import type { City } from './city-types'

export const CITIES_NORTHEAST: City[] = [
  // ── New York (NY) ─────────────────────────────────────────────────────────
  { name: 'Troy', slug: 'troy-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 49170 },
  { name: 'Amherst', slug: 'amherst-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 126082 },
  { name: 'Cheektowaga', slug: 'cheektowaga-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 88226 },
  { name: 'Niagara Falls', slug: 'niagara-falls-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 48671 },
  { name: 'Tonawanda', slug: 'tonawanda-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 72884 },
  { name: 'Smithtown', slug: 'smithtown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 116017 },
  { name: 'Hempstead', slug: 'hempstead-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 55361 },
  { name: 'Freeport', slug: 'freeport-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 43713 },
  { name: 'Oceanside', slug: 'oceanside-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 32109 },
  { name: 'Valley Stream', slug: 'valley-stream-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 37545 },
  { name: 'Hicksville', slug: 'hicksville-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 41547 },
  { name: 'Levittown', slug: 'levittown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 51881 },
  { name: 'Patchogue', slug: 'patchogue-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 12255 },
  { name: 'Commack', slug: 'commack-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 36124 },
  { name: 'Brentwood', slug: 'brentwood-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 60664 },
  { name: 'North Babylon', slug: 'north-babylon-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 17468 },
  { name: 'West Islip', slug: 'west-islip-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 28335 },
  { name: 'Huntington', slug: 'huntington-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 203264 },
  { name: 'Port Chester', slug: 'port-chester-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 29387 },
  { name: 'Spring Valley', slug: 'spring-valley-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 31347 },
  { name: 'Ramapo', slug: 'ramapo-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 136905 },
  { name: 'Brookhaven', slug: 'brookhaven-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 486040 },
  { name: 'Islip', slug: 'islip-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 335543 },
  { name: 'Babylon', slug: 'babylon-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 213603 },
  { name: 'Oyster Bay', slug: 'oyster-bay-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 293925 },
  { name: 'Glen Cove', slug: 'glen-cove-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 27164 },
  { name: 'Long Beach', slug: 'long-beach-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 33275 },
  { name: 'Saratoga Springs', slug: 'saratoga-springs-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 28491 },
  { name: 'Watertown', slug: 'watertown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 25591 },
  { name: 'Poughkeepsie', slug: 'poughkeepsie-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 30515 },
  { name: 'Kingston', slug: 'kingston-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 24043 },
  { name: 'Middletown', slug: 'middletown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 28086 },
  { name: 'Newburgh', slug: 'newburgh-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 29141 },
  { name: 'Peekskill', slug: 'peekskill-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 24033 },
  { name: 'Elmira', slug: 'elmira-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 28846 },
  { name: 'Ithaca', slug: 'ithaca-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 32968 },
  { name: 'Glens Falls', slug: 'glens-falls-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 14700 },
  { name: 'Plattsburgh', slug: 'plattsburgh-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 19989 },
  { name: 'Cortland', slug: 'cortland-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 18623 },
  { name: 'Jamestown', slug: 'jamestown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 28712 },
  { name: 'Oswego', slug: 'oswego-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 17560 },
  { name: 'Rome', slug: 'rome-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 32861 },
  { name: 'Oneida', slug: 'oneida-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 11392 },
  { name: 'Lockport', slug: 'lockport-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 20897 },
  { name: 'Ossining', slug: 'ossining-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 26554 },
  { name: 'Tarrytown', slug: 'tarrytown-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 11277 },
  { name: 'Harrison', slug: 'harrison-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 29127 },
  { name: 'Mamaroneck', slug: 'mamaroneck-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 19163 },
  { name: 'Mount Kisco', slug: 'mount-kisco-ny', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 10877 },

  // ── Pennsylvania (PA) ────────────────────────────────────────────────────
  { name: 'Allentown', slug: 'allentown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 125845 },
  { name: 'Erie', slug: 'erie-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 94831 },
  { name: 'Reading', slug: 'reading-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 95112 },
  { name: 'Scranton', slug: 'scranton-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 76089 },
  { name: 'Bethlehem', slug: 'bethlehem-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 75781 },
  { name: 'Lancaster', slug: 'lancaster-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 59322 },
  { name: 'Harrisburg', slug: 'harrisburg-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 50135 },
  { name: 'Altoona', slug: 'altoona-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 43687 },
  { name: 'York', slug: 'york-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 44867 },
  { name: 'State College', slug: 'state-college-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 42034 },
  { name: 'Wilkes-Barre', slug: 'wilkes-barre-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 40806 },
  { name: 'Chester', slug: 'chester-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 33972 },
  { name: 'Norristown', slug: 'norristown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 34324 },
  { name: 'Easton', slug: 'easton-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 27573 },
  { name: 'Lebanon', slug: 'lebanon-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 25477 },
  { name: 'Hazleton', slug: 'hazleton-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 25340 },
  { name: 'McKeesport', slug: 'mckeesport-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 19301 },
  { name: 'Abington', slug: 'abington-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 55831 },
  { name: 'Upper Darby', slug: 'upper-darby-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 81821 },
  { name: 'Bensalem', slug: 'bensalem-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 60427 },
  { name: 'Levittown', slug: 'levittown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 52983 },
  { name: 'Bethel Park', slug: 'bethel-park-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 32313 },
  { name: 'Monroeville', slug: 'monroeville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 28386 },
  { name: 'Penn Hills', slug: 'penn-hills-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 42329 },
  { name: 'Plum', slug: 'plum-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 27126 },
  { name: 'Murrysville', slug: 'murrysville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 20079 },
  { name: 'Cranberry Township', slug: 'cranberry-township-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 32050 },
  { name: 'Mt. Lebanon', slug: 'mt-lebanon-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 33137 },
  { name: 'Latrobe', slug: 'latrobe-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 8338 },
  { name: 'Carlisle', slug: 'carlisle-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 19188 },
  { name: 'Chambersburg', slug: 'chambersburg-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 22000 },
  { name: 'Pottstown', slug: 'pottstown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 22377 },
  { name: 'Williamsport', slug: 'williamsport-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 28322 },
  { name: 'Greensburg', slug: 'greensburg-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 14677 },
  { name: 'Johnstown', slug: 'johnstown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 19447 },
  { name: 'Aliquippa', slug: 'aliquippa-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 9438 },
  { name: 'Radnor', slug: 'radnor-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 31531 },
  { name: 'Horsham', slug: 'horsham-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 26147 },
  { name: 'Doylestown', slug: 'doylestown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 8380 },
  { name: 'Newtown', slug: 'newtown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 2248 },
  { name: 'Media', slug: 'media-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 5533 },
  { name: 'Lansdale', slug: 'lansdale-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 16971 },
  { name: 'King of Prussia', slug: 'king-of-prussia-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 20050 },
  { name: 'West Chester', slug: 'west-chester-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 18461 },
  { name: 'Coatesville', slug: 'coatesville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 13100 },
  { name: 'Phoenixville', slug: 'phoenixville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 16440 },
  { name: 'Pottsville', slug: 'pottsville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 13904 },
  { name: 'Sunbury', slug: 'sunbury-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 9905 },
  { name: 'Bloomsburg', slug: 'bloomsburg-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 14855 },
  { name: 'Lock Haven', slug: 'lock-haven-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 8944 },
  { name: 'Meadville', slug: 'meadville-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 13388 },
  { name: 'Butler', slug: 'butler-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 13299 },
  { name: 'New Castle', slug: 'new-castle-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 22128 },
  { name: 'Uniontown', slug: 'uniontown-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 9983 },
  { name: 'Carbondale', slug: 'carbondale-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 8764 },
  { name: 'Stroudsburg', slug: 'stroudsburg-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 5744 },
  { name: 'Hanover', slug: 'hanover-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 15930 },
  { name: 'Indiana', slug: 'indiana-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 13975 },
  { name: 'Du Bois', slug: 'du-bois-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 7616 },
  { name: 'Oil City', slug: 'oil-city-pa', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 9860 },

  // ── New Jersey (NJ) ──────────────────────────────────────────────────────
  { name: 'Newark', slug: 'newark-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 311549 },
  { name: 'Jersey City', slug: 'jersey-city-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 292449 },
  { name: 'Paterson', slug: 'paterson-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 159732 },
  { name: 'Elizabeth', slug: 'elizabeth-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 137298 },
  { name: 'Edison', slug: 'edison-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 107588 },
  { name: 'Woodbridge', slug: 'woodbridge-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 101265 },
  { name: 'Lakewood', slug: 'lakewood-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 135158 },
  { name: 'Toms River', slug: 'toms-river-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 97313 },
  { name: 'Hamilton', slug: 'hamilton-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 92297 },
  { name: 'Clifton', slug: 'clifton-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 89456 },
  { name: 'Trenton', slug: 'trenton-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 90871 },
  { name: 'Camden', slug: 'camden-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 71791 },
  { name: 'Brick', slug: 'brick-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 75072 },
  { name: 'Cherry Hill', slug: 'cherry-hill-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 71045 },
  { name: 'Passaic', slug: 'passaic-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 70868 },
  { name: 'Middletown', slug: 'middletown-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 66522 },
  { name: 'Union City', slug: 'union-city-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 70387 },
  { name: 'Old Bridge', slug: 'old-bridge-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 65387 },
  { name: 'Gloucester Township', slug: 'gloucester-township-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 64350 },
  { name: 'East Orange', slug: 'east-orange-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 69824 },
  { name: 'Bayonne', slug: 'bayonne-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 67800 },
  { name: 'Franklin', slug: 'franklin-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 65652 },
  { name: 'North Bergen', slug: 'north-bergen-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 60773 },
  { name: 'Vineland', slug: 'vineland-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 60724 },
  { name: 'Union', slug: 'union-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 58255 },
  { name: 'Piscataway', slug: 'piscataway-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 57378 },
  { name: 'New Brunswick', slug: 'new-brunswick-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 56100 },
  { name: 'Jackson', slug: 'jackson-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 58008 },
  { name: 'Wayne', slug: 'wayne-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 55000 },
  { name: 'Irvington', slug: 'irvington-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 54040 },
  { name: 'Parsippany', slug: 'parsippany-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 52699 },
  { name: 'Hackensack', slug: 'hackensack-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 44411 },
  { name: 'Sayreville', slug: 'sayreville-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 44412 },
  { name: 'Perth Amboy', slug: 'perth-amboy-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 55436 },
  { name: 'Howell', slug: 'howell-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 51940 },
  { name: 'Kearny', slug: 'kearny-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 43101 },
  { name: 'Linden', slug: 'linden-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 42775 },
  { name: 'Atlantic City', slug: 'atlantic-city-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 37743 },
  { name: 'Plainfield', slug: 'plainfield-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 49808 },
  { name: 'West Orange', slug: 'west-orange-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 47715 },
  { name: 'Hoboken', slug: 'hoboken-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 60419 },
  { name: 'Montclair', slug: 'montclair-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 38977 },
  { name: 'Bloomfield', slug: 'bloomfield-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 47315 },
  { name: 'Belleville', slug: 'belleville-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 36878 },
  { name: 'Livingston', slug: 'livingston-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 29366 },
  { name: 'Maplewood', slug: 'maplewood-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 24378 },
  { name: 'South Orange', slug: 'south-orange-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 16486 },
  { name: 'Millville', slug: 'millville-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 28400 },
  { name: 'Bridgeton', slug: 'bridgeton-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 25349 },
  { name: 'Bergenfield', slug: 'bergenfield-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 27203 },
  { name: 'Garfield', slug: 'garfield-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 32684 },
  { name: 'Ewing', slug: 'ewing-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 36000 },
  { name: 'Red Bank', slug: 'red-bank-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 12206 },
  { name: 'Asbury Park', slug: 'asbury-park-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 15634 },
  { name: 'Long Branch', slug: 'long-branch-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 30686 },
  { name: 'Freehold', slug: 'freehold-nj', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 12052 },

  // ── Connecticut (CT) ─────────────────────────────────────────────────────
  { name: 'Bridgeport', slug: 'bridgeport-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 148654 },
  { name: 'New Haven', slug: 'new-haven-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 130250 },
  { name: 'Hartford', slug: 'hartford-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 121054 },
  { name: 'Stamford', slug: 'stamford-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 135470 },
  { name: 'Waterbury', slug: 'waterbury-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 114403 },
  { name: 'Norwalk', slug: 'norwalk-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 91184 },
  { name: 'Danbury', slug: 'danbury-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 84694 },
  { name: 'New Britain', slug: 'new-britain-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 73206 },
  { name: 'West Hartford', slug: 'west-hartford-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 63268 },
  { name: 'Greenwich', slug: 'greenwich-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 62396 },
  { name: 'Hamden', slug: 'hamden-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 61476 },
  { name: 'Bristol', slug: 'bristol-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 60477 },
  { name: 'Meriden', slug: 'meriden-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 59479 },
  { name: 'Manchester', slug: 'manchester-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 58241 },
  { name: 'West Haven', slug: 'west-haven-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 55564 },
  { name: 'Milford', slug: 'milford-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 52759 },
  { name: 'Stratford', slug: 'stratford-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 52729 },
  { name: 'Glastonbury', slug: 'glastonbury-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 34427 },
  { name: 'Shelton', slug: 'shelton-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 41475 },
  { name: 'Norwich', slug: 'norwich-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 40175 },
  { name: 'Torrington', slug: 'torrington-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 35515 },
  { name: 'Naugatuck', slug: 'naugatuck-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 31862 },
  { name: 'Trumbull', slug: 'trumbull-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 36018 },
  { name: 'Cheshire', slug: 'cheshire-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 29261 },
  { name: 'Southington', slug: 'southington-ct', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 43069 },

  // ── Massachusetts (MA) ───────────────────────────────────────────────────
  { name: 'Cambridge', slug: 'cambridge-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 118403 },
  { name: 'Lowell', slug: 'lowell-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 115554 },
  { name: 'Brockton', slug: 'brockton-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 105643 },
  { name: 'New Bedford', slug: 'new-bedford-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 101079 },
  { name: 'Quincy', slug: 'quincy-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 101636 },
  { name: 'Lynn', slug: 'lynn-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 101253 },
  { name: 'Fall River', slug: 'fall-river-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 94942 },
  { name: 'Newton', slug: 'newton-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 88923 },
  { name: 'Somerville', slug: 'somerville-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 81175 },
  { name: 'Lawrence', slug: 'lawrence-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 80376 },
  { name: 'Framingham', slug: 'framingham-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 72362 },
  { name: 'Haverhill', slug: 'haverhill-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 65110 },
  { name: 'Waltham', slug: 'waltham-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 62765 },
  { name: 'Malden', slug: 'malden-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 60509 },
  { name: 'Brookline', slug: 'brookline-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 59121 },
  { name: 'Plymouth', slug: 'plymouth-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 61217 },
  { name: 'Medford', slug: 'medford-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 58004 },
  { name: 'Taunton', slug: 'taunton-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 57464 },
  { name: 'Chicopee', slug: 'chicopee-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 55298 },
  { name: 'Weymouth', slug: 'weymouth-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 55643 },
  { name: 'Peabody', slug: 'peabody-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 54074 },
  { name: 'Revere', slug: 'revere-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 53756 },
  { name: 'Methuen', slug: 'methuen-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 50055 },
  { name: 'Barnstable', slug: 'barnstable-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 45193 },
  { name: 'Pittsfield', slug: 'pittsfield-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 42364 },
  { name: 'Attleboro', slug: 'attleboro-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 45257 },
  { name: 'Leominster', slug: 'leominster-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 41303 },
  { name: 'Salem', slug: 'salem-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 44267 },
  { name: 'Fitchburg', slug: 'fitchburg-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 40759 },
  { name: 'Westfield', slug: 'westfield-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 41301 },
  { name: 'Beverly', slug: 'beverly-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 42034 },
  { name: 'Holyoke', slug: 'holyoke-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 36704 },
  { name: 'Marlborough', slug: 'marlborough-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 39414 },
  { name: 'Woburn', slug: 'woburn-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 40977 },
  { name: 'Gloucester', slug: 'gloucester-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 30272 },
  { name: 'Northampton', slug: 'northampton-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 28984 },
  { name: 'Chelsea', slug: 'chelsea-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 40975 },
  { name: 'Everett', slug: 'everett-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 46451 },
  { name: 'Watertown', slug: 'watertown-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 35939 },
  { name: 'Randolph', slug: 'randolph-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 34284 },
  { name: 'Andover', slug: 'andover-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 36569 },
  { name: 'Dedham', slug: 'dedham-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 25364 },

  // ── Maryland (MD) ────────────────────────────────────────────────────────
  { name: 'Frederick', slug: 'frederick-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 78171 },
  { name: 'Rockville', slug: 'rockville-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 67117 },
  { name: 'Gaithersburg', slug: 'gaithersburg-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 68890 },
  { name: 'Bowie', slug: 'bowie-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 58682 },
  { name: 'Hagerstown', slug: 'hagerstown-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 43143 },
  { name: 'Annapolis', slug: 'annapolis-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 40812 },
  { name: 'College Park', slug: 'college-park-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 32459 },
  { name: 'Salisbury', slug: 'salisbury-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 33941 },
  { name: 'Laurel', slug: 'laurel-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 26342 },
  { name: 'Greenbelt', slug: 'greenbelt-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 24441 },
  { name: 'Cumberland', slug: 'cumberland-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 18518 },
  { name: 'Westminster', slug: 'westminster-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 19059 },
  { name: 'Hyattsville', slug: 'hyattsville-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 22000 },
  { name: 'Towson', slug: 'towson-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 57583 },
  { name: 'Ellicott City', slug: 'ellicott-city-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 72585 },
  { name: 'Columbia', slug: 'columbia-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 103587 },
  { name: 'Germantown', slug: 'germantown-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 86395 },
  { name: 'Silver Spring', slug: 'silver-spring-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 81015 },
  { name: 'Bethesda', slug: 'bethesda-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 62936 },
  { name: 'Waldorf', slug: 'waldorf-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 67752 },
  { name: 'Dundalk', slug: 'dundalk-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 63597 },
  { name: 'Essex', slug: 'essex-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 39262 },
  { name: 'Parkville', slug: 'parkville-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 30734 },
  { name: 'Catonsville', slug: 'catonsville-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 41567 },

  // ── Washington DC ─────────────────────────────────────────────────────────
  { name: 'Washington', slug: 'washington-dc', state: 'District of Columbia', stateSlug: 'district-of-columbia', stateAbbr: 'DC', population: 689545 },

  // ── Delaware (DE) ────────────────────────────────────────────────────────
  { name: 'Wilmington', slug: 'wilmington-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 70898 },
  { name: 'Dover', slug: 'dover-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 39403 },
  { name: 'Newark', slug: 'newark-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 33398 },
  { name: 'Middletown', slug: 'middletown-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 24067 },
  { name: 'Smyrna', slug: 'smyrna-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 12432 },
  { name: 'Milford', slug: 'milford-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 11836 },
  { name: 'Seaford', slug: 'seaford-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 8186 },
  { name: 'Georgetown', slug: 'georgetown-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 7234 },

  // ── Vermont (VT) ─────────────────────────────────────────────────────────
  { name: 'Burlington', slug: 'burlington-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 45012 },
  { name: 'South Burlington', slug: 'south-burlington-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 20292 },
  { name: 'Rutland', slug: 'rutland-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 15314 },
  { name: 'Barre', slug: 'barre-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 8747 },
  { name: 'Montpelier', slug: 'montpelier-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 7855 },
  { name: 'Winooski', slug: 'winooski-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 7267 },

  // ── Maine (ME) ───────────────────────────────────────────────────────────
  { name: 'Portland', slug: 'portland-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 68408 },
  { name: 'Lewiston', slug: 'lewiston-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 37121 },
  { name: 'Bangor', slug: 'bangor-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 31903 },
  { name: 'South Portland', slug: 'south-portland-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 26291 },
  { name: 'Auburn', slug: 'auburn-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 24061 },
  { name: 'Biddeford', slug: 'biddeford-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 22080 },
  { name: 'Sanford', slug: 'sanford-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 21267 },
  { name: 'Augusta', slug: 'augusta-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 18697 },

  // ── Rhode Island (RI) ────────────────────────────────────────────────────
  { name: 'Pawtucket', slug: 'pawtucket-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 72958 },
  { name: 'East Providence', slug: 'east-providence-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 47958 },
  { name: 'Woonsocket', slug: 'woonsocket-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 41186 },
  { name: 'Coventry', slug: 'coventry-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 35668 },
  { name: 'Cumberland', slug: 'cumberland-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 35966 },
  { name: 'North Providence', slug: 'north-providence-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 32433 },
  { name: 'West Warwick', slug: 'west-warwick-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 29581 },
  { name: 'Johnston', slug: 'johnston-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 29568 },
  { name: 'Smithfield', slug: 'smithfield-ri', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 21963 },

  // ── New Hampshire (NH) ───────────────────────────────────────────────────
  { name: 'Dover', slug: 'dover-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 32105 },
  { name: 'Rochester', slug: 'rochester-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 32413 },
  { name: 'Keene', slug: 'keene-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 23409 },
  { name: 'Derry', slug: 'derry-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 34317 },
  { name: 'Londonderry', slug: 'londonderry-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 26203 },
  { name: 'Exeter', slug: 'exeter-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 14306 },
  { name: 'Hampton', slug: 'hampton-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 15430 },
  { name: 'Salem', slug: 'salem-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 30132 },
  { name: 'Merrimack', slug: 'merrimack-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 27594 },
  { name: 'Goffstown', slug: 'goffstown-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 17651 },
  { name: 'Laconia', slug: 'laconia-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 16141 },
  { name: 'Claremont', slug: 'claremont-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 13355 },
  { name: 'Somersworth', slug: 'somersworth-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 11766 },
  { name: 'Berlin', slug: 'berlin-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 10051 },
]
