import type { City } from './city-types'

export const CITIES_SOUTH: City[] = [

  // ── TEXAS (additional cities beyond Houston, Dallas, San Antonio, Austin in cities.ts) ──
  { name: 'Fort Worth', slug: 'fort-worth', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 935508 },
  { name: 'El Paso', slug: 'el-paso', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 678815 },
  { name: 'Arlington', slug: 'arlington-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 395600 },
  { name: 'Corpus Christi', slug: 'corpus-christi', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 317863 },
  { name: 'Plano', slug: 'plano', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 285494 },
  { name: 'Laredo', slug: 'laredo', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 255205 },
  { name: 'Lubbock', slug: 'lubbock', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 258862 },
  { name: 'Garland', slug: 'garland', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 246018 },
  { name: 'Irving', slug: 'irving', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 240373 },
  { name: 'Amarillo', slug: 'amarillo', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 200393 },
  { name: 'Grand Prairie', slug: 'grand-prairie', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 196100 },
  { name: 'Brownsville', slug: 'brownsville', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 186738 },
  { name: 'McKinney', slug: 'mckinney', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 195308 },
  { name: 'Frisco', slug: 'frisco', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 200509 },
  { name: 'Pasadena', slug: 'pasadena-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 151950 },
  { name: 'Killeen', slug: 'killeen', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 153095 },
  { name: 'McAllen', slug: 'mcallen', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 142212 },
  { name: 'Mesquite', slug: 'mesquite', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 143484 },
  { name: 'Denton', slug: 'denton', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 139869 },
  { name: 'Waco', slug: 'waco', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 138183 },
  { name: 'Midland', slug: 'midland-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 132950 },
  { name: 'Carrollton', slug: 'carrollton', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 133434 },
  { name: 'Round Rock', slug: 'round-rock', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 133372 },
  { name: 'Abilene', slug: 'abilene', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 123420 },
  { name: 'Beaumont', slug: 'beaumont', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 112314 },
  { name: 'Odessa', slug: 'odessa-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 120588 },
  { name: 'Sugar Land', slug: 'sugar-land', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 111026 },
  { name: 'Pearland', slug: 'pearland', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 122649 },
  { name: 'The Woodlands', slug: 'the-woodlands', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 114436 },
  { name: 'Richardson', slug: 'richardson', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 115169 },
  { name: 'Lewisville', slug: 'lewisville', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 111822 },
  { name: 'Allen', slug: 'allen-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 105623 },
  { name: 'League City', slug: 'league-city', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 111931 },
  { name: 'College Station', slug: 'college-station', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 115142 },
  { name: 'Tyler', slug: 'tyler', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 105525 },
  { name: 'Edinburg', slug: 'edinburg', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 100393 },
  { name: 'Wichita Falls', slug: 'wichita-falls', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 102051 },
  { name: 'San Marcos', slug: 'san-marcos', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 67553 },
  { name: 'Georgetown', slug: 'georgetown-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 67176 },
  { name: 'Conroe', slug: 'conroe', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 92796 },
  { name: 'Longview', slug: 'longview-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 82157 },
  { name: 'Baytown', slug: 'baytown', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 78123 },
  { name: 'New Braunfels', slug: 'new-braunfels', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 90800 },
  { name: 'Flower Mound', slug: 'flower-mound', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 79156 },
  { name: 'Mansfield', slug: 'mansfield-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 73235 },
  { name: 'Mission', slug: 'mission-tx', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 86316 },
  { name: 'Harlingen', slug: 'harlingen', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 73139 },

  // ── FLORIDA (additional cities beyond Miami, Jacksonville, Tampa, Orlando, St. Pete in cities.ts) ──
  { name: 'Hialeah', slug: 'hialeah', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 223109 },
  { name: 'Tallahassee', slug: 'tallahassee', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 194500 },
  { name: 'Fort Lauderdale', slug: 'fort-lauderdale', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 182760 },
  { name: 'Port St. Lucie', slug: 'port-saint-lucie', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 201846 },
  { name: 'Cape Coral', slug: 'cape-coral', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 194016 },
  { name: 'Miramar', slug: 'miramar', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 136232 },
  { name: 'Pembroke Pines', slug: 'pembroke-pines', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 171178 },
  { name: 'Hollywood', slug: 'hollywood-fl', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 153067 },
  { name: 'Gainesville', slug: 'gainesville', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 141085 },
  { name: 'Coral Springs', slug: 'coral-springs', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 134394 },
  { name: 'Lakeland', slug: 'lakeland', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 112641 },
  { name: 'Clearwater', slug: 'clearwater', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 115370 },
  { name: 'Palm Bay', slug: 'palm-bay', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 117415 },
  { name: 'Pompano Beach', slug: 'pompano-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 112887 },
  { name: 'West Palm Beach', slug: 'west-palm-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 111398 },
  { name: 'Davie', slug: 'davie', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 100641 },
  { name: 'Fort Myers', slug: 'fort-myers', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 86395 },
  { name: 'Boca Raton', slug: 'boca-raton', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 99805 },
  { name: 'Melbourne', slug: 'melbourne-fl', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 83988 },
  { name: 'Sarasota', slug: 'sarasota', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 58285 },
  { name: 'Delray Beach', slug: 'delray-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 69451 },
  { name: 'Daytona Beach', slug: 'daytona-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 68149 },
  { name: 'Deerfield Beach', slug: 'deerfield-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 86859 },
  { name: 'Plantation', slug: 'plantation-fl', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 91750 },
  { name: 'Palm Coast', slug: 'palm-coast', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 86986 },
  { name: 'Boynton Beach', slug: 'boynton-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 78210 },
  { name: 'Naples', slug: 'naples-fl', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 22161 },
  { name: 'Pensacola', slug: 'pensacola', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 53888 },
  { name: 'Ocala', slug: 'ocala', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 63591 },

  // ── GEORGIA (additional cities beyond Atlanta in cities.ts) ──
  { name: 'Columbus', slug: 'columbus-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 206922 },
  { name: 'Augusta', slug: 'augusta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 202081 },
  { name: 'Savannah', slug: 'savannah', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 147810 },
  { name: 'Macon', slug: 'macon', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 153159 },
  { name: 'Sandy Springs', slug: 'sandy-springs', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 108228 },
  { name: 'Athens', slug: 'athens-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 127315 },
  { name: 'South Fulton', slug: 'south-fulton', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 107436 },
  { name: 'Roswell', slug: 'roswell-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 92833 },
  { name: 'Johns Creek', slug: 'johns-creek', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 82788 },
  { name: 'Albany', slug: 'albany-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 70669 },
  { name: 'Warner Robins', slug: 'warner-robins', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 80308 },
  { name: 'Alpharetta', slug: 'alpharetta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 65818 },
  { name: 'Marietta', slug: 'marietta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 60972 },
  { name: 'Smyrna', slug: 'smyrna-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 56884 },
  { name: 'Valdosta', slug: 'valdosta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 57286 },
  { name: 'Gainesville', slug: 'gainesville-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 41429 },
  { name: 'Peachtree City', slug: 'peachtree-city', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 37034 },
  { name: 'Tucker', slug: 'tucker-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 37322 },

  // ── NORTH CAROLINA (additional cities beyond Charlotte, Raleigh in cities.ts) ──
  { name: 'Greensboro', slug: 'greensboro', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 296710 },
  { name: 'Durham', slug: 'durham', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 283506 },
  { name: 'Winston-Salem', slug: 'winston-salem', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 249545 },
  { name: 'Fayetteville', slug: 'fayetteville-nc', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 208501 },
  { name: 'Cary', slug: 'cary', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 170282 },
  { name: 'Wilmington', slug: 'wilmington-nc', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 123784 },
  { name: 'High Point', slug: 'high-point', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 112791 },
  { name: 'Concord', slug: 'concord-nc', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 105240 },
  { name: 'Asheville', slug: 'asheville', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 94589 },
  { name: 'Gastonia', slug: 'gastonia', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 80411 },
  { name: 'Chapel Hill', slug: 'chapel-hill', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 61960 },
  { name: 'Huntersville', slug: 'huntersville', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 60220 },
  { name: 'Burlington', slug: 'burlington-nc', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 57960 },

  // ── VIRGINIA (additional cities beyond Virginia Beach, Richmond in cities.ts) ──
  { name: 'Chesapeake', slug: 'chesapeake', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 244835 },
  { name: 'Norfolk', slug: 'norfolk', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 238005 },
  { name: 'Arlington', slug: 'arlington-va', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 238643 },
  { name: 'Newport News', slug: 'newport-news', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 185247 },
  { name: 'Alexandria', slug: 'alexandria', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 155810 },
  { name: 'Hampton', slug: 'hampton', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 134510 },
  { name: 'Roanoke', slug: 'roanoke', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 99143 },
  { name: 'Portsmouth', slug: 'portsmouth-va', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 95311 },
  { name: 'Suffolk', slug: 'suffolk', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 94324 },
  { name: 'Lynchburg', slug: 'lynchburg', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 82168 },
  { name: 'Charlottesville', slug: 'charlottesville', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 46912 },
  { name: 'Harrisonburg', slug: 'harrisonburg', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 54142 },
  { name: 'Reston', slug: 'reston', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 61000 },
  { name: 'McLean', slug: 'mclean', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 48115 },
  { name: 'Blacksburg', slug: 'blacksburg', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 44826 },
  { name: 'Tysons', slug: 'tysons', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 24000 },

  // ── TENNESSEE (additional cities beyond Nashville, Memphis in cities.ts) ──
  { name: 'Knoxville', slug: 'knoxville', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 190740 },
  { name: 'Chattanooga', slug: 'chattanooga', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 181099 },
  { name: 'Clarksville', slug: 'clarksville', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 166722 },
  { name: 'Murfreesboro', slug: 'murfreesboro', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 152769 },
  { name: 'Franklin', slug: 'franklin-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 83454 },
  { name: 'Jackson', slug: 'jackson-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 67685 },
  { name: 'Johnson City', slug: 'johnson-city', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 67831 },
  { name: 'Hendersonville', slug: 'hendersonville-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 59296 },
  { name: 'Kingsport', slug: 'kingsport', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 55442 },
  { name: 'Brentwood', slug: 'brentwood-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 45766 },
  { name: 'Columbia', slug: 'columbia-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 39234 },
  { name: 'Smyrna', slug: 'smyrna-tn', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 52547 },

  // ── SOUTH CAROLINA ──
  { name: 'Columbia', slug: 'columbia-sc', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 136885 },
  { name: 'Charleston', slug: 'charleston', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 150277 },
  { name: 'North Charleston', slug: 'north-charleston', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 114852 },
  { name: 'Mount Pleasant', slug: 'mount-pleasant-sc', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 91684 },
  { name: 'Rock Hill', slug: 'rock-hill', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 75048 },
  { name: 'Greenville', slug: 'greenville-sc', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 70635 },
  { name: 'Summerville', slug: 'summerville', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 52549 },
  { name: 'Sumter', slug: 'sumter', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 40938 },
  { name: 'Goose Creek', slug: 'goose-creek', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 44692 },
  { name: 'Hilton Head Island', slug: 'hilton-head', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 39727 },
  { name: 'Florence', slug: 'florence-sc', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 37792 },
  { name: 'Spartanburg', slug: 'spartanburg', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 37646 },

  // ── ALABAMA ──
  { name: 'Birmingham', slug: 'birmingham', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 212237 },
  { name: 'Montgomery', slug: 'montgomery', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 199518 },
  { name: 'Huntsville', slug: 'huntsville', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 215006 },
  { name: 'Mobile', slug: 'mobile', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 187041 },
  { name: 'Tuscaloosa', slug: 'tuscaloosa', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 99543 },
  { name: 'Hoover', slug: 'hoover', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 84126 },
  { name: 'Dothan', slug: 'dothan', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 71072 },
  { name: 'Auburn', slug: 'auburn-al', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 76143 },
  { name: 'Decatur', slug: 'decatur-al', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 52208 },
  { name: 'Madison', slug: 'madison-al', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 48174 },
  { name: 'Florence', slug: 'florence-al', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 40229 },
  { name: 'Gadsden', slug: 'gadsden', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 32673 },

  // ── LOUISIANA (additional beyond New Orleans in cities.ts) ──
  { name: 'Baton Rouge', slug: 'baton-rouge', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 220236 },
  { name: 'Shreveport', slug: 'shreveport', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 179325 },
  { name: 'Metairie', slug: 'metairie', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 142489 },
  { name: 'Lafayette', slug: 'lafayette-la', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 121374 },
  { name: 'Lake Charles', slug: 'lake-charles', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 84872 },
  { name: 'Bossier City', slug: 'bossier-city', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 68468 },
  { name: 'Monroe', slug: 'monroe-la', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 45382 },
  { name: 'Alexandria', slug: 'alexandria-la', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 45215 },
  { name: 'Slidell', slug: 'slidell', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 27982 },
  { name: 'Kenner', slug: 'kenner', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 66702 },

  // ── KENTUCKY ──
  { name: 'Louisville', slug: 'louisville', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 633045 },
  { name: 'Lexington', slug: 'lexington-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 322570 },
  { name: 'Bowling Green', slug: 'bowling-green', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 72294 },
  { name: 'Owensboro', slug: 'owensboro', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 59508 },
  { name: 'Covington', slug: 'covington-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 43022 },
  { name: 'Richmond', slug: 'richmond-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 35697 },
  { name: 'Georgetown', slug: 'georgetown-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 36073 },
  { name: 'Florence', slug: 'florence-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 32963 },
  { name: 'Elizabethtown', slug: 'elizabethtown', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 31461 },
  { name: 'Nicholasville', slug: 'nicholasville', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 34402 },
  { name: 'Paducah', slug: 'paducah', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 26865 },
  { name: 'Hopkinsville', slug: 'hopkinsville', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 32034 },

  // ── OKLAHOMA (additional beyond Oklahoma City, Tulsa in cities.ts) ──
  { name: 'Norman', slug: 'norman', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 128026 },
  { name: 'Broken Arrow', slug: 'broken-arrow', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 113540 },
  { name: 'Lawton', slug: 'lawton', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 92757 },
  { name: 'Edmond', slug: 'edmond', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 95380 },
  { name: 'Moore', slug: 'moore-ok', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 62793 },
  { name: 'Midwest City', slug: 'midwest-city', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 57364 },
  { name: 'Stillwater', slug: 'stillwater-ok', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 50299 },
  { name: 'Muskogee', slug: 'muskogee', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 36388 },
  { name: 'Enid', slug: 'enid', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 50145 },
  { name: 'Owasso', slug: 'owasso', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 38680 },

  // ── MISSISSIPPI ──
  { name: 'Jackson', slug: 'jackson-ms', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 153701 },
  { name: 'Gulfport', slug: 'gulfport', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 72926 },
  { name: 'Southaven', slug: 'southaven', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 55282 },
  { name: 'Hattiesburg', slug: 'hattiesburg', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 47806 },
  { name: 'Biloxi', slug: 'biloxi', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 46319 },
  { name: 'Meridian', slug: 'meridian', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 40922 },
  { name: 'Olive Branch', slug: 'olive-branch', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 38280 },
  { name: 'Tupelo', slug: 'tupelo', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 38845 },

  // ── ARKANSAS ──
  { name: 'Little Rock', slug: 'little-rock', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 202591 },
  { name: 'Fort Smith', slug: 'fort-smith', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 89142 },
  { name: 'Fayetteville', slug: 'fayetteville-ar', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 93949 },
  { name: 'Springdale', slug: 'springdale', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 83887 },
  { name: 'Jonesboro', slug: 'jonesboro', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 78576 },
  { name: 'North Little Rock', slug: 'north-little-rock', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 65994 },
  { name: 'Rogers', slug: 'rogers-ar', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 68572 },
  { name: 'Conway', slug: 'conway-ar', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 66834 },
  { name: 'Bentonville', slug: 'bentonville', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 54164 },
  { name: 'Pine Bluff', slug: 'pine-bluff', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 41474 },

  // ── WEST VIRGINIA ──
  { name: 'Charleston', slug: 'charleston-wv', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 46536 },
  { name: 'Huntington', slug: 'huntington-wv', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 43542 },
  { name: 'Morgantown', slug: 'morgantown', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 30955 },
  { name: 'Parkersburg', slug: 'parkersburg', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 29703 },
  { name: 'Wheeling', slug: 'wheeling-wv', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 26915 },
  { name: 'Weirton', slug: 'weirton', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 18608 },

]
