import type { City } from './city-types'

export const CITIES_WEST: City[] = [
  // ── CALIFORNIA (additional cities not in cities.ts) ──
  // Bay Area
  { name: 'Hayward', slug: 'hayward', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 162954 },
  { name: 'Concord', slug: 'concord', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 129295 },
  { name: 'Berkeley', slug: 'berkeley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 124321 },
  { name: 'Richmond', slug: 'richmond-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 116448 },
  { name: 'Antioch', slug: 'antioch', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 115000 },
  { name: 'Daly City', slug: 'daly-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 107100 },
  { name: 'Fairfield', slug: 'fairfield', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 117786 },
  { name: 'Vallejo', slug: 'vallejo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 124760 },
  { name: 'South San Francisco', slug: 'south-san-francisco', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 67271 },
  { name: 'San Leandro', slug: 'san-leandro', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 90000 },
  { name: 'Livermore', slug: 'livermore', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 93144 },
  { name: 'Pleasanton', slug: 'pleasanton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 82666 },
  { name: 'Walnut Creek', slug: 'walnut-creek', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 71061 },
  { name: 'Union City', slug: 'union-city-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 75000 },
  { name: 'Dublin', slug: 'dublin-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 74000 },
  { name: 'Alameda', slug: 'alameda', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 79000 },
  { name: 'Pittsburg', slug: 'pittsburg-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 73000 },
  { name: 'Brentwood', slug: 'brentwood-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 63600 },
  { name: 'San Pablo', slug: 'san-pablo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 32000 },
  { name: 'El Cerrito', slug: 'el-cerrito', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 26000 },
  { name: 'Newark', slug: 'newark-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 48000 },
  { name: 'Milpitas', slug: 'milpitas', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 77820 },
  { name: 'Campbell', slug: 'campbell', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 42000 },
  { name: 'Los Gatos', slug: 'los-gatos', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 33000 },
  { name: 'Saratoga', slug: 'saratoga-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 31000 },
  { name: 'Los Altos', slug: 'los-altos', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 31000 },
  { name: 'Burlingame', slug: 'burlingame', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 32000 },
  { name: 'San Bruno', slug: 'san-bruno', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 45000 },
  { name: 'Millbrae', slug: 'millbrae', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 23000 },
  { name: 'Foster City', slug: 'foster-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 33000 },
  { name: 'Emeryville', slug: 'emeryville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 13000 },
  { name: 'Belmont', slug: 'belmont-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 27000 },
  { name: 'San Carlos', slug: 'san-carlos', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 31000 },
  // North Bay & Wine Country
  { name: 'Santa Rosa', slug: 'santa-rosa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 178127 },
  { name: 'Petaluma', slug: 'petaluma', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 63170 },
  { name: 'Napa', slug: 'napa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 79945 },
  { name: 'Vacaville', slug: 'vacaville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 102237 },
  { name: 'Rohnert Park', slug: 'rohnert-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 43000 },
  { name: 'Novato', slug: 'novato', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 56000 },
  // Sacramento Metro
  { name: 'Elk Grove', slug: 'elk-grove', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 176124 },
  { name: 'Roseville', slug: 'roseville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 141500 },
  { name: 'Citrus Heights', slug: 'citrus-heights', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 83316 },
  { name: 'Folsom', slug: 'folsom', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 82171 },
  { name: 'Rancho Cordova', slug: 'rancho-cordova', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 74000 },
  { name: 'Woodland', slug: 'woodland', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 61170 },
  { name: 'Davis', slug: 'davis', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68111 },
  { name: 'Yuba City', slug: 'yuba-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 71234 },
  // Central Valley
  { name: 'Visalia', slug: 'visalia', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 141384 },
  { name: 'Clovis', slug: 'clovis-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 120124 },
  { name: 'Chico', slug: 'chico', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 103000 },
  { name: 'Tracy', slug: 'tracy', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 97000 },
  { name: 'Redding', slug: 'redding', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 93583 },
  { name: 'Turlock', slug: 'turlock', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 73346 },
  { name: 'Merced', slug: 'merced', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 86823 },
  { name: 'Manteca', slug: 'manteca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 85000 },
  { name: 'Madera', slug: 'madera', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 67000 },
  { name: 'Tulare', slug: 'tulare', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 66000 },
  { name: 'Lodi', slug: 'lodi', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 70000 },
  { name: 'Hanford', slug: 'hanford', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 58000 },
  { name: 'Ceres', slug: 'ceres', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 49000 },
  { name: 'Porterville', slug: 'porterville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 58000 },
  { name: 'Delano', slug: 'delano-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 52000 },
  // Greater Los Angeles
  { name: 'Santa Clarita', slug: 'santa-clarita', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 228673 },
  { name: 'Huntington Beach', slug: 'huntington-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 200191 },
  { name: 'Fontana', slug: 'fontana', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 211815 },
  { name: 'Moreno Valley', slug: 'moreno-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 213055 },
  { name: 'Garden Grove', slug: 'garden-grove', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 171949 },
  { name: 'Rancho Cucamonga', slug: 'rancho-cucamonga', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 174453 },
  { name: 'Lancaster', slug: 'lancaster-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 173516 },
  { name: 'Palmdale', slug: 'palmdale', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 169450 },
  { name: 'Ontario', slug: 'ontario-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 173212 },
  { name: 'Corona', slug: 'corona-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 169868 },
  { name: 'Salinas', slug: 'salinas', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 163542 },
  { name: 'Pomona', slug: 'pomona', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 151348 },
  { name: 'Escondido', slug: 'escondido', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 152986 },
  { name: 'Downey', slug: 'downey', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 147877 },
  { name: 'Thousand Oaks', slug: 'thousand-oaks', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 129339 },
  { name: 'Simi Valley', slug: 'simi-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 126298 },
  { name: 'Murrieta', slug: 'murrieta', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 122354 },
  { name: 'Oceanside', slug: 'oceanside', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 175742 },
  { name: 'Carlsbad', slug: 'carlsbad-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 114746 },
  { name: 'Temecula', slug: 'temecula', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 115139 },
  { name: 'Fullerton', slug: 'fullerton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 136347 },
  { name: 'Victorville', slug: 'victorville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 134810 },
  { name: 'El Monte', slug: 'el-monte', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 113475 },
  { name: 'Costa Mesa', slug: 'costa-mesa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 113825 },
  { name: 'Ventura', slug: 'ventura', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 110265 },
  { name: 'Inglewood', slug: 'inglewood', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 109673 },
  { name: 'Jurupa Valley', slug: 'jurupa-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 106549 },
  { name: 'West Covina', slug: 'west-covina', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 106098 },
  { name: 'Santa Maria', slug: 'santa-maria', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 105000 },
  { name: 'Norwalk', slug: 'norwalk-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 102321 },
  { name: 'Vista', slug: 'vista-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 101818 },
  { name: 'Rialto', slug: 'rialto', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 103526 },
  { name: 'San Marcos', slug: 'san-marcos-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 99250 },
  { name: 'Hesperia', slug: 'hesperia', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 99818 },
  { name: 'Mission Viejo', slug: 'mission-viejo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 96000 },
  { name: 'Compton', slug: 'compton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 95605 },
  { name: 'South Gate', slug: 'south-gate', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 94396 },
  { name: 'Menifee', slug: 'menifee', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 100000 },
  { name: 'Whittier', slug: 'whittier', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 87306 },
  { name: 'El Cajon', slug: 'el-cajon', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 103147 },
  { name: 'Orange', slug: 'orange-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 140332 },
  { name: 'Hawthorne', slug: 'hawthorne', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 88083 },
  { name: 'Alhambra', slug: 'alhambra', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 83890 },
  { name: 'Hemet', slug: 'hemet', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 90164 },
  { name: 'Indio', slug: 'indio', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 90180 },
  { name: 'Tustin', slug: 'tustin', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 81000 },
  { name: 'Lakewood', slug: 'lakewood-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 80048 },
  { name: 'Bellflower', slug: 'bellflower', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 76616 },
  { name: 'Apple Valley', slug: 'apple-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 74108 },
  { name: 'Chino', slug: 'chino', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 92000 },
  { name: 'Chino Hills', slug: 'chino-hills', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 83000 },
  { name: 'Westminster', slug: 'westminster-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 89701 },
  { name: 'Carson', slug: 'carson-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 93049 },
  { name: 'Upland', slug: 'upland', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 78000 },
  { name: 'Buena Park', slug: 'buena-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 83000 },
  { name: 'Lynwood', slug: 'lynwood', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 71000 },
  { name: 'Camarillo', slug: 'camarillo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68980 },
  { name: 'Poway', slug: 'poway', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 50397 },
  { name: 'Yorba Linda', slug: 'yorba-linda', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68000 },
  { name: 'Redondo Beach', slug: 'redondo-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68000 },
  { name: 'Santa Cruz', slug: 'santa-cruz', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 65459 },
  { name: 'Encinitas', slug: 'encinitas', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 63272 },
  { name: 'Eastvale', slug: 'eastvale', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 72000 },
  { name: 'Lake Elsinore', slug: 'lake-elsinore', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 66000 },
  { name: 'Arcadia', slug: 'arcadia', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 57000 },
  { name: 'Gilroy', slug: 'gilroy', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 59000 },
  { name: 'Lake Forest', slug: 'lake-forest-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 86000 },
  { name: 'National City', slug: 'national-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 61039 },
  { name: 'Laguna Niguel', slug: 'laguna-niguel', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68000 },
  { name: 'La Mesa', slug: 'la-mesa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 60167 },
  { name: 'Santee', slug: 'santee', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 57737 },
  { name: 'Baldwin Park', slug: 'baldwin-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 76000 },
  { name: 'Redlands', slug: 'redlands', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 73000 },
  { name: 'Colton', slug: 'colton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 54000 },
  { name: 'Glendora', slug: 'glendora', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 53000 },
  { name: 'Palm Desert', slug: 'palm-desert', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 53000 },
  { name: 'Cathedral City', slug: 'cathedral-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 54000 },
  { name: 'Azusa', slug: 'azusa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 51000 },
  { name: 'Aliso Viejo', slug: 'aliso-viejo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 50000 },
  { name: 'Morgan Hill', slug: 'morgan-hill', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 48000 },
  { name: 'San Luis Obispo', slug: 'san-luis-obispo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 47563 },
  { name: 'Palm Springs', slug: 'palm-springs', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 47969 },
  { name: 'San Jacinto', slug: 'san-jacinto', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 52000 },
  { name: 'Yucaipa', slug: 'yucaipa', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 54542 },
  { name: 'Covina', slug: 'covina', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 49000 },
  { name: 'Cypress', slug: 'cypress-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 49000 },
  { name: 'Cerritos', slug: 'cerritos', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 50000 },
  { name: 'Perris', slug: 'perris', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 80000 },
  { name: 'Beaumont', slug: 'beaumont-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 52000 },
  { name: 'Fountain Valley', slug: 'fountain-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 56000 },
  { name: 'Watsonville', slug: 'watsonville', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 53000 },
  { name: 'Montebello', slug: 'montebello', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 64000 },
  { name: 'Pico Rivera', slug: 'pico-rivera', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 63000 },
  { name: 'Rosemead', slug: 'rosemead', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 57000 },
  { name: 'San Gabriel', slug: 'san-gabriel', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 41000 },
  { name: 'Gardena', slug: 'gardena', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 61000 },
  { name: 'Monrovia', slug: 'monrovia', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 39000 },
  { name: 'Paramount', slug: 'paramount', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 55000 },
  { name: 'Temple City', slug: 'temple-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 36000 },
  { name: 'Montclair', slug: 'montclair-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 40000 },
  { name: 'La Habra', slug: 'la-habra', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 62000 },
  { name: 'Manhattan Beach', slug: 'manhattan-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 35000 },
  { name: 'Placentia', slug: 'placentia', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 53000 },
  { name: 'San Dimas', slug: 'san-dimas', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 33000 },
  { name: 'La Verne', slug: 'la-verne', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 32000 },
  { name: 'Claremont', slug: 'claremont', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 37000 },
  { name: 'Lompoc', slug: 'lompoc', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 43000 },
  { name: 'Paso Robles', slug: 'paso-robles', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 32000 },
  { name: 'Monterey', slug: 'monterey', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 31759 },
  { name: 'San Clemente', slug: 'san-clemente', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 65000 },
  { name: 'Laguna Hills', slug: 'laguna-hills', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 32000 },
  { name: 'Rancho Santa Margarita', slug: 'rancho-santa-margarita', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 50000 },
  { name: 'Dana Point', slug: 'dana-point', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 34000 },
  { name: 'San Juan Capistrano', slug: 'san-juan-capistrano', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 36000 },
  { name: 'Lemon Grove', slug: 'lemon-grove', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 27000 },
  { name: 'Wildomar', slug: 'wildomar', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 36000 },
  { name: 'Laguna Beach', slug: 'laguna-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 23000 },
  { name: 'Maywood', slug: 'maywood', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 27000 },
  { name: 'Bell Gardens', slug: 'bell-gardens', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 41000 },
  { name: 'West Hollywood', slug: 'west-hollywood', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 34000 },
  { name: 'Culver City', slug: 'culver-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 38000 },
  { name: 'Lawndale', slug: 'lawndale', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 33000 },
  { name: 'Agoura Hills', slug: 'agoura-hills', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 20000 },
  { name: 'Moorpark', slug: 'moorpark', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 38000 },
  { name: 'Port Hueneme', slug: 'port-hueneme', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 22000 },
  { name: 'El Centro', slug: 'el-centro', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 44000 },
  { name: 'Calabasas', slug: 'calabasas', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 24000 },
  { name: 'Ridgecrest', slug: 'ridgecrest', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 28000 },
  { name: 'Barstow', slug: 'barstow', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 23000 },
  { name: 'Coachella', slug: 'coachella', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 46000 },
  { name: 'Rancho Palos Verdes', slug: 'rancho-palos-verdes', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 41000 },
  { name: 'Diamond Bar', slug: 'diamond-bar', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 56000 },
  { name: 'Rowland Heights', slug: 'rowland-heights', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 50000 },
  { name: 'Hacienda Heights', slug: 'hacienda-heights', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 54000 },
  { name: 'Monterey Park', slug: 'monterey-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 60000 },
  { name: 'Brea', slug: 'brea', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 47000 },
  { name: 'Stanton', slug: 'stanton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 39000 },
  { name: 'Walnut', slug: 'walnut-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 30000 },
  { name: 'South Pasadena', slug: 'south-pasadena', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 26000 },
  { name: 'Seal Beach', slug: 'seal-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 25000 },
  { name: 'Bell', slug: 'bell', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 36000 },
  { name: 'Huntington Park', slug: 'huntington-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 58000 },
  { name: 'La Puente', slug: 'la-puente', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 38000 },
  { name: 'San Fernando', slug: 'san-fernando', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 24000 },
  { name: 'Twentynine Palms', slug: 'twentynine-palms', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 30000 },
  { name: 'Blythe', slug: 'blythe', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 20000 },
  { name: 'Yucca Valley', slug: 'yucca-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 22000 },
  { name: 'Cudahy', slug: 'cudahy', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 24000 },
  { name: 'Hollister', slug: 'hollister-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 43000 },
  { name: 'Scotts Valley', slug: 'scotts-valley', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 12000 },
  { name: 'Corcoran', slug: 'corcoran-ca', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 22000 },
  { name: 'Tehachapi', slug: 'tehachapi', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 14000 },
  // ── OREGON ──
  { name: 'Portland', slug: 'portland', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 652503 },
  { name: 'Eugene', slug: 'eugene', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 176654 },
  { name: 'Salem', slug: 'salem', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 175535 },
  { name: 'Gresham', slug: 'gresham', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 114116 },
  { name: 'Hillsboro', slug: 'hillsboro', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 106447 },
  { name: 'Beaverton', slug: 'beaverton', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 97590 },
  { name: 'Bend', slug: 'bend', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 94520 },
  { name: 'Medford', slug: 'medford-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 85428 },
  { name: 'Springfield', slug: 'springfield-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 62256 },
  { name: 'Corvallis', slug: 'corvallis', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 59922 },
  { name: 'Albany', slug: 'albany-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 55818 },
  { name: 'Tigard', slug: 'tigard', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 55767 },
  { name: 'Keizer', slug: 'keizer', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 40076 },
  { name: 'Lake Oswego', slug: 'lake-oswego', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 41654 },
  { name: 'Oregon City', slug: 'oregon-city', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 36614 },
  { name: 'McMinnville', slug: 'mcminnville-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 35097 },
  { name: 'Grants Pass', slug: 'grants-pass', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 39098 },
  { name: 'Redmond', slug: 'redmond-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 31414 },
  { name: 'Wilsonville', slug: 'wilsonville', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 26193 },
  { name: 'Newberg', slug: 'newberg', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 24989 },
  { name: 'Tualatin', slug: 'tualatin', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 30002 },
  { name: 'West Linn', slug: 'west-linn', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 26499 },
  { name: 'Ashland', slug: 'ashland-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 21281 },
  { name: 'Klamath Falls', slug: 'klamath-falls', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 22138 },
  { name: 'Milwaukie', slug: 'milwaukie', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 21265 },
  { name: 'Roseburg', slug: 'roseburg', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 24000 },
  { name: 'Hermiston', slug: 'hermiston', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 18935 },
  { name: 'Pendleton', slug: 'pendleton-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 16612 },
  { name: 'The Dalles', slug: 'the-dalles', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 15800 },
  { name: 'Coos Bay', slug: 'coos-bay', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 16390 },
  { name: 'Newport', slug: 'newport-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 10334 },
  { name: 'Astoria', slug: 'astoria-or', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 9729 },
  { name: 'Hood River', slug: 'hood-river', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 8100 },
  // ── WASHINGTON ──
  { name: 'Seattle', slug: 'seattle', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 737255 },
  { name: 'Spokane', slug: 'spokane', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 222081 },
  { name: 'Tacoma', slug: 'tacoma', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 219346 },
  { name: 'Vancouver', slug: 'vancouver-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 190915 },
  { name: 'Bellevue', slug: 'bellevue-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 148164 },
  { name: 'Kent', slug: 'kent', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 134400 },
  { name: 'Everett', slug: 'everett', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 113019 },
  { name: 'Renton', slug: 'renton', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 106785 },
  { name: 'Federal Way', slug: 'federal-way', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 97142 },
  { name: 'Kirkland', slug: 'kirkland', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 90928 },
  { name: 'Yakima', slug: 'yakima', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 96968 },
  { name: 'Bellingham', slug: 'bellingham', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 92314 },
  { name: 'Kennewick', slug: 'kennewick', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 84347 },
  { name: 'Auburn', slug: 'auburn-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 84816 },
  { name: 'Pasco', slug: 'pasco', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 77800 },
  { name: 'Marysville', slug: 'marysville', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 67088 },
  { name: 'Redmond', slug: 'redmond', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 67180 },
  { name: 'Sammamish', slug: 'sammamish', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 71491 },
  { name: 'Richland', slug: 'richland', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 61440 },
  { name: 'Lacey', slug: 'lacey-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 65673 },
  { name: 'Shoreline', slug: 'shoreline', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 55730 },
  { name: 'Olympia', slug: 'olympia-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 55605 },
  { name: 'Lakewood', slug: 'lakewood-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 69799 },
  { name: 'Bothell', slug: 'bothell', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 50733 },
  { name: 'Issaquah', slug: 'issaquah', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 41720 },
  { name: 'Edmonds', slug: 'edmonds', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 42470 },
  { name: 'Lynnwood', slug: 'lynnwood', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 41740 },
  { name: 'Burien', slug: 'burien', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 52066 },
  { name: 'Bremerton', slug: 'bremerton', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 44522 },
  { name: 'Longview', slug: 'longview-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 40540 },
  { name: 'Walla Walla', slug: 'walla-walla', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 33530 },
  { name: 'Mount Vernon', slug: 'mount-vernon-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 38000 },
  { name: 'Wenatchee', slug: 'wenatchee', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 33668 },
  { name: 'Maple Valley', slug: 'maple-valley', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 28798 },
  { name: 'Pullman', slug: 'pullman-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 34100 },
  { name: 'Kenmore', slug: 'kenmore-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 23500 },
  { name: 'Oak Harbor', slug: 'oak-harbor', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 24000 },
  { name: 'Spokane Valley', slug: 'spokane-valley', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 102976 },
  { name: 'University Place', slug: 'university-place', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 33000 },
  { name: 'Mukilteo', slug: 'mukilteo', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 22000 },
  { name: 'Des Moines', slug: 'des-moines-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 32000 },
  // ── NEVADA ──
  { name: 'Las Vegas', slug: 'las-vegas', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 641903 },
  { name: 'Henderson', slug: 'henderson', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 320189 },
  { name: 'North Las Vegas', slug: 'north-las-vegas', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 262527 },
  { name: 'Reno', slug: 'reno', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 255601 },
  { name: 'Paradise', slug: 'paradise-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 223167 },
  { name: 'Spring Valley', slug: 'spring-valley-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 178395 },
  { name: 'Sunrise Manor', slug: 'sunrise-manor', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 189372 },
  { name: 'Enterprise', slug: 'enterprise-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 108481 },
  { name: 'Sparks', slug: 'sparks', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 105006 },
  { name: 'Carson City', slug: 'carson-city', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 59010 },
  { name: 'Whitney', slug: 'whitney-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 42000 },
  { name: 'Pahrump', slug: 'pahrump', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 38000 },
  { name: 'Winchester', slug: 'winchester-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 27980 },
  { name: 'Mesquite', slug: 'mesquite-nv', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 22264 },
  { name: 'Fernley', slug: 'fernley', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 24432 },
  { name: 'Elko', slug: 'elko', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 20078 },
  { name: 'Boulder City', slug: 'boulder-city', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 15665 },
  { name: 'Laughlin', slug: 'laughlin', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 11000 },
  { name: 'Winnemucca', slug: 'winnemucca', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 7974 },
  { name: 'Fallon', slug: 'fallon', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 9636 },
  // ── ARIZONA ──
  { name: 'Phoenix', slug: 'phoenix', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 1608139 },
  { name: 'Tucson', slug: 'tucson', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 542629 },
  { name: 'Mesa', slug: 'mesa', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 504258 },
  { name: 'Chandler', slug: 'chandler', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 261165 },
  { name: 'Scottsdale', slug: 'scottsdale', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 258069 },
  { name: 'Gilbert', slug: 'gilbert', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 254114 },
  { name: 'Glendale', slug: 'glendale-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 252381 },
  { name: 'Tempe', slug: 'tempe', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 195805 },
  { name: 'Peoria', slug: 'peoria-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 175961 },
  { name: 'Surprise', slug: 'surprise', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 143148 },
  { name: 'San Tan Valley', slug: 'san-tan-valley', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 100000 },
  { name: 'Queen Creek', slug: 'queen-creek', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 68234 },
  { name: 'Buckeye', slug: 'buckeye', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 91502 },
  { name: 'Avondale', slug: 'avondale', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 89374 },
  { name: 'Goodyear', slug: 'goodyear', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 93665 },
  { name: 'Yuma', slug: 'yuma', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 99160 },
  { name: 'Flagstaff', slug: 'flagstaff', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 76831 },
  { name: 'Prescott Valley', slug: 'prescott-valley', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 47402 },
  { name: 'Maricopa', slug: 'maricopa', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 58063 },
  { name: 'Casa Grande', slug: 'casa-grande', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 58814 },
  { name: 'Lake Havasu City', slug: 'lake-havasu-city', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 61591 },
  { name: 'Marana', slug: 'marana', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 47038 },
  { name: 'Prescott', slug: 'prescott', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 45827 },
  { name: 'Oro Valley', slug: 'oro-valley', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 46234 },
  { name: 'Apache Junction', slug: 'apache-junction', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 42811 },
  { name: 'El Mirage', slug: 'el-mirage', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 35234 },
  { name: 'Sierra Vista', slug: 'sierra-vista', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 45865 },
  { name: 'Sahuarita', slug: 'sahuarita', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 31674 },
  { name: 'Fountain Hills', slug: 'fountain-hills', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 24657 },
  { name: 'Kingman', slug: 'kingman', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 32499 },
  { name: 'Bullhead City', slug: 'bullhead-city', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 40252 },
  { name: 'Cottonwood', slug: 'cottonwood-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 12234 },
  { name: 'Sedona', slug: 'sedona', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 10336 },
  { name: 'Show Low', slug: 'show-low', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 10942 },
  { name: 'Nogales', slug: 'nogales-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 20409 },
  { name: 'Douglas', slug: 'douglas-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 17087 },
  // ── UTAH ──
  { name: 'Salt Lake City', slug: 'salt-lake-city', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 200133 },
  { name: 'West Valley City', slug: 'west-valley-city', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 140230 },
  { name: 'Provo', slug: 'provo', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 115264 },
  { name: 'West Jordan', slug: 'west-jordan', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 116961 },
  { name: 'Sandy', slug: 'sandy-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 96382 },
  { name: 'Orem', slug: 'orem', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 98129 },
  { name: 'Ogden', slug: 'ogden', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 87321 },
  { name: 'St. George', slug: 'st-george', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 95342 },
  { name: 'Layton', slug: 'layton', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 82836 },
  { name: 'South Jordan', slug: 'south-jordan', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 77487 },
  { name: 'Lehi', slug: 'lehi', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 75907 },
  { name: 'Herriman', slug: 'herriman', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 53984 },
  { name: 'Millcreek', slug: 'millcreek', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 62759 },
  { name: 'Taylorsville', slug: 'taylorsville', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 60678 },
  { name: 'Logan', slug: 'logan-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 52778 },
  { name: 'Murray', slug: 'murray-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 49965 },
  { name: 'Draper', slug: 'draper', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 49377 },
  { name: 'Bountiful', slug: 'bountiful', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 44131 },
  { name: 'Riverton', slug: 'riverton-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 43568 },
  { name: 'Spanish Fork', slug: 'spanish-fork', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 40223 },
  { name: 'Roy', slug: 'roy-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 40427 },
  { name: 'Pleasant Grove', slug: 'pleasant-grove', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 39676 },
  { name: 'Kaysville', slug: 'kaysville', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 33000 },
  { name: 'Springville', slug: 'springville', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 34903 },
  { name: 'Cedar City', slug: 'cedar-city', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 35438 },
  { name: 'Cottonwood Heights', slug: 'cottonwood-heights', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 34228 },
  { name: 'American Fork', slug: 'american-fork', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 33105 },
  { name: 'Saratoga Springs', slug: 'saratoga-springs-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 31000 },
  { name: 'Clearfield', slug: 'clearfield-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 32000 },
  { name: 'Syracuse', slug: 'syracuse-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 28000 },
  // ── COLORADO ──
  { name: 'Denver', slug: 'denver', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 715522 },
  { name: 'Colorado Springs', slug: 'colorado-springs', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 478221 },
  { name: 'Aurora', slug: 'aurora-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 366623 },
  { name: 'Fort Collins', slug: 'fort-collins', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 164685 },
  { name: 'Lakewood', slug: 'lakewood', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 157984 },
  { name: 'Thornton', slug: 'thornton', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 139670 },
  { name: 'Arvada', slug: 'arvada', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 118428 },
  { name: 'Westminster', slug: 'westminster-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 113479 },
  { name: 'Pueblo', slug: 'pueblo', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 111876 },
  { name: 'Centennial', slug: 'centennial', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 108418 },
  { name: 'Boulder', slug: 'boulder', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 105112 },
  { name: 'Highlands Ranch', slug: 'highlands-ranch', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 103155 },
  { name: 'Greeley', slug: 'greeley', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 103990 },
  { name: 'Longmont', slug: 'longmont', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 94772 },
  { name: 'Loveland', slug: 'loveland', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 79959 },
  { name: 'Broomfield', slug: 'broomfield', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 73167 },
  { name: 'Castle Rock', slug: 'castle-rock', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 75000 },
  { name: 'Commerce City', slug: 'commerce-city', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 62000 },
  { name: 'Parker', slug: 'parker-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 58512 },
  { name: 'Security-Widefield', slug: 'security-widefield', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 40000 },
  { name: 'Northglenn', slug: 'northglenn', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 43000 },
  { name: 'Brighton', slug: 'brighton-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 39000 },
  { name: 'Fountain', slug: 'fountain-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 29000 },
  { name: 'Littleton', slug: 'littleton-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 46000 },
  { name: 'Englewood', slug: 'englewood-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 34000 },
  { name: 'Wheat Ridge', slug: 'wheat-ridge', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 32000 },
  { name: 'Lafayette', slug: 'lafayette-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 28000 },
  { name: 'Golden', slug: 'golden-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 21000 },
  { name: 'Erie', slug: 'erie-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 30000 },
  { name: 'Windsor', slug: 'windsor-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 27000 },
  { name: 'Evans', slug: 'evans-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 21000 },
  { name: 'Sterling', slug: 'sterling-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 14000 },
  { name: 'Frederick', slug: 'frederick-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 13000 },
  { name: 'Firestone', slug: 'firestone', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 17000 },
  { name: 'Superior', slug: 'superior-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 14000 },
  { name: 'Castle Pines', slug: 'castle-pines', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 11000 },
  // ── IDAHO ──
  { name: 'Boise', slug: 'boise', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 235684 },
  { name: 'Meridian', slug: 'meridian', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 120719 },
  { name: 'Nampa', slug: 'nampa', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 100200 },
  { name: 'Idaho Falls', slug: 'idaho-falls', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 64818 },
  { name: 'Caldwell', slug: 'caldwell-id', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 61001 },
  { name: 'Pocatello', slug: 'pocatello', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 56536 },
  { name: 'Coeur d\'Alene', slug: 'coeur-dalene', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 52081 },
  { name: 'Twin Falls', slug: 'twin-falls', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 50531 },
  { name: 'Post Falls', slug: 'post-falls', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 38000 },
  { name: 'Lewiston', slug: 'lewiston-id', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 34000 },
  { name: 'Rexburg', slug: 'rexburg', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 30000 },
  { name: 'Eagle', slug: 'eagle-id', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 29000 },
  { name: 'Kuna', slug: 'kuna', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 25000 },
  { name: 'Moscow', slug: 'moscow-id', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 25000 },
  { name: 'Garden City', slug: 'garden-city-id', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 12000 },
  { name: 'Chubbuck', slug: 'chubbuck', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 16000 },
  { name: 'Hailey', slug: 'hailey', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 9000 },
  { name: 'Sandpoint', slug: 'sandpoint', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 9000 },
  // ── MONTANA ──
  { name: 'Billings', slug: 'billings', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 119616 },
  { name: 'Missoula', slug: 'missoula', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 74598 },
  { name: 'Great Falls', slug: 'great-falls', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 60442 },
  { name: 'Bozeman', slug: 'bozeman', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 53293 },
  { name: 'Butte', slug: 'butte-mt', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 34494 },
  { name: 'Helena', slug: 'helena-mt', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 33124 },
  { name: 'Kalispell', slug: 'kalispell', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 25023 },
  { name: 'Havre', slug: 'havre-mt', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 9953 },
  { name: 'Anaconda', slug: 'anaconda-mt', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 9298 },
  { name: 'Livingston', slug: 'livingston-mt', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 8047 },
  { name: 'Whitefish', slug: 'whitefish', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 9246 },
  { name: 'Miles City', slug: 'miles-city', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 8700 },
  // ── WYOMING ──
  { name: 'Cheyenne', slug: 'cheyenne', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 65132 },
  { name: 'Casper', slug: 'casper', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 60285 },
  { name: 'Laramie', slug: 'laramie', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 32609 },
  { name: 'Gillette', slug: 'gillette', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 31000 },
  { name: 'Rock Springs', slug: 'rock-springs', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 24000 },
  { name: 'Sheridan', slug: 'sheridan-wy', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 19429 },
  { name: 'Green River', slug: 'green-river-wy', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 12538 },
  { name: 'Evanston', slug: 'evanston-wy', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 12359 },
  { name: 'Riverton', slug: 'riverton-wy', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 11255 },
  { name: 'Jackson', slug: 'jackson-wy', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 10532 },
  // ── ALASKA ──
  { name: 'Anchorage', slug: 'anchorage', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 291538 },
  { name: 'Juneau', slug: 'juneau', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 32113 },
  { name: 'Fairbanks', slug: 'fairbanks', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 31335 },
  { name: 'Wasilla', slug: 'wasilla', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 10282 },
  { name: 'Sitka', slug: 'sitka', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 8493 },
  { name: 'Ketchikan', slug: 'ketchikan', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 8273 },
  { name: 'Kenai', slug: 'kenai', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 7419 },
  { name: 'Kodiak', slug: 'kodiak', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 5720 },
  { name: 'Bethel', slug: 'bethel-ak', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 6325 },
  { name: 'Palmer', slug: 'palmer-ak', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 7400 },
  // ── HAWAII ──
  { name: 'Honolulu', slug: 'honolulu', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 350964 },
  { name: 'Pearl City', slug: 'pearl-city', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 47698 },
  { name: 'Hilo', slug: 'hilo', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 44186 },
  { name: 'Kailua', slug: 'kailua-hi', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 50218 },
  { name: 'Waipahu', slug: 'waipahu', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 38216 },
  { name: 'Kaneohe', slug: 'kaneohe', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 34970 },
  { name: 'Mililani', slug: 'mililani', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 28611 },
  { name: 'Kahului', slug: 'kahului', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 29124 },
  { name: 'Kihei', slug: 'kihei', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 22300 },
  { name: 'Mililani Mauka', slug: 'mililani-mauka', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 20898 },
  { name: 'Ewa Beach', slug: 'ewa-beach', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 14650 },
  { name: 'Kailua-Kona', slug: 'kailua-kona', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 14000 },
  { name: 'Kapolei', slug: 'kapolei', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 20000 },
  { name: 'Wailuku', slug: 'wailuku', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 16088 },
  { name: 'Makakilo', slug: 'makakilo', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 16000 },
  // ── NEW MEXICO ──
  { name: 'Albuquerque', slug: 'albuquerque', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 564559 },
  { name: 'Las Cruces', slug: 'las-cruces', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 111385 },
  { name: 'Rio Rancho', slug: 'rio-rancho', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 104046 },
  { name: 'Santa Fe', slug: 'santa-fe', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 84683 },
  { name: 'Roswell', slug: 'roswell-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 46766 },
  { name: 'Farmington', slug: 'farmington-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 45426 },
  { name: 'Clovis', slug: 'clovis-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 39689 },
  { name: 'Hobbs', slug: 'hobbs', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 37000 },
  { name: 'Alamogordo', slug: 'alamogordo', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 31000 },
  { name: 'Carlsbad', slug: 'carlsbad-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 29613 },
  { name: 'Gallup', slug: 'gallup', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 22119 },
  { name: 'Taos', slug: 'taos', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 5763 },
  { name: 'Artesia', slug: 'artesia-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 12257 },
  { name: 'Portales', slug: 'portales', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 12000 },
  { name: 'Los Lunas', slug: 'los-lunas', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 16700 },
  { name: 'Deming', slug: 'deming', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 14855 },
  { name: 'Silver City', slug: 'silver-city', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 10315 },
  { name: 'Aztec', slug: 'aztec-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 6763 },
  { name: 'Ruidoso', slug: 'ruidoso', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 8349 },
  { name: 'Espanola', slug: 'espanola', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 10224 },
  { name: 'Grants', slug: 'grants-nm', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 9109 },
  { name: 'Tucumcari', slug: 'tucumcari', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 4718 },
  { name: 'Globe', slug: 'globe-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 7532 },
  { name: 'Payson', slug: 'payson-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 16002 },
  { name: 'Eloy', slug: 'eloy', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 16928 },
  { name: 'Winslow', slug: 'winslow-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 9520 },
]
