export type { City } from './city-types'
import type { City } from './city-types'

export const CITIES: City[] = [
  // ── NEW YORK ──
  { name: 'New York City', slug: 'new-york-city', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 8336817 },
  { name: 'Buffalo', slug: 'buffalo', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 278349 },
  { name: 'Rochester', slug: 'rochester', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 211328 },
  { name: 'Yonkers', slug: 'yonkers', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 211569 },
  { name: 'Syracuse', slug: 'syracuse', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 148458 },
  { name: 'Albany', slug: 'albany', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 100884 },
  { name: 'White Plains', slug: 'white-plains', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 58109 },
  { name: 'Utica', slug: 'utica', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 59750 },
  { name: 'Garden City', slug: 'garden-city', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 22371 },
  { name: 'Melville', slug: 'melville', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 18985 },
  { name: 'Hauppauge', slug: 'hauppauge', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 20882 },
  { name: 'New Rochelle', slug: 'new-rochelle', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 79726 },
  { name: 'Binghamton', slug: 'binghamton', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 47376 },
  { name: 'Schenectady', slug: 'schenectady', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 65273 },
  { name: 'Mount Vernon', slug: 'mount-vernon', state: 'New York', stateSlug: 'new-york', stateAbbr: 'NY', population: 73893 },
  // ── CALIFORNIA ──
  { name: 'Los Angeles', slug: 'los-angeles', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 3979576 },
  { name: 'San Francisco', slug: 'san-francisco', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 881549 },
  { name: 'San Jose', slug: 'san-jose', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 1013240 },
  { name: 'San Diego', slug: 'san-diego', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 1423851 },
  { name: 'Sacramento', slug: 'sacramento', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 524943 },
  { name: 'Oakland', slug: 'oakland', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 440646 },
  { name: 'Palo Alto', slug: 'palo-alto', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 68572 },
  { name: 'Santa Monica', slug: 'santa-monica', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 91411 },
  { name: 'Irvine', slug: 'irvine', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 307670 },
  { name: 'Fresno', slug: 'fresno', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 542107 },
  { name: 'Long Beach', slug: 'long-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 466742 },
  { name: 'Bakersfield', slug: 'bakersfield', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 403455 },
  { name: 'Anaheim', slug: 'anaheim', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 346824 },
  { name: 'Santa Ana', slug: 'santa-ana', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 310227 },
  { name: 'Riverside', slug: 'riverside', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 331360 },
  { name: 'Stockton', slug: 'stockton', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 320804 },
  { name: 'Chula Vista', slug: 'chula-vista', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 274492 },
  { name: 'Fremont', slug: 'fremont', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 230504 },
  { name: 'San Bernardino', slug: 'san-bernardino', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 222101 },
  { name: 'Modesto', slug: 'modesto', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 218464 },
  { name: 'Santa Barbara', slug: 'santa-barbara', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 88255 },
  { name: 'Pasadena', slug: 'pasadena', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 141029 },
  { name: 'Mountain View', slug: 'mountain-view', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 82376 },
  { name: 'Sunnyvale', slug: 'sunnyvale', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 153185 },
  { name: 'Santa Clara', slug: 'santa-clara', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 127647 },
  { name: 'Menlo Park', slug: 'menlo-park', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 35254 },
  { name: 'Beverly Hills', slug: 'beverly-hills', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 34109 },
  { name: 'Burbank', slug: 'burbank', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 103340 },
  { name: 'Torrance', slug: 'torrance', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 147067 },
  { name: 'Glendale', slug: 'glendale', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 196543 },
  { name: 'San Mateo', slug: 'san-mateo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 105661 },
  { name: 'Redwood City', slug: 'redwood-city', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 84888 },
  { name: 'Cupertino', slug: 'cupertino', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 60170 },
  { name: 'El Segundo', slug: 'el-segundo', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 16946 },
  { name: 'Newport Beach', slug: 'newport-beach', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 85239 },
  { name: 'San Ramon', slug: 'san-ramon', state: 'California', stateSlug: 'california', stateAbbr: 'CA', population: 84605 },
  // ── TEXAS ──
  { name: 'Houston', slug: 'houston', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 2304580 },
  { name: 'Dallas', slug: 'dallas', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 1304379 },
  { name: 'Austin', slug: 'austin', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 961855 },
  { name: 'San Antonio', slug: 'san-antonio', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 1434625 },
  { name: 'Fort Worth', slug: 'fort-worth', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 895008 },
  { name: 'Plano', slug: 'plano', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 285494 },
  { name: 'Irving', slug: 'irving', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 239798 },
  { name: 'Frisco', slug: 'frisco', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 200509 },
  { name: 'McKinney', slug: 'mckinney', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 199177 },
  { name: 'Arlington', slug: 'arlington', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 394266 },
  { name: 'Round Rock', slug: 'round-rock', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 128066 },
  { name: 'The Woodlands', slug: 'the-woodlands', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 114436 },
  { name: 'Lubbock', slug: 'lubbock', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 257141 },
  { name: 'El Paso', slug: 'el-paso', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 678815 },
  { name: 'Corpus Christi', slug: 'corpus-christi', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 317863 },
  { name: 'Laredo', slug: 'laredo', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 262491 },
  { name: 'Garland', slug: 'garland', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 246018 },
  { name: 'Amarillo', slug: 'amarillo', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 201730 },
  { name: 'Grand Prairie', slug: 'grand-prairie', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 196100 },
  { name: 'Brownsville', slug: 'brownsville', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 182781 },
  { name: 'Killeen', slug: 'killeen', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 153095 },
  { name: 'Midland', slug: 'midland', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 132524 },
  { name: 'Waco', slug: 'waco', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 138486 },
  { name: 'Denton', slug: 'denton', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 139869 },
  { name: 'Allen', slug: 'allen', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 103027 },
  { name: 'Sugar Land', slug: 'sugar-land', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 118000 },
  { name: 'Tyler', slug: 'tyler', state: 'Texas', stateSlug: 'texas', stateAbbr: 'TX', population: 105995 },
  // ── FLORIDA ──
  { name: 'Miami', slug: 'miami', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 442241 },
  { name: 'Tampa', slug: 'tampa', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 399700 },
  { name: 'Orlando', slug: 'orlando', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 307573 },
  { name: 'Jacksonville', slug: 'jacksonville', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 949611 },
  { name: 'Fort Lauderdale', slug: 'fort-lauderdale', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 182760 },
  { name: 'Boca Raton', slug: 'boca-raton', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 99805 },
  { name: 'Naples', slug: 'naples', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 22635 },
  { name: 'West Palm Beach', slug: 'west-palm-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 111955 },
  { name: 'Sarasota', slug: 'sarasota', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 57738 },
  { name: 'St. Petersburg', slug: 'st-petersburg', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 265351 },
  { name: 'Clearwater', slug: 'clearwater', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 117292 },
  { name: 'Pembroke Pines', slug: 'pembroke-pines', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 173591 },
  { name: 'Hollywood', slug: 'hollywood', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 153067 },
  { name: 'Gainesville', slug: 'gainesville', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 133997 },
  { name: 'Cape Coral', slug: 'cape-coral', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 194016 },
  { name: 'Miramar', slug: 'miramar', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 134721 },
  { name: 'Coral Springs', slug: 'coral-springs', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 128711 },
  { name: 'Palm Bay', slug: 'palm-bay', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 120779 },
  { name: 'Tallahassee', slug: 'tallahassee', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 196169 },
  { name: 'Lakeland', slug: 'lakeland', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 112641 },
  { name: 'Fort Myers', slug: 'fort-myers', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 87103 },
  { name: 'Daytona Beach', slug: 'daytona-beach', state: 'Florida', stateSlug: 'florida', stateAbbr: 'FL', population: 69300 },
  // ── ILLINOIS ──
  { name: 'Chicago', slug: 'chicago', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 2693976 },
  { name: 'Naperville', slug: 'naperville', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 148272 },
  { name: 'Schaumburg', slug: 'schaumburg', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 75936 },
  { name: 'Evanston', slug: 'evanston', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 74486 },
  { name: 'Oak Brook', slug: 'oak-brook', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 7882 },
  { name: 'Peoria', slug: 'peoria', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 113150 },
  { name: 'Rockford', slug: 'rockford', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 148655 },
  { name: 'Springfield', slug: 'springfield', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 114394 },
  { name: 'Aurora', slug: 'aurora', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 180542 },
  { name: 'Joliet', slug: 'joliet', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 150362 },
  { name: 'Elgin', slug: 'elgin', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 114797 },
  { name: 'Waukegan', slug: 'waukegan', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 89078 },
  { name: 'Cicero', slug: 'cicero', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 84103 },
  // ── PENNSYLVANIA ──
  { name: 'Philadelphia', slug: 'philadelphia', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 1603797 },
  { name: 'Pittsburgh', slug: 'pittsburgh', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 302971 },
  { name: 'Allentown', slug: 'allentown', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 125845 },
  { name: 'Harrisburg', slug: 'harrisburg', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 50249 },
  { name: 'Lancaster', slug: 'lancaster', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 59322 },
  { name: 'King of Prussia', slug: 'king-of-prussia', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 26108 },
  { name: 'Wayne', slug: 'wayne', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 55607 },
  { name: 'Malvern', slug: 'malvern', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 3943 },
  { name: 'Reading', slug: 'reading', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 95112 },
  { name: 'Scranton', slug: 'scranton', state: 'Pennsylvania', stateSlug: 'pennsylvania', stateAbbr: 'PA', population: 76997 },
  // ── OHIO ──
  { name: 'Columbus', slug: 'columbus', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 905748 },
  { name: 'Cleveland', slug: 'cleveland', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 372624 },
  { name: 'Cincinnati', slug: 'cincinnati', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 309317 },
  { name: 'Toledo', slug: 'toledo', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 272779 },
  { name: 'Akron', slug: 'akron', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 190469 },
  { name: 'Dayton', slug: 'dayton', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 137644 },
  { name: 'Westlake', slug: 'westlake', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 33109 },
  { name: 'Dublin', slug: 'dublin', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 49328 },
  { name: 'Parma', slug: 'parma', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 78103 },
  { name: 'Canton', slug: 'canton', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 70872 },
  { name: 'Youngstown', slug: 'youngstown', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 60068 },
  { name: 'Lorain', slug: 'lorain', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 63700 },
  // ── GEORGIA ──
  { name: 'Atlanta', slug: 'atlanta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 498715 },
  { name: 'Savannah', slug: 'savannah', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 145403 },
  { name: 'Augusta', slug: 'augusta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 202081 },
  { name: 'Columbus', slug: 'columbus-ga', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 202824 },
  { name: 'Alpharetta', slug: 'alpharetta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 67213 },
  { name: 'Sandy Springs', slug: 'sandy-springs', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 108080 },
  { name: 'Macon', slug: 'macon', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 157346 },
  { name: 'Marietta', slug: 'marietta', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 60972 },
  { name: 'Roswell', slug: 'roswell', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 94763 },
  { name: 'Dunwoody', slug: 'dunwoody', state: 'Georgia', stateSlug: 'georgia', stateAbbr: 'GA', population: 49948 },
  // ── NORTH CAROLINA ──
  { name: 'Charlotte', slug: 'charlotte', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 874579 },
  { name: 'Raleigh', slug: 'raleigh', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 467665 },
  { name: 'Durham', slug: 'durham', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 278993 },
  { name: 'Greensboro', slug: 'greensboro', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 299035 },
  { name: 'Winston-Salem', slug: 'winston-salem', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 249545 },
  { name: 'Cary', slug: 'cary', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 174721 },
  { name: 'Chapel Hill', slug: 'chapel-hill', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 61960 },
  { name: 'Fayetteville', slug: 'fayetteville', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 211657 },
  { name: 'Asheville', slug: 'asheville', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 92452 },
  { name: 'Wilmington', slug: 'wilmington', state: 'North Carolina', stateSlug: 'north-carolina', stateAbbr: 'NC', population: 123784 },
  // ── MICHIGAN ──
  { name: 'Detroit', slug: 'detroit', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 639111 },
  { name: 'Grand Rapids', slug: 'grand-rapids', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 198917 },
  { name: 'Ann Arbor', slug: 'ann-arbor', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 123851 },
  { name: 'Lansing', slug: 'lansing', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 112644 },
  { name: 'Troy', slug: 'troy', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 87294 },
  { name: 'Sterling Heights', slug: 'sterling-heights', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 134346 },
  { name: 'Dearborn', slug: 'dearborn', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 109976 },
  { name: 'Warren', slug: 'warren', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 136640 },
  { name: 'Southfield', slug: 'southfield', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 73006 },
  { name: 'Kalamazoo', slug: 'kalamazoo', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 72139 },
  // ── VIRGINIA ──
  { name: 'Richmond', slug: 'richmond', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 226610 },
  { name: 'Virginia Beach', slug: 'virginia-beach', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 459470 },
  { name: 'Arlington', slug: 'arlington', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 238643 },
  { name: 'McLean', slug: 'mclean', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 48115 },
  { name: 'Tysons', slug: 'tysons', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 23956 },
  { name: 'Reston', slug: 'reston', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 61837 },
  { name: 'Norfolk', slug: 'norfolk', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 238005 },
  { name: 'Alexandria', slug: 'alexandria', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 159467 },
  { name: 'Fairfax', slug: 'fairfax', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 24019 },
  { name: 'Chantilly', slug: 'chantilly', state: 'Virginia', stateSlug: 'virginia', stateAbbr: 'VA', population: 23039 },
  // ── WASHINGTON ──
  { name: 'Seattle', slug: 'seattle', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 737255 },
  { name: 'Bellevue', slug: 'bellevue', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 148164 },
  { name: 'Redmond', slug: 'redmond', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 67180 },
  { name: 'Kirkland', slug: 'kirkland', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 90928 },
  { name: 'Spokane', slug: 'spokane', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 222081 },
  { name: 'Tacoma', slug: 'tacoma', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 219346 },
  { name: 'Renton', slug: 'renton', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 106785 },
  { name: 'Bothell', slug: 'bothell', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 53050 },
  { name: 'Bellevue', slug: 'bellevue-wa', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 148164 },
  { name: 'Kent', slug: 'kent', state: 'Washington', stateSlug: 'washington', stateAbbr: 'WA', population: 134400 },
  // ── MASSACHUSETTS ──
  { name: 'Boston', slug: 'boston', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 685094 },
  { name: 'Cambridge', slug: 'cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 118977 },
  { name: 'Worcester', slug: 'worcester', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 206518 },
  { name: 'Springfield', slug: 'springfield-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 155929 },
  { name: 'Waltham', slug: 'waltham', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 62423 },
  { name: 'Burlington', slug: 'burlington-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 28530 },
  { name: 'Framingham', slug: 'framingham', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 72032 },
  { name: 'Lowell', slug: 'lowell', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 115554 },
  { name: 'Quincy', slug: 'quincy', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 101636 },
  { name: 'Newton', slug: 'newton', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 88923 },
  { name: 'Somerville', slug: 'somerville', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 81360 },
  { name: 'Lexington', slug: 'lexington-ma', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 33111 },
  { name: 'Needham', slug: 'needham', state: 'Massachusetts', stateSlug: 'massachusetts', stateAbbr: 'MA', population: 32322 },
  // ── COLORADO ──
  { name: 'Denver', slug: 'denver', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 715522 },
  { name: 'Boulder', slug: 'boulder', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 105112 },
  { name: 'Colorado Springs', slug: 'colorado-springs', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 478221 },
  { name: 'Aurora', slug: 'aurora-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 366623 },
  { name: 'Fort Collins', slug: 'fort-collins', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 164685 },
  { name: 'Loveland', slug: 'loveland', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 79959 },
  { name: 'Arvada', slug: 'arvada', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 118428 },
  { name: 'Westminster', slug: 'westminster-co', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 113479 },
  { name: 'Lakewood', slug: 'lakewood', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 157984 },
  { name: 'Broomfield', slug: 'broomfield', state: 'Colorado', stateSlug: 'colorado', stateAbbr: 'CO', population: 73167 },
  // ── ARIZONA ──
  { name: 'Phoenix', slug: 'phoenix', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 1608139 },
  { name: 'Scottsdale', slug: 'scottsdale', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 258069 },
  { name: 'Tempe', slug: 'tempe', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 195805 },
  { name: 'Mesa', slug: 'mesa', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 504258 },
  { name: 'Chandler', slug: 'chandler', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 261165 },
  { name: 'Tucson', slug: 'tucson', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 542629 },
  { name: 'Gilbert', slug: 'gilbert', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 254114 },
  { name: 'Glendale', slug: 'glendale-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 248325 },
  { name: 'Peoria', slug: 'peoria-az', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 175961 },
  { name: 'Surprise', slug: 'surprise', state: 'Arizona', stateSlug: 'arizona', stateAbbr: 'AZ', population: 143148 },
  // ── MINNESOTA ──
  { name: 'Minneapolis', slug: 'minneapolis', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 429606 },
  { name: 'Saint Paul', slug: 'saint-paul', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 311527 },
  { name: 'Bloomington', slug: 'bloomington', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 89987 },
  { name: 'Rochester', slug: 'rochester-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 121395 },
  { name: 'Eden Prairie', slug: 'eden-prairie', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 64198 },
  { name: 'Plymouth', slug: 'plymouth', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 79671 },
  { name: 'Duluth', slug: 'duluth', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 90872 },
  { name: 'Woodbury', slug: 'woodbury', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 75102 },
  { name: 'Maple Grove', slug: 'maple-grove', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 71608 },
  { name: 'Eagan', slug: 'eagan', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 68855 },
  // ── NEW JERSEY ──
  { name: 'Newark', slug: 'newark', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 311549 },
  { name: 'Jersey City', slug: 'jersey-city', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 292449 },
  { name: 'Hoboken', slug: 'hoboken', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 60419 },
  { name: 'Trenton', slug: 'trenton', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 90871 },
  { name: 'Princeton', slug: 'princeton', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 31822 },
  { name: 'Parsippany', slug: 'parsippany', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 53238 },
  { name: 'Edison', slug: 'edison', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 107694 },
  { name: 'Short Hills', slug: 'short-hills', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 13400 },
  { name: 'Morristown', slug: 'morristown', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 20204 },
  { name: 'Iselin', slug: 'iselin', state: 'New Jersey', stateSlug: 'new-jersey', stateAbbr: 'NJ', population: 17884 },
  // ── MARYLAND ──
  { name: 'Baltimore', slug: 'baltimore', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 585708 },
  { name: 'Rockville', slug: 'rockville', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 68010 },
  { name: 'Bethesda', slug: 'bethesda', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 63374 },
  { name: 'Gaithersburg', slug: 'gaithersburg', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 68365 },
  { name: 'Annapolis', slug: 'annapolis', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 40812 },
  { name: 'Silver Spring', slug: 'silver-spring', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 81015 },
  { name: 'Columbia', slug: 'columbia-md', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 105162 },
  { name: 'Frederick', slug: 'frederick', state: 'Maryland', stateSlug: 'maryland', stateAbbr: 'MD', population: 78171 },
  // ── CONNECTICUT ──
  { name: 'Hartford', slug: 'hartford', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 121054 },
  { name: 'Stamford', slug: 'stamford', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 135470 },
  { name: 'Bridgeport', slug: 'bridgeport', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 148654 },
  { name: 'New Haven', slug: 'new-haven', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 130250 },
  { name: 'Greenwich', slug: 'greenwich', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 63518 },
  { name: 'Westport', slug: 'westport', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 28097 },
  { name: 'Danbury', slug: 'danbury', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 86518 },
  { name: 'Norwalk', slug: 'norwalk', state: 'Connecticut', stateSlug: 'connecticut', stateAbbr: 'CT', population: 91184 },
  // ── TENNESSEE ──
  { name: 'Nashville', slug: 'nashville', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 689447 },
  { name: 'Memphis', slug: 'memphis', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 651073 },
  { name: 'Knoxville', slug: 'knoxville', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 190740 },
  { name: 'Chattanooga', slug: 'chattanooga', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 181099 },
  { name: 'Brentwood', slug: 'brentwood', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 45658 },
  { name: 'Franklin', slug: 'franklin', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 83454 },
  { name: 'Clarksville', slug: 'clarksville', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 166722 },
  { name: 'Murfreesboro', slug: 'murfreesboro', state: 'Tennessee', stateSlug: 'tennessee', stateAbbr: 'TN', population: 152769 },
  // ── INDIANA ──
  { name: 'Indianapolis', slug: 'indianapolis', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 887642 },
  { name: 'Fort Wayne', slug: 'fort-wayne', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 268378 },
  { name: 'Evansville', slug: 'evansville', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 117979 },
  { name: 'South Bend', slug: 'south-bend', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 103453 },
  { name: 'Carmel', slug: 'carmel', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 99757 },
  { name: 'Fishers', slug: 'fishers', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 99604 },
  // ── MISSOURI ──
  { name: 'Kansas City', slug: 'kansas-city-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 508090 },
  { name: 'St. Louis', slug: 'st-louis', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 301578 },
  { name: 'Springfield', slug: 'springfield-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 167319 },
  { name: 'Columbia', slug: 'columbia-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 126254 },
  { name: "Lee's Summit", slug: 'lees-summit', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 101108 },
  { name: 'Clayton', slug: 'clayton', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 17044 },
  // ── WISCONSIN ──
  { name: 'Milwaukee', slug: 'milwaukee', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 577222 },
  { name: 'Madison', slug: 'madison', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 269840 },
  { name: 'Green Bay', slug: 'green-bay', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 107395 },
  { name: 'Kenosha', slug: 'kenosha', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 100150 },
  { name: 'Racine', slug: 'racine', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 77816 },
  { name: 'Waukesha', slug: 'waukesha', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 73403 },
  // ── NEVADA ──
  { name: 'Las Vegas', slug: 'las-vegas', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 641903 },
  { name: 'Henderson', slug: 'henderson', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 320189 },
  { name: 'Reno', slug: 'reno', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 255601 },
  { name: 'North Las Vegas', slug: 'north-las-vegas', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 262527 },
  { name: 'Sparks', slug: 'sparks', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 105006 },
  { name: 'Carson City', slug: 'carson-city', state: 'Nevada', stateSlug: 'nevada', stateAbbr: 'NV', population: 58639 },
  // ── OREGON ──
  { name: 'Portland', slug: 'portland', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 652503 },
  { name: 'Salem', slug: 'salem', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 175535 },
  { name: 'Eugene', slug: 'eugene', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 176654 },
  { name: 'Beaverton', slug: 'beaverton', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 97590 },
  { name: 'Hillsboro', slug: 'hillsboro', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 106447 },
  { name: 'Bend', slug: 'bend', state: 'Oregon', stateSlug: 'oregon', stateAbbr: 'OR', population: 94520 },
  // ── UTAH ──
  { name: 'Salt Lake City', slug: 'salt-lake-city', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 200133 },
  { name: 'Provo', slug: 'provo', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 115264 },
  { name: 'Ogden', slug: 'ogden', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 87321 },
  { name: 'St. George', slug: 'st-george', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 89587 },
  { name: 'Lehi', slug: 'lehi', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 75907 },
  { name: 'Sandy', slug: 'sandy-ut', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 96382 },
  { name: 'West Valley City', slug: 'west-valley-city', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 140230 },
  { name: 'West Jordan', slug: 'west-jordan', state: 'Utah', stateSlug: 'utah', stateAbbr: 'UT', population: 116961 },
  // ── SOUTH CAROLINA ──
  { name: 'Charleston', slug: 'charleston', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 150227 },
  { name: 'Columbia', slug: 'columbia-sc', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 136632 },
  { name: 'Greenville', slug: 'greenville', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 70720 },
  { name: 'Spartanburg', slug: 'spartanburg', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 37646 },
  { name: 'Myrtle Beach', slug: 'myrtle-beach', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 34695 },
  { name: 'Rock Hill', slug: 'rock-hill', state: 'South Carolina', stateSlug: 'south-carolina', stateAbbr: 'SC', population: 75048 },
  // ── LOUISIANA ──
  { name: 'New Orleans', slug: 'new-orleans', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 383997 },
  { name: 'Baton Rouge', slug: 'baton-rouge', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 227470 },
  { name: 'Shreveport', slug: 'shreveport', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 187593 },
  { name: 'Lafayette', slug: 'lafayette', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 121374 },
  { name: 'Metairie', slug: 'metairie', state: 'Louisiana', stateSlug: 'louisiana', stateAbbr: 'LA', population: 138482 },
  // ── KENTUCKY ──
  { name: 'Louisville', slug: 'louisville', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 633045 },
  { name: 'Lexington', slug: 'lexington-ky', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 322570 },
  { name: 'Covington', slug: 'covington', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 40640 },
  { name: 'Bowling Green', slug: 'bowling-green', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 72294 },
  { name: 'Owensboro', slug: 'owensboro', state: 'Kentucky', stateSlug: 'kentucky', stateAbbr: 'KY', population: 60580 },
  // ── ALABAMA ──
  { name: 'Birmingham', slug: 'birmingham', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 212237 },
  { name: 'Huntsville', slug: 'huntsville', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 215006 },
  { name: 'Mobile', slug: 'mobile', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 187041 },
  { name: 'Montgomery', slug: 'montgomery', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 199518 },
  { name: 'Tuscaloosa', slug: 'tuscaloosa', state: 'Alabama', stateSlug: 'alabama', stateAbbr: 'AL', population: 99543 },
  // ── OKLAHOMA ──
  { name: 'Oklahoma City', slug: 'oklahoma-city', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 681054 },
  { name: 'Tulsa', slug: 'tulsa', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 413066 },
  { name: 'Norman', slug: 'norman', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 128026 },
  { name: 'Broken Arrow', slug: 'broken-arrow', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 113540 },
  { name: 'Edmond', slug: 'edmond', state: 'Oklahoma', stateSlug: 'oklahoma', stateAbbr: 'OK', population: 97318 },
  // ── KANSAS ──
  { name: 'Wichita', slug: 'wichita', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 397532 },
  { name: 'Overland Park', slug: 'overland-park', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 197238 },
  { name: 'Kansas City', slug: 'kansas-city-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 156607 },
  { name: 'Olathe', slug: 'olathe', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 141290 },
  { name: 'Topeka', slug: 'topeka', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 125904 },
  // ── IOWA ──
  { name: 'Des Moines', slug: 'des-moines', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 214133 },
  { name: 'Cedar Rapids', slug: 'cedar-rapids', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 137710 },
  { name: 'Davenport', slug: 'davenport', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 101724 },
  { name: 'Iowa City', slug: 'iowa-city', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 74738 },
  { name: 'Sioux City', slug: 'sioux-city', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 85797 },
  // ── NEBRASKA ──
  { name: 'Omaha', slug: 'omaha', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 486051 },
  { name: 'Lincoln', slug: 'lincoln', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 291082 },
  { name: 'Bellevue', slug: 'bellevue-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 62949 },
  // ── NEW MEXICO ──
  { name: 'Albuquerque', slug: 'albuquerque', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 564559 },
  { name: 'Santa Fe', slug: 'santa-fe', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 84683 },
  { name: 'Las Cruces', slug: 'las-cruces', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 111385 },
  { name: 'Rio Rancho', slug: 'rio-rancho', state: 'New Mexico', stateSlug: 'new-mexico', stateAbbr: 'NM', population: 104046 },
  // ── IDAHO ──
  { name: 'Boise', slug: 'boise', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 235684 },
  { name: 'Nampa', slug: 'nampa', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 100200 },
  { name: 'Meridian', slug: 'meridian', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 120719 },
  { name: 'Idaho Falls', slug: 'idaho-falls', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 64818 },
  { name: 'Pocatello', slug: 'pocatello', state: 'Idaho', stateSlug: 'idaho', stateAbbr: 'ID', population: 56536 },
  // ── ARKANSAS ──
  { name: 'Little Rock', slug: 'little-rock', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 202591 },
  { name: 'Fayetteville', slug: 'fayetteville-ar', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 93949 },
  { name: 'Fort Smith', slug: 'fort-smith', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 88037 },
  { name: 'Springdale', slug: 'springdale', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 84161 },
  { name: 'Bentonville', slug: 'bentonville', state: 'Arkansas', stateSlug: 'arkansas', stateAbbr: 'AR', population: 52979 },
  // ── MISSISSIPPI ──
  { name: 'Jackson', slug: 'jackson', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 153701 },
  { name: 'Gulfport', slug: 'gulfport', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 73013 },
  { name: 'Southaven', slug: 'southaven', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 55535 },
  { name: 'Hattiesburg', slug: 'hattiesburg', state: 'Mississippi', stateSlug: 'mississippi', stateAbbr: 'MS', population: 46523 },
  // ── MONTANA ──
  { name: 'Billings', slug: 'billings', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 119616 },
  { name: 'Missoula', slug: 'missoula', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 74598 },
  { name: 'Great Falls', slug: 'great-falls', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 60442 },
  { name: 'Bozeman', slug: 'bozeman', state: 'Montana', stateSlug: 'montana', stateAbbr: 'MT', population: 53293 },
  // ── DELAWARE ──
  { name: 'Wilmington', slug: 'wilmington-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 70898 },
  { name: 'Dover', slug: 'dover', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 38079 },
  { name: 'Newark', slug: 'newark-de', state: 'Delaware', stateSlug: 'delaware', stateAbbr: 'DE', population: 31454 },
  // ── HAWAII ──
  { name: 'Honolulu', slug: 'honolulu', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 350964 },
  { name: 'Pearl City', slug: 'pearl-city', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 47698 },
  { name: 'Hilo', slug: 'hilo', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 44186 },
  { name: 'Kailua', slug: 'kailua', state: 'Hawaii', stateSlug: 'hawaii', stateAbbr: 'HI', population: 38216 },
  // ── WEST VIRGINIA ──
  { name: 'Charleston', slug: 'charleston-wv', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 46692 },
  { name: 'Huntington', slug: 'huntington-wv', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 46842 },
  { name: 'Morgantown', slug: 'morgantown', state: 'West Virginia', stateSlug: 'west-virginia', stateAbbr: 'WV', population: 29660 },
  // ── ALASKA ──
  { name: 'Anchorage', slug: 'anchorage', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 291247 },
  { name: 'Fairbanks', slug: 'fairbanks', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 31535 },
  { name: 'Juneau', slug: 'juneau', state: 'Alaska', stateSlug: 'alaska', stateAbbr: 'AK', population: 32255 },
  // ── WYOMING ──
  { name: 'Cheyenne', slug: 'cheyenne', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 64235 },
  { name: 'Casper', slug: 'casper', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 59038 },
  { name: 'Laramie', slug: 'laramie', state: 'Wyoming', stateSlug: 'wyoming', stateAbbr: 'WY', population: 32158 },
  // ── NORTH DAKOTA ──
  { name: 'Fargo', slug: 'fargo', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 125990 },
  { name: 'Bismarck', slug: 'bismarck', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 73622 },
  { name: 'Grand Forks', slug: 'grand-forks', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 59166 },
  { name: 'Minot', slug: 'minot', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 48862 },
  // ── SOUTH DAKOTA ──
  { name: 'Sioux Falls', slug: 'sioux-falls', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 192517 },
  { name: 'Rapid City', slug: 'rapid-city', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 76692 },
  { name: 'Aberdeen', slug: 'aberdeen', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 28495 },
  // ── VERMONT ──
  { name: 'Burlington', slug: 'burlington-vt', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 44743 },
  { name: 'South Burlington', slug: 'south-burlington', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 20292 },
  { name: 'Montpelier', slug: 'montpelier', state: 'Vermont', stateSlug: 'vermont', stateAbbr: 'VT', population: 7855 },
  // ── MAINE ──
  { name: 'Portland', slug: 'portland-me', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 68408 },
  { name: 'Lewiston', slug: 'lewiston', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 36592 },
  { name: 'Bangor', slug: 'bangor', state: 'Maine', stateSlug: 'maine', stateAbbr: 'ME', population: 31753 },
  // ── RHODE ISLAND ──
  { name: 'Providence', slug: 'providence', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 190934 },
  { name: 'Warwick', slug: 'warwick', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 82672 },
  { name: 'Cranston', slug: 'cranston', state: 'Rhode Island', stateSlug: 'rhode-island', stateAbbr: 'RI', population: 81798 },
  // ── NEW HAMPSHIRE ──
  { name: 'Manchester', slug: 'manchester-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 115644 },
  { name: 'Nashua', slug: 'nashua', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 91322 },
  { name: 'Concord', slug: 'concord-nh', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 43627 },
  { name: 'Portsmouth', slug: 'portsmouth', state: 'New Hampshire', stateSlug: 'new-hampshire', stateAbbr: 'NH', population: 21956 },
]

import { CITIES_WEST } from './cities-west'
import { CITIES_SOUTH } from './cities-south'
import { CITIES_MIDWEST } from './cities-midwest'
import { CITIES_NORTHEAST } from './cities-northeast'


export const ALL_CITIES: City[] = [
  ...CITIES,
  ...CITIES_WEST,
  ...CITIES_SOUTH,
  ...CITIES_MIDWEST,
  ...CITIES_NORTHEAST,
]

export function getCityBySlug(slug: string): City | undefined {
  return ALL_CITIES.find(c => c.slug === slug)
}

export function getCitiesByState(stateSlug: string): City[] {
  return ALL_CITIES.filter(c => c.stateSlug === stateSlug)
}

export function getAllCitySlugs(): { citySlug: string; stateSlug: string }[] {
  return ALL_CITIES.map(c => ({ citySlug: c.slug, stateSlug: c.stateSlug }))
}

export function toSlug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
