import type { City } from './city-types'

export const CITIES_MIDWEST: City[] = [
  // Illinois (IL)
  { name: 'Aurora', slug: 'aurora-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 200965 },
  { name: 'Rockford', slug: 'rockford-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 148278 },
  { name: 'Joliet', slug: 'joliet-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 150362 },
  { name: 'Naperville', slug: 'naperville-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 149104 },
  { name: 'Springfield', slug: 'springfield-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 114394 },
  { name: 'Peoria', slug: 'peoria-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 113150 },
  { name: 'Elgin', slug: 'elgin-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 114797 },
  { name: 'Waukegan', slug: 'waukegan-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 87938 },
  { name: 'Cicero', slug: 'cicero-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 84103 },
  { name: 'Champaign', slug: 'champaign-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 92567 },
  { name: 'Bloomington', slug: 'bloomington-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 79168 },
  { name: 'Arlington Heights', slug: 'arlington-heights-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 77676 },
  { name: 'Evanston', slug: 'evanston-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 73233 },
  { name: 'Decatur', slug: 'decatur-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 68081 },
  { name: 'Schaumburg', slug: 'schaumburg-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 78723 },
  { name: 'Bolingbrook', slug: 'bolingbrook-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 74184 },
  { name: 'Palatine', slug: 'palatine-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 68799 },
  { name: 'Skokie', slug: 'skokie-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 65068 },
  { name: 'Des Plaines', slug: 'des-plaines-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 60016 },
  { name: 'Orland Park', slug: 'orland-park-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 58132 },
  { name: 'Tinley Park', slug: 'tinley-park-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 57072 },
  { name: 'Oak Lawn', slug: 'oak-lawn-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 55245 },
  { name: 'Berwyn', slug: 'berwyn-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 56657 },
  { name: 'Mount Prospect', slug: 'mount-prospect-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 55170 },
  { name: 'Normal', slug: 'normal-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 54664 },
  { name: 'Wheaton', slug: 'wheaton-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 53648 },
  { name: 'Downers Grove', slug: 'downers-grove-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 50098 },
  { name: 'Hoffman Estates', slug: 'hoffman-estates-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 52398 },
  { name: 'Oak Park', slug: 'oak-park-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 52233 },
  { name: 'Glenview', slug: 'glenview-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 47986 },
  { name: 'Belleville', slug: 'belleville-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 44478 },
  { name: 'Moline', slug: 'moline-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 42664 },
  { name: 'Urbana', slug: 'urbana-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 38336 },
  { name: 'Galesburg', slug: 'galesburg-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 29193 },
  { name: 'Niles', slug: 'niles-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 29803 },
  { name: 'Calumet City', slug: 'calumet-city-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 36048 },
  { name: 'Carol Stream', slug: 'carol-stream-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 41828 },
  { name: 'Bartlett', slug: 'bartlett-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 41208 },
  { name: 'Romeoville', slug: 'romeoville-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 39680 },
  { name: 'Streamwood', slug: 'streamwood-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 40351 },
  { name: 'Crystal Lake', slug: 'crystal-lake-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 40743 },
  { name: 'Hanover Park', slug: 'hanover-park-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 38510 },
  { name: 'Addison', slug: 'addison-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 37384 },
  { name: 'Danville', slug: 'danville-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 31353 },
  { name: 'Quincy', slug: 'quincy-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 40633 },
  { name: 'Freeport', slug: 'freeport-il', state: 'Illinois', stateSlug: 'illinois', stateAbbr: 'IL', population: 23941 },

  // Ohio (OH)
  { name: 'Columbus', slug: 'columbus-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 905748 },
  { name: 'Cleveland', slug: 'cleveland-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 372624 },
  { name: 'Cincinnati', slug: 'cincinnati-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 309317 },
  { name: 'Toledo', slug: 'toledo-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 270871 },
  { name: 'Akron', slug: 'akron-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 190469 },
  { name: 'Dayton', slug: 'dayton-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 137644 },
  { name: 'Parma', slug: 'parma-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 78103 },
  { name: 'Canton', slug: 'canton-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 70458 },
  { name: 'Youngstown', slug: 'youngstown-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 60068 },
  { name: 'Lorain', slug: 'lorain-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 63710 },
  { name: 'Hamilton', slug: 'hamilton-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 63399 },
  { name: 'Springfield', slug: 'springfield-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 58662 },
  { name: 'Kettering', slug: 'kettering-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 56163 },
  { name: 'Elyria', slug: 'elyria-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 54086 },
  { name: 'Lakewood', slug: 'lakewood-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 51769 },
  { name: 'Cuyahoga Falls', slug: 'cuyahoga-falls-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 49852 },
  { name: 'Middletown', slug: 'middletown-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 51605 },
  { name: 'Euclid', slug: 'euclid-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 47047 },
  { name: 'Newark', slug: 'newark-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 49648 },
  { name: 'Mansfield', slug: 'mansfield-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 45921 },
  { name: 'Mentor', slug: 'mentor-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 46985 },
  { name: 'Cleveland Heights', slug: 'cleveland-heights-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 43566 },
  { name: 'Beavercreek', slug: 'beavercreek-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 46549 },
  { name: 'Strongsville', slug: 'strongsville-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 44750 },
  { name: 'Findlay', slug: 'findlay-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 41202 },
  { name: 'Fairfield', slug: 'fairfield-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 42956 },
  { name: 'Warren', slug: 'warren-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 38573 },
  { name: 'Lima', slug: 'lima-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35769 },
  { name: 'Upper Arlington', slug: 'upper-arlington-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35648 },
  { name: 'Grove City', slug: 'grove-city-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 41922 },
  { name: 'Reynoldsburg', slug: 'reynoldsburg-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 40503 },
  { name: 'Westerville', slug: 'westerville-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 38959 },
  { name: 'Dublin', slug: 'dublin-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 49328 },
  { name: 'Hilliard', slug: 'hilliard-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 36534 },
  { name: 'Huber Heights', slug: 'huber-heights-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 40756 },
  { name: 'Gahanna', slug: 'gahanna-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35593 },
  { name: 'Mason', slug: 'mason-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 33690 },
  { name: 'Medina', slug: 'medina-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 26678 },
  { name: 'Brunswick', slug: 'brunswick-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35567 },
  { name: 'Sandusky', slug: 'sandusky-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 25325 },
  { name: 'Fairborn', slug: 'fairborn-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 34588 },
  { name: 'Lancaster', slug: 'lancaster-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 40399 },
  { name: 'Marion', slug: 'marion-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35318 },
  { name: 'Stow', slug: 'stow-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35066 },
  { name: 'Barberton', slug: 'barberton-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 26558 },
  { name: 'Boardman', slug: 'boardman-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 35376 },
  { name: 'Zanesville', slug: 'zanesville-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 25093 },
  { name: 'Niles', slug: 'niles-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 19011 },
  { name: 'Defiance', slug: 'defiance-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 16540 },
  { name: 'Alliance', slug: 'alliance-oh', state: 'Ohio', stateSlug: 'ohio', stateAbbr: 'OH', population: 21822 },

  // Michigan (MI)
  { name: 'Detroit', slug: 'detroit-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 639111 },
  { name: 'Grand Rapids', slug: 'grand-rapids-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 198917 },
  { name: 'Warren', slug: 'warren-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 139387 },
  { name: 'Sterling Heights', slug: 'sterling-heights-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 132438 },
  { name: 'Ann Arbor', slug: 'ann-arbor-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 123851 },
  { name: 'Lansing', slug: 'lansing-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 112644 },
  { name: 'Flint', slug: 'flint-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 81252 },
  { name: 'Dearborn', slug: 'dearborn-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 109976 },
  { name: 'Livonia', slug: 'livonia-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 96942 },
  { name: 'Westland', slug: 'westland-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 84094 },
  { name: 'Troy', slug: 'troy-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 87294 },
  { name: 'Farmington Hills', slug: 'farmington-hills-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 83986 },
  { name: 'Kalamazoo', slug: 'kalamazoo-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 72293 },
  { name: 'Wyoming', slug: 'wyoming-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 76058 },
  { name: 'Southfield', slug: 'southfield-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 73006 },
  { name: 'Rochester Hills', slug: 'rochester-hills-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 73469 },
  { name: 'Taylor', slug: 'taylor-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 61817 },
  { name: 'Pontiac', slug: 'pontiac-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 59515 },
  { name: 'St. Clair Shores', slug: 'st-clair-shores-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 59715 },
  { name: 'Royal Oak', slug: 'royal-oak-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 59764 },
  { name: 'Novi', slug: 'novi-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 57023 },
  { name: 'Dearborn Heights', slug: 'dearborn-heights-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 56951 },
  { name: 'Battle Creek', slug: 'battle-creek-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 51008 },
  { name: 'Saginaw', slug: 'saginaw-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 44173 },
  { name: 'Kentwood', slug: 'kentwood-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 53169 },
  { name: 'East Lansing', slug: 'east-lansing-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 48579 },
  { name: 'Roseville', slug: 'roseville-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 47299 },
  { name: 'Portage', slug: 'portage-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 49996 },
  { name: 'Midland', slug: 'midland-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 42181 },
  { name: 'Mount Pleasant', slug: 'mount-pleasant-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 19661 },
  { name: 'Bay City', slug: 'bay-city-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 28765 },
  { name: 'Muskegon', slug: 'muskegon-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 38401 },
  { name: 'Holland', slug: 'holland-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 33208 },
  { name: 'Clinton Township', slug: 'clinton-township-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 101837 },
  { name: 'Waterford', slug: 'waterford-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 72538 },
  { name: 'Lincoln Park', slug: 'lincoln-park-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 37420 },
  { name: 'Ypsilanti', slug: 'ypsilanti-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 19855 },
  { name: 'Canton', slug: 'canton-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 99531 },
  { name: 'Burton', slug: 'burton-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 28219 },
  { name: 'Traverse City', slug: 'traverse-city-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 15778 },
  { name: 'Madison Heights', slug: 'madison-heights-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 29690 },
  { name: 'Oak Park', slug: 'oak-park-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 29319 },
  { name: 'Inkster', slug: 'inkster-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 24128 },
  { name: 'Sault Ste. Marie', slug: 'sault-ste-marie-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 13337 },
  { name: 'Marquette', slug: 'marquette-mi', state: 'Michigan', stateSlug: 'michigan', stateAbbr: 'MI', population: 19661 },

  // Indiana (IN)
  { name: 'Indianapolis', slug: 'indianapolis-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 887642 },
  { name: 'Fort Wayne', slug: 'fort-wayne-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 270402 },
  { name: 'Evansville', slug: 'evansville-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 117429 },
  { name: 'South Bend', slug: 'south-bend-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 103453 },
  { name: 'Carmel', slug: 'carmel-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 101068 },
  { name: 'Fishers', slug: 'fishers-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 100905 },
  { name: 'Bloomington', slug: 'bloomington-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 84067 },
  { name: 'Hammond', slug: 'hammond-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 74812 },
  { name: 'Gary', slug: 'gary-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 69093 },
  { name: 'Muncie', slug: 'muncie-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 65320 },
  { name: 'Lafayette', slug: 'lafayette-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 70373 },
  { name: 'Terre Haute', slug: 'terre-haute-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 58808 },
  { name: 'Anderson', slug: 'anderson-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 54150 },
  { name: 'Noblesville', slug: 'noblesville-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 69604 },
  { name: 'Greenwood', slug: 'greenwood-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 62751 },
  { name: 'Kokomo', slug: 'kokomo-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 59010 },
  { name: 'Westfield', slug: 'westfield-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 47286 },
  { name: 'Elkhart', slug: 'elkhart-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 53923 },
  { name: 'Mishawaka', slug: 'mishawaka-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 48498 },
  { name: 'Lawrence', slug: 'lawrence-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 46001 },
  { name: 'Jeffersonville', slug: 'jeffersonville-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 47813 },
  { name: 'Columbus', slug: 'columbus-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 47972 },
  { name: 'Portage', slug: 'portage-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 36828 },
  { name: 'New Albany', slug: 'new-albany-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 36827 },
  { name: 'Zionsville', slug: 'zionsville-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 29021 },
  { name: 'Highland', slug: 'highland-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 22995 },
  { name: 'Merrillville', slug: 'merrillville-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 34869 },
  { name: 'Michigan City', slug: 'michigan-city-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 31779 },
  { name: 'Valparaiso', slug: 'valparaiso-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 32969 },
  { name: 'Goshen', slug: 'goshen-in', state: 'Indiana', stateSlug: 'indiana', stateAbbr: 'IN', population: 35778 },

  // Wisconsin (WI)
  { name: 'Milwaukee', slug: 'milwaukee-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 577222 },
  { name: 'Madison', slug: 'madison-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 269196 },
  { name: 'Green Bay', slug: 'green-bay-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 107395 },
  { name: 'Kenosha', slug: 'kenosha-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 99776 },
  { name: 'Racine', slug: 'racine-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 77816 },
  { name: 'Appleton', slug: 'appleton-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 75644 },
  { name: 'Waukesha', slug: 'waukesha-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 72734 },
  { name: 'Oshkosh', slug: 'oshkosh-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 66816 },
  { name: 'Eau Claire', slug: 'eau-claire-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 69153 },
  { name: 'Janesville', slug: 'janesville-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 65615 },
  { name: 'West Allis', slug: 'west-allis-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 60411 },
  { name: 'La Crosse', slug: 'la-crosse-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 52680 },
  { name: 'Sheboygan', slug: 'sheboygan-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 50314 },
  { name: 'Wauwatosa', slug: 'wauwatosa-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 47981 },
  { name: 'Fond du Lac', slug: 'fond-du-lac-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 43069 },
  { name: 'New Berlin', slug: 'new-berlin-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 39584 },
  { name: 'Wausau', slug: 'wausau-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 38426 },
  { name: 'Brookfield', slug: 'brookfield-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 40977 },
  { name: 'Beloit', slug: 'beloit-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 36966 },
  { name: 'Greenfield', slug: 'greenfield-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 36720 },
  { name: 'Menomonee Falls', slug: 'menomonee-falls-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 35626 },
  { name: 'West Bend', slug: 'west-bend-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 31587 },
  { name: 'Sun Prairie', slug: 'sun-prairie-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 34983 },
  { name: 'Superior', slug: 'superior-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 26751 },
  { name: 'Manitowoc', slug: 'manitowoc-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 32539 },
  { name: 'Mequon', slug: 'mequon-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 23795 },
  { name: 'De Pere', slug: 'de-pere-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 24393 },
  { name: 'Fitchburg', slug: 'fitchburg-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 29364 },
  { name: 'Caledonia', slug: 'caledonia-wi', state: 'Wisconsin', stateSlug: 'wisconsin', stateAbbr: 'WI', population: 25623 },

  // Minnesota (MN)
  { name: 'Minneapolis', slug: 'minneapolis-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 429954 },
  { name: 'Saint Paul', slug: 'saint-paul-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 311527 },
  { name: 'Rochester', slug: 'rochester-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 124016 },
  { name: 'Duluth', slug: 'duluth-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 90314 },
  { name: 'Bloomington', slug: 'bloomington-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 89987 },
  { name: 'Brooklyn Park', slug: 'brooklyn-park-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 86478 },
  { name: 'Plymouth', slug: 'plymouth-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 79828 },
  { name: 'Maple Grove', slug: 'maple-grove-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 70253 },
  { name: 'Woodbury', slug: 'woodbury-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 75149 },
  { name: 'St. Cloud', slug: 'st-cloud-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 67559 },
  { name: 'Eagan', slug: 'eagan-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 68855 },
  { name: 'Burnsville', slug: 'burnsville-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 64317 },
  { name: 'Coon Rapids', slug: 'coon-rapids-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 63599 },
  { name: 'Brooklyn Center', slug: 'brooklyn-center-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 33095 },
  { name: 'Eden Prairie', slug: 'eden-prairie-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 64920 },
  { name: 'Minnetonka', slug: 'minnetonka-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 53805 },
  { name: 'Blaine', slug: 'blaine-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 70002 },
  { name: 'Edina', slug: 'edina-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 53494 },
  { name: 'Lakeville', slug: 'lakeville-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 69490 },
  { name: 'Mankato', slug: 'mankato-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 44488 },
  { name: 'Richfield', slug: 'richfield-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 36994 },
  { name: 'Apple Valley', slug: 'apple-valley-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 55491 },
  { name: 'Shakopee', slug: 'shakopee-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 43396 },
  { name: 'Maplewood', slug: 'maplewood-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 41437 },
  { name: 'Cottage Grove', slug: 'cottage-grove-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 38338 },
  { name: 'Inver Grove Heights', slug: 'inver-grove-heights-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 34729 },
  { name: 'Fridley', slug: 'fridley-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 29334 },
  { name: 'Roseville', slug: 'roseville-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 36571 },
  { name: 'Shoreview', slug: 'shoreview-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 25648 },
  { name: 'Prior Lake', slug: 'prior-lake-mn', state: 'Minnesota', stateSlug: 'minnesota', stateAbbr: 'MN', population: 27743 },

  // Iowa (IA)
  { name: 'Des Moines', slug: 'des-moines-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 214133 },
  { name: 'Cedar Rapids', slug: 'cedar-rapids-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 137710 },
  { name: 'Davenport', slug: 'davenport-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 101724 },
  { name: 'Sioux City', slug: 'sioux-city-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 82516 },
  { name: 'Iowa City', slug: 'iowa-city-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 74398 },
  { name: 'Waterloo', slug: 'waterloo-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 67314 },
  { name: 'Council Bluffs', slug: 'council-bluffs-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 62526 },
  { name: 'Ames', slug: 'ames-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 66427 },
  { name: 'West Des Moines', slug: 'west-des-moines-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 67982 },
  { name: 'Dubuque', slug: 'dubuque-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 59667 },
  { name: 'Ankeny', slug: 'ankeny-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 67355 },
  { name: 'Urbandale', slug: 'urbandale-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 45456 },
  { name: 'Cedar Falls', slug: 'cedar-falls-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 40566 },
  { name: 'Marion', slug: 'marion-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 40567 },
  { name: 'Bettendorf', slug: 'bettendorf-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 38506 },
  { name: 'Mason City', slug: 'mason-city-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 27453 },
  { name: 'Marshalltown', slug: 'marshalltown-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 27695 },
  { name: 'Clinton', slug: 'clinton-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 24945 },
  { name: 'Burlington', slug: 'burlington-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 24711 },
  { name: 'Ottumwa', slug: 'ottumwa-ia', state: 'Iowa', stateSlug: 'iowa', stateAbbr: 'IA', population: 24311 },

  // Missouri (MO)
  { name: 'Kansas City', slug: 'kansas-city-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 508090 },
  { name: 'St. Louis', slug: 'st-louis-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 301578 },
  { name: 'Springfield', slug: 'springfield-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 169176 },
  { name: 'Columbia', slug: 'columbia-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 126254 },
  { name: 'Independence', slug: 'independence-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 123811 },
  { name: "Lee's Summit", slug: 'lees-summit-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 100271 },
  { name: "O'Fallon", slug: 'ofallon-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 91316 },
  { name: 'St. Joseph', slug: 'st-joseph-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 73990 },
  { name: 'St. Charles', slug: 'st-charles-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 70427 },
  { name: 'Blue Springs', slug: 'blue-springs-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 59801 },
  { name: 'Joplin', slug: 'joplin-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 52028 },
  { name: 'Chesterfield', slug: 'chesterfield-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 47484 },
  { name: 'Jefferson City', slug: 'jefferson-city-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 43228 },
  { name: 'Cape Girardeau', slug: 'cape-girardeau-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 40301 },
  { name: 'Florissant', slug: 'florissant-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 55265 },
  { name: 'Wentzville', slug: 'wentzville-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 45099 },
  { name: 'University City', slug: 'university-city-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 34032 },
  { name: 'Ballwin', slug: 'ballwin-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 30404 },
  { name: 'Raytown', slug: 'raytown-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 29426 },
  { name: 'Kirkwood', slug: 'kirkwood-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 27540 },
  { name: 'Maryland Heights', slug: 'maryland-heights-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 27472 },
  { name: 'Hazelwood', slug: 'hazelwood-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 25703 },
  { name: 'Gladstone', slug: 'gladstone-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 27095 },
  { name: 'Liberty', slug: 'liberty-mo', state: 'Missouri', stateSlug: 'missouri', stateAbbr: 'MO', population: 29149 },

  // North Dakota (ND)
  { name: 'Fargo', slug: 'fargo-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 125990 },
  { name: 'Bismarck', slug: 'bismarck-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 73622 },
  { name: 'Grand Forks', slug: 'grand-forks-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 57339 },
  { name: 'Minot', slug: 'minot-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 48743 },
  { name: 'West Fargo', slug: 'west-fargo-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 38626 },
  { name: 'Mandan', slug: 'mandan-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 22636 },
  { name: 'Dickinson', slug: 'dickinson-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 24001 },
  { name: 'Jamestown', slug: 'jamestown-nd', state: 'North Dakota', stateSlug: 'north-dakota', stateAbbr: 'ND', population: 15629 },

  // South Dakota (SD)
  { name: 'Sioux Falls', slug: 'sioux-falls-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 192517 },
  { name: 'Rapid City', slug: 'rapid-city-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 80366 },
  { name: 'Aberdeen', slug: 'aberdeen-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 28495 },
  { name: 'Brookings', slug: 'brookings-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 25494 },
  { name: 'Watertown', slug: 'watertown-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 22655 },
  { name: 'Mitchell', slug: 'mitchell-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 15660 },
  { name: 'Yankton', slug: 'yankton-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 14687 },
  { name: 'Huron', slug: 'huron-sd', state: 'South Dakota', stateSlug: 'south-dakota', stateAbbr: 'SD', population: 13209 },

  // Nebraska (NE)
  { name: 'Omaha', slug: 'omaha-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 486051 },
  { name: 'Lincoln', slug: 'lincoln-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 295222 },
  { name: 'Bellevue', slug: 'bellevue-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 63977 },
  { name: 'Grand Island', slug: 'grand-island-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 51390 },
  { name: 'Kearney', slug: 'kearney-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 33790 },
  { name: 'Fremont', slug: 'fremont-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 26871 },
  { name: 'Hastings', slug: 'hastings-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 24907 },
  { name: 'Norfolk', slug: 'norfolk-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 24348 },
  { name: 'Columbus', slug: 'columbus-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 23999 },
  { name: 'Papillion', slug: 'papillion-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 24077 },
  { name: 'La Vista', slug: 'la-vista-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 16398 },
  { name: 'Scottsbluff', slug: 'scottsbluff-ne', state: 'Nebraska', stateSlug: 'nebraska', stateAbbr: 'NE', population: 14507 },

  // Kansas (KS)
  { name: 'Wichita', slug: 'wichita-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 397532 },
  { name: 'Overland Park', slug: 'overland-park-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 197238 },
  { name: 'Kansas City', slug: 'kansas-city-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 156607 },
  { name: 'Topeka', slug: 'topeka-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 126587 },
  { name: 'Olathe', slug: 'olathe-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 140545 },
  { name: 'Lawrence', slug: 'lawrence-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 95358 },
  { name: 'Shawnee', slug: 'shawnee-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 65827 },
  { name: 'Manhattan', slug: 'manhattan-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 55601 },
  { name: 'Lenexa', slug: 'lenexa-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 55979 },
  { name: 'Salina', slug: 'salina-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 45679 },
  { name: 'Hutchinson', slug: 'hutchinson-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 40787 },
  { name: 'Leavenworth', slug: 'leavenworth-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 35251 },
  { name: 'Leawood', slug: 'leawood-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 35148 },
  { name: 'Dodge City', slug: 'dodge-city-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 27781 },
  { name: 'Garden City', slug: 'garden-city-ks', state: 'Kansas', stateSlug: 'kansas', stateAbbr: 'KS', population: 26658 },
]
