export interface CompanyType {
  name: string
  slug: string
  description: string
  topRoles: string[]
  typicalRevenue: string
  painPoints: string[]
}

export const COMPANY_TYPES: CompanyType[] = [
  {
    name: 'Series A Startups',
    slug: 'series-a-startups',
    description: 'Venture-backed companies that have closed their first institutional funding round and are scaling their team and go-to-market.',
    topRoles: ['cfo', 'cto', 'cmo', 'coo'],
    typicalRevenue: '$500K–$5M ARR',
    painPoints: ['First institutional board reporting', 'Scaling from founder-led sales', 'First formal financial close process', 'Engineering team structure'],
  },
  {
    name: 'Series B & C Companies',
    slug: 'series-b-c-companies',
    description: 'Growth-stage companies raising $15M–$100M and scaling revenue, operations, and team at speed.',
    topRoles: ['cro', 'coo', 'cfo', 'chro'],
    typicalRevenue: '$5M–$50M ARR',
    painPoints: ['Revenue predictability and forecasting', 'Org design and headcount planning', 'Financial audit for the first time', 'Enterprise sales motion build-out'],
  },
  {
    name: 'PE-Backed Portfolio Companies',
    slug: 'pe-backed-companies',
    description: 'Companies owned by private equity sponsors undergoing value creation, add-on acquisitions, or preparation for an exit.',
    topRoles: ['cfo', 'coo', 'ceo', 'chro'],
    typicalRevenue: '$10M–$200M',
    painPoints: ['100-day value creation plan execution', 'EBITDA improvement and cost structure', 'Integration of add-on acquisitions', 'Exit readiness and QoE preparation'],
  },
  {
    name: 'Bootstrapped Companies',
    slug: 'bootstrapped-companies',
    description: 'Founder-owned businesses that have grown without institutional capital and are navigating professional leadership for the first time.',
    topRoles: ['cfo', 'coo', 'cmo', 'chro'],
    typicalRevenue: '$2M–$30M',
    painPoints: ['First outside professional leadership', 'Cash flow management at scale', 'Process and SOP formalization', 'Preparing for a potential sale or PE interest'],
  },
  {
    name: 'Family-Owned Businesses',
    slug: 'family-owned-businesses',
    description: 'Multi-generational family businesses facing succession, professionalization, or growth beyond the founding generation\'s expertise.',
    topRoles: ['ceo', 'cfo', 'coo', 'chro'],
    typicalRevenue: '$5M–$100M',
    painPoints: ['Family member to professional management transition', 'Succession planning', 'Competitive pressure from larger consolidators', 'Capital structure optimization'],
  },
  {
    name: 'Pre-Revenue Startups',
    slug: 'pre-revenue-startups',
    description: 'Seed and pre-seed stage companies preparing for their first significant capital raise or early commercial traction.',
    topRoles: ['cto', 'cfo', 'cmo', 'coo'],
    typicalRevenue: 'Pre-revenue',
    painPoints: ['Fundraising preparation', 'MVP architecture and product decisions', 'First go-to-market strategy', 'Financial model and projections'],
  },
  {
    name: 'Distressed Companies',
    slug: 'distressed-companies',
    description: 'Companies facing cash flow crises, covenant violations, leadership vacuums, or operational collapse requiring immediate intervention.',
    topRoles: ['ceo', 'cfo', 'coo', 'chro'],
    typicalRevenue: 'Any',
    painPoints: ['Cash preservation and runway extension', 'Lender and investor communication', 'Leadership vacuum stabilization', 'Rapid operational triage'],
  },
  {
    name: 'Public Companies',
    slug: 'public-companies',
    description: 'Listed companies on NYSE, NASDAQ, or other exchanges that need interim or fractional leadership during transition periods.',
    topRoles: ['cfo', 'coo', 'chro', 'ciso'],
    typicalRevenue: '$50M+',
    painPoints: ['Interim leadership during sudden departures', 'SEC reporting compliance during transition', 'Sarbanes-Oxley compliance oversight', 'Board governance during executive changes'],
  },
  {
    name: 'SPAC-Merged Companies',
    slug: 'spac-companies',
    description: 'Companies that went public via SPAC and are navigating the post-merger operational and financial complexity of being a public entity.',
    topRoles: ['cfo', 'coo', 'chro', 'ciso'],
    typicalRevenue: '$20M–$200M',
    painPoints: ['First public company financial reporting', 'SOX compliance build-out', 'Investor relations establishment', 'Working capital and cash management in a newly public entity'],
  },
  {
    name: 'Non-Profit Organizations',
    slug: 'nonprofit-organizations',
    description: '501(c)(3) charitable organizations, foundations, and mission-driven entities that need institutional leadership without full-time C-suite budgets.',
    topRoles: ['cfo', 'coo', 'chro', 'cmo'],
    typicalRevenue: '$1M–$50M budget',
    painPoints: ['Board reporting and financial controls', 'Grant compliance and restricted funds management', 'HR structure and staff retention', 'Mission-aligned growth strategy'],
  },
  {
    name: 'Government Contractors',
    slug: 'government-contractors',
    description: 'Federal, state, and local government contractors navigating DCAA compliance, contract transitions, and clearance requirements.',
    topRoles: ['cfo', 'coo', 'ciso', 'chro'],
    typicalRevenue: '$5M–$500M',
    painPoints: ['DCAA-compliant accounting and cost accounting standards', 'Contract transition and re-compete preparation', 'Security clearance program management', 'GSA schedule and OTA strategy'],
  },
  {
    name: 'Professional Sports Teams & Leagues',
    slug: 'sports-organizations',
    description: 'Professional and semi-professional sports teams, leagues, and sports entertainment businesses.',
    topRoles: ['cfo', 'coo', 'cmo', 'chro'],
    typicalRevenue: '$5M–$500M',
    painPoints: ['Revenue diversification and sponsorship growth', 'Stadium operations and event P&L', 'Media rights and broadcast contract negotiation', 'Player compensation and salary cap management'],
  },
  {
    name: 'Real Estate Investment Trusts (REITs)',
    slug: 'reits',
    description: 'Public and private REITs owning and operating income-producing real estate across asset classes.',
    topRoles: ['cfo', 'coo', 'chro', 'ciso'],
    typicalRevenue: '$10M–$1B+ AUM',
    painPoints: ['REIT qualification and compliance', 'Capital markets and debt refinancing', 'Property management operations', 'Investor distribution reporting'],
  },
  {
    name: 'Healthcare Systems & Hospital Groups',
    slug: 'healthcare-systems',
    description: 'Multi-site healthcare providers, hospital systems, and ambulatory care networks.',
    topRoles: ['coo', 'cfo', 'chro', 'ciso'],
    typicalRevenue: '$20M+',
    painPoints: ['Revenue cycle management and payer mix optimization', 'HIPAA compliance and security', 'Physician alignment and compensation models', 'Operational efficiency across multiple sites'],
  },
  {
    name: 'Search Fund Acquisitions',
    slug: 'search-funds',
    description: 'Companies acquired by entrepreneurial-through-acquisition (ETA) investors who need immediate operational and financial expertise.',
    topRoles: ['cfo', 'coo', 'chro', 'cmo'],
    typicalRevenue: '$2M–$15M EBITDA',
    painPoints: ['First 100 days of ownership transition', 'Financial systems upgrade from informal to institutional', 'Retention of key employees through ownership change', 'Establishing a board governance structure'],
  },
  {
    name: 'Roll-Up Platforms',
    slug: 'roll-ups',
    description: 'PE-backed platform companies executing serial acquisitions in fragmented industries.',
    topRoles: ['cfo', 'coo', 'chro', 'cto'],
    typicalRevenue: '$10M–$500M',
    painPoints: ['Integration of acquired businesses', 'Unified financial reporting across entities', 'ERP and systems consolidation', 'Culture and people integration across acquisitions'],
  },
  {
    name: 'Turnaround Situations',
    slug: 'turnarounds',
    description: 'Companies in operational or financial distress requiring a rapid triage, restructuring, and stabilization.',
    topRoles: ['ceo', 'cfo', 'coo', 'chro'],
    typicalRevenue: 'Any',
    painPoints: ['Cash preservation under 90 days of runway', 'Lender and investor negotiation', 'Rapid cost structure analysis and reduction', 'Morale stabilization and leadership credibility restoration'],
  },
  {
    name: 'Post-Merger Integration',
    slug: 'post-merger-integration',
    description: 'Companies navigating the integration of a significant merger or acquisition in the 12–24 months following close.',
    topRoles: ['coo', 'cfo', 'chro', 'cto'],
    typicalRevenue: 'Any',
    painPoints: ['Systems and data integration', 'Culture alignment and retention of acquired talent', 'Customer communication and contract transition', 'Financial reporting consolidation'],
  },
  {
    name: 'Pre-Exit Businesses',
    slug: 'pre-exit',
    description: 'Companies preparing for a strategic sale, PE recapitalization, or IPO in the next 12–36 months.',
    topRoles: ['cfo', 'coo', 'ceo', 'chro'],
    typicalRevenue: '$5M–$200M',
    painPoints: ['Quality of earnings preparation', 'Management presentation and data room', 'Normalizing EBITDA and removing seller discretionary expenses', 'Ensuring clean IP, contracts, and compliance records'],
  },
  {
    name: 'High-Growth Franchises',
    slug: 'franchise-systems',
    description: 'Franchise networks scaling franchisee count, territory expansion, and franchise support infrastructure.',
    topRoles: ['coo', 'cfo', 'cmo', 'chro'],
    typicalRevenue: '$2M–$100M system-wide',
    painPoints: ['Franchisee performance management and standards enforcement', 'Franchise disclosure document (FDD) compliance', 'Marketing fund management and local advertising', 'Supply chain and vendor management across locations'],
  },
  {
    name: 'Venture Studios & Holding Companies',
    slug: 'venture-studios',
    description: 'Venture studios, holding companies, and family investment vehicles that need portfolio-level C-suite support.',
    topRoles: ['cfo', 'coo', 'cto', 'chro'],
    typicalRevenue: 'Multiple entities',
    painPoints: ['Consolidated financial reporting across portfolio', 'Shared services infrastructure for portfolio companies', 'Portfolio-level talent strategy', 'Intercompany accounting and compliance'],
  },
  {
    name: 'SaaS Companies Scaling to Enterprise',
    slug: 'saas-enterprise',
    description: 'SaaS companies transitioning from SMB to enterprise sales, requiring enterprise-grade security, compliance, and support infrastructure.',
    topRoles: ['cro', 'ciso', 'coo', 'cfo'],
    typicalRevenue: '$3M–$30M ARR',
    painPoints: ['Enterprise security and compliance (SOC 2, ISO 27001)', 'Enterprise sales motion and procurement navigation', 'Customer success organization for enterprise accounts', 'Professional services organization build-out'],
  },
  {
    name: 'Regulated Financial Entities',
    slug: 'regulated-financial',
    description: 'Banks, broker-dealers, RIAs, and other SEC/FINRA regulated financial entities navigating compliance and growth.',
    topRoles: ['cfo', 'ciso', 'coo', 'chro'],
    typicalRevenue: '$1M–$500M',
    painPoints: ['SEC and FINRA examination readiness', 'AML/BSA program management', 'Reg T and capital adequacy', 'Data security and cybersecurity compliance'],
  },
  {
    name: 'Companies in CEO Transition',
    slug: 'ceo-transition',
    description: 'Organizations navigating a planned or unplanned change in chief executive leadership.',
    topRoles: ['ceo', 'coo', 'chro', 'cfo'],
    typicalRevenue: 'Any',
    painPoints: ['Leadership continuity during search', 'Board confidence and investor communication', 'Team morale and retention during uncertainty', 'Institutional knowledge preservation'],
  },
  {
    name: 'Companies Raising Debt Capital',
    slug: 'debt-capital',
    description: 'Businesses seeking asset-based lending, term loans, revolving credit facilities, or mezzanine financing.',
    topRoles: ['cfo', 'coo', 'ceo', 'chro'],
    typicalRevenue: '$5M+',
    painPoints: ['Lender-ready financial packages and covenant structures', 'Working capital optimization for borrowing base', 'Collateral documentation and due diligence', 'Bank relationship management'],
  },
  {
    name: 'Impact & ESG-Focused Companies',
    slug: 'esg-companies',
    description: 'Businesses with formal ESG commitments, impact measurement requirements, or B Corp certification goals.',
    topRoles: ['coo', 'cfo', 'chro', 'cmo'],
    typicalRevenue: 'Any',
    painPoints: ['ESG reporting framework selection (GRI, SASB, TCFD)', 'Scope 1/2/3 emissions measurement', 'Board-level ESG governance', 'Impact measurement and materiality assessment'],
  },
  {
    name: 'Founder-Led Companies Professionalization',
    slug: 'founder-led',
    description: 'Companies where the founder is transitioning from operator to owner, and needs institutional leadership to fill the vacuum.',
    topRoles: ['coo', 'cfo', 'chro', 'cmo'],
    typicalRevenue: '$3M–$50M',
    painPoints: ['Founder-to-professional management transition', 'Process formalization and accountability structures', 'Founder independence from daily operations', 'Leadership team capability uplift'],
  },
  {
    name: 'Rapidly Scaling Operators',
    slug: 'rapid-scale',
    description: 'Companies growing 50–200% year-over-year and whose operational infrastructure cannot keep pace with growth.',
    topRoles: ['coo', 'cfo', 'chro', 'cto'],
    typicalRevenue: '$5M–$100M',
    painPoints: ['Operational infrastructure scaling with revenue', 'Systems and technology modernization', 'Headcount planning and talent velocity', 'Unit economics protection as volume scales'],
  },
  {
    name: 'Emerging Market Entrants',
    slug: 'market-entrants',
    description: 'Companies entering a new geographic market, customer segment, or product category for the first time.',
    topRoles: ['cmo', 'cro', 'coo', 'cfo'],
    typicalRevenue: 'Any',
    painPoints: ['Market sizing and entry strategy', 'First sales and distribution relationships', 'Local regulatory and compliance requirements', 'Brand awareness in a new market'],
  },
  {
    name: 'Companies Preparing for Audit',
    slug: 'audit-prep',
    description: 'Businesses undergoing their first GAAP audit, PCAOB audit, or quality of earnings review for a transaction.',
    topRoles: ['cfo', 'coo', 'chro', 'ciso'],
    typicalRevenue: '$2M+',
    painPoints: ['First GAAP audit preparation', 'Internal controls documentation', 'Revenue recognition policy compliance', 'Related party transaction documentation'],
  },
]

export function getCompanyTypeBySlug(slug: string): CompanyType | undefined {
  return COMPANY_TYPES.find(c => c.slug === slug)
}

export function getAllCompanyTypeSlugs(): string[] {
  return COMPANY_TYPES.map(c => c.slug)
}
