export interface Competitor {
  name: string
  slug: string
  url: string
  model: string
  pricing: string
  deploymentTime: string
  ivyLeague: boolean
  usOnly: boolean
  flatRate: boolean
  cancellationPolicy: string
  strengths: string[]
  weaknesses: string[]
  bestFor: string
  verdictVsCrimson: string
}

export const COMPETITORS: Competitor[] = [
  {
    name: 'GoFractional',
    slug: 'gofractional',
    url: 'gofractional.com',
    model: 'Marketplace — 1,200+ pre-vetted executives set their own rates',
    pricing: '$3,000–$12,000/month; 20% conversion fee if hired full-time',
    deploymentTime: 'No SLA — exec-driven timeline',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Varies by executive',
    strengths: ['Large executive network', 'Strong SEO content', 'Rate flexibility', 'Broad role coverage'],
    weaknesses: ['No Ivy League guarantee', 'No deployment SLA', 'Marketplace quality variance', 'Hidden 20% conversion fee', 'Execs set own rates — no price predictability'],
    bestFor: 'Companies that want to browse a wide network and have flexibility on credentials',
    verdictVsCrimson: 'GoFractional has a larger talent pool but zero credential guarantees and no deployment SLA. If you need an Ivy League-educated executive in your seat within 48 hours at a predictable flat rate, The Crimson Bench delivers where GoFractional cannot.',
  },
  {
    name: 'Bolster',
    slug: 'bolster',
    url: 'bolsterhq.com',
    model: 'Marketplace covering fractional, interim, board, advisory, coaching',
    pricing: '$7,000–$20,000/month; ~20% marketplace markup',
    deploymentTime: '5–7 days to candidate shortlist',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Standard terms — varies',
    strengths: ['Strong VC/startup network', 'Board seat placements', 'Wide engagement type coverage', 'Mature platform'],
    weaknesses: ['Slower deployment (5–7 days vs. 48 hours)', 'No domestic guarantee', 'Marketplace markup adds cost', 'No Ivy League credential standard'],
    bestFor: 'VC-backed startups looking for board members and advisors in addition to fractional executives',
    verdictVsCrimson: 'Bolster is the best competitor for board seat placements. But for operational fractional executives deployed quickly with credential guarantees, The Crimson Bench is faster, more credentialed, and more cost-transparent.',
  },
  {
    name: 'Catalant',
    slug: 'catalant',
    url: 'catalant.com',
    model: 'Enterprise expert marketplace — 100,000+ consultants with MBB pedigree',
    pricing: '$150–$450/hr; 35–50% platform markup; enterprise annual contracts',
    deploymentTime: 'Project-scoped, not C-suite fractional focused',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Enterprise contract terms',
    strengths: ['Fortune 500 client relationships', 'MBB consulting pedigree', 'Large talent pool', 'Algorithmic matching with human concierge layer'],
    weaknesses: ['Expensive (35–50% markup)', 'Not focused on fractional C-suite', 'Enterprise-only pricing model', 'Opaque pricing', 'Smaller network than Crimson Bench (100K vs 150K+)'],
    bestFor: 'Fortune 500 companies running large-scale strategy consulting engagements — not fractional C-suite deployment',
    verdictVsCrimson: 'Catalant has 100,000+ consultants and charges a 35–50% markup. The Crimson Bench has 150,000+ global consultants — including scientists and engineers — at transparent flat-rate pricing, with Ivy League-educated C-suite executives deployable in 48 hours. We are larger, more credentialed, and more cost-transparent.',
  },
  {
    name: 'Fractionus',
    slug: 'fractionus',
    url: 'fractionus.com',
    model: 'Direct placement — no ongoing markup; 5,000+ executive network (US, AU, UK)',
    pricing: 'No markup on executive rate; transparent direct pricing',
    deploymentTime: '2–3 days to shortlist',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Direct negotiation with executive',
    strengths: ['No markup pricing model', 'Fast shortlisting (2–3 days)', 'Strong SEO and comparison content', 'Transparent direct model'],
    weaknesses: ['Not US-only (AU and UK talent included)', 'No Ivy League guarantee', 'Direct rate negotiation required', 'No published flat rates'],
    bestFor: 'Price-sensitive buyers who want transparent pricing and don\'t require specific credential guarantees',
    verdictVsCrimson: 'Fractionus offers transparent pricing but no Ivy League guarantee and no 48-hour deployment SLA. They also operate internationally — if you specifically need a US-based executive, Fractionus cannot guarantee domestic talent the way The Crimson Bench can.',
  },
  {
    name: 'Shiny',
    slug: 'shiny',
    url: 'useshiny.com',
    model: 'Startup-focused marketplace — CFO, CMO, CTO, COO, CHRO, CRO; 10% markup',
    pricing: '10% markup on executive compensation; no upfront fee',
    deploymentTime: 'Days to 15-candidate shortlist',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Varies by executive',
    strengths: ['Low 10% markup', 'Fast matching', 'No upfront fee', 'Startup-native experience', 'Up to 15 candidates per shortlist'],
    weaknesses: ['Quality variance across 15-candidate shortlist', 'No prestige guarantee', 'Wide range (2–40 hours/week) can be imprecise', 'No deployment SLA', 'No Ivy League or domestic guarantee'],
    bestFor: 'Early-stage startups that want to cast a wide net across many candidates at low cost',
    verdictVsCrimson: 'Shiny offers the widest candidate shortlist at the lowest markup, but quantity is not the same as quality. If you are raising a Series A or managing a PE-sponsored company where executive credential matters to investors and boards, The Crimson Bench\'s Ivy League guarantee carries the weight that Shiny\'s marketplace approach cannot.',
  },
  {
    name: 'Business Talent Group (BTG)',
    slug: 'business-talent-group',
    url: 'businesstalentgroup.com',
    model: 'Expert talent marketplace — focused on strategy, finance, and operations',
    pricing: '$150–$400/hr; marketplace markup 30–40%',
    deploymentTime: '5–10 days',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: 'Project-based terms',
    strengths: ['Strong in strategy and M&A due diligence', 'Large enterprise client base', 'Relationships with Big 3 consulting alumni'],
    weaknesses: ['High hourly rates plus markup', 'Not focused on ongoing fractional leadership', 'Better for project work than operational roles', 'Slower than Crimson Bench'],
    bestFor: 'PE firms and enterprise companies looking for ex-MBB experts for specific strategy projects',
    verdictVsCrimson: 'BTG is project-consulting focused, not fractional leadership. For an executive who will actually run your operations, manage your team, and be accountable to your board, The Crimson Bench is the right solution.',
  },
  {
    name: 'Chief',
    slug: 'chief',
    url: 'chief.com',
    model: 'Network and community for senior women executives — peer groups, coaching, and career development',
    pricing: '$5,900–$7,900/year membership',
    deploymentTime: 'N/A — membership model',
    ivyLeague: false,
    usOnly: true,
    flatRate: true,
    cancellationPolicy: 'Annual membership',
    strengths: ['Strong community and network effect', 'Peer group model for senior executives', 'Women-focused executive development'],
    weaknesses: ['Not a placement service', 'Does not deploy executives into companies', 'Membership is for the executive, not for the company needing one'],
    bestFor: 'Senior women executives looking for a peer network — not companies looking to hire fractional executives',
    verdictVsCrimson: 'Chief and The Crimson Bench serve completely different needs. Chief is for executives to develop themselves. The Crimson Bench deploys executives into companies. These are not competitors — but the distinction matters if you\'re comparing options as a company hiring fractional leadership.',
  },
  {
    name: 'Toptal',
    slug: 'toptal',
    url: 'toptal.com',
    model: 'Elite talent marketplace — engineers, designers, finance experts; top 3% claim',
    pricing: '$2,000–$5,000/week for finance and management; ~35% platform markup',
    deploymentTime: '48–72 hours',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: '14-day risk-free trial',
    strengths: ['Fast matching', 'Risk-free trial period', 'Strong engineering talent reputation', 'Wide skill coverage'],
    weaknesses: ['No Ivy League credential guarantee', 'Not US-only', 'Markup adds significant cost', 'Engineering-focused — C-suite depth is limited', 'No flat-rate pricing'],
    bestFor: 'Companies needing elite freelance engineers or finance analysts — less appropriate for ongoing C-suite leadership',
    verdictVsCrimson: 'Toptal\'s fastest deployment is 48–72 hours — comparable to The Crimson Bench. But Toptal carries a 35% markup, has no Ivy League guarantee, and is primarily engineering-focused. For C-suite leadership specifically, The Crimson Bench delivers more credentialed talent at a predictable flat rate.',
  },
  {
    name: 'Vistage',
    slug: 'vistage',
    url: 'vistage.com',
    model: 'CEO peer advisory groups with executive coaching — not fractional placement',
    pricing: '$1,500–$2,000/month membership fee',
    deploymentTime: 'N/A — peer group model',
    ivyLeague: false,
    usOnly: false,
    flatRate: true,
    cancellationPolicy: 'Annual contract, monthly billing',
    strengths: ['Large CEO peer group network', 'Established brand (60+ years)', 'Regular peer meetings plus private coaching', 'Local chapter availability across US'],
    weaknesses: ['Not executive placement', 'Does not deploy executives into companies', 'Coaching-focused, not operational leadership', 'Group format limits individual attention'],
    bestFor: 'CEOs who want a peer advisory network and private coaching — not companies that need a C-suite executive deployed',
    verdictVsCrimson: 'Vistage is peer coaching for the CEO — not a fractional executive deployment service. If you need an Ivy League-educated CFO running your financial close or a CRO building your enterprise pipeline, Vistage is not the answer. The Crimson Bench is.',
  },
  {
    name: 'FLG Partners',
    slug: 'flg-partners',
    url: 'flgpartners.com',
    model: 'Boutique fractional CFO firm — senior finance executives for Bay Area companies',
    pricing: '$10,000–$25,000/month',
    deploymentTime: '1–2 weeks',
    ivyLeague: false,
    usOnly: true,
    flatRate: false,
    cancellationPolicy: '30-day notice standard',
    strengths: ['Senior, experienced CFOs', 'Bay Area network and reputation', 'Strong reference network with VC firms'],
    weaknesses: ['CFO-only (single role focus)', 'Bay Area-centric', 'Higher price point', 'Limited national footprint', 'Not a full C-suite solution'],
    bestFor: 'Bay Area startups specifically looking for a senior fractional CFO with local VC relationships',
    verdictVsCrimson: 'FLG Partners is respected in the Bay Area CFO market but covers only one role in one geography. The Crimson Bench deploys all eight C-suite roles nationally with an Ivy League guarantee and 48-hour deployment — at competitive pricing.',
  },
  {
    name: 'CFO Hub',
    slug: 'cfo-hub',
    url: 'cfohub.com',
    model: 'Fractional and interim CFO firm — SMB to mid-market focus',
    pricing: '$5,000–$15,000/month',
    deploymentTime: '3–7 days',
    ivyLeague: false,
    usOnly: true,
    flatRate: false,
    cancellationPolicy: '30-day notice',
    strengths: ['CFO-focused depth', 'US-based talent', 'SMB-friendly pricing', 'Industry vertical expertise in some sectors'],
    weaknesses: ['CFO-only (no CTO, CMO, COO, etc.)', 'No Ivy League guarantee', 'Slower than Crimson Bench 48-hr SLA', 'Limited national brand'],
    bestFor: 'SMBs looking specifically for a fractional CFO at a mid-market price point',
    verdictVsCrimson: 'CFO Hub is a reasonable single-role option for companies that need only a fractional CFO. The Crimson Bench serves the same need with Ivy League-educated talent, 48-hour deployment, and the ability to expand to any other C-suite role without switching vendors.',
  },
  {
    name: 'G-Squared Partners',
    slug: 'g-squared-partners',
    url: 'gsquaredpartners.com',
    model: 'Fractional CFO firm for startups and scale-ups — finance-first positioning',
    pricing: '$8,000–$20,000/month',
    deploymentTime: '5–10 days',
    ivyLeague: false,
    usOnly: false,
    flatRate: false,
    cancellationPolicy: '30-day notice',
    strengths: ['Startup financial expertise', 'Fundraising track record', 'FP&A depth'],
    weaknesses: ['CFO-only', 'No Ivy League guarantee', 'Slower deployment', 'US and Canada — not exclusively domestic'],
    bestFor: 'VC-backed startups that need a finance-first fractional partner for fundraising and FP&A',
    verdictVsCrimson: 'G-Squared is a solid finance-first partner for startups. The Crimson Bench matches their CFO depth and adds the Ivy League guarantee, 48-hour deployment, and a full C-suite roster that G-Squared cannot provide.',
  },
  {
    name: 'Paro',
    slug: 'paro',
    url: 'paro.ai',
    model: 'AI-matched fractional finance and accounting professionals — CFO, controllers, analysts',
    pricing: '$150–$400/hr; varies by project scope',
    deploymentTime: 'Same-day to 72 hours (AI matching)',
    ivyLeague: false,
    usOnly: true,
    flatRate: false,
    cancellationPolicy: 'Project-based',
    strengths: ['AI-powered matching for speed', 'US-based network', 'Finance and accounting breadth (CFO to analyst)', 'Hourly flexibility'],
    weaknesses: ['AI matching does not guarantee credential quality', 'Hourly billing adds unpredictability', 'Finance-only (no CMO, CTO, etc.)', 'No Ivy League standard'],
    bestFor: 'Companies needing flexible finance and accounting support on an hourly basis — not strategic C-suite leadership',
    verdictVsCrimson: 'Paro uses AI to match finance professionals quickly, but AI matching is not the same as Ivy League vetting. For strategic CFO leadership — not just accounting support — The Crimson Bench brings credentials and accountability that Paro\'s AI model cannot replicate.',
  },
  {
    name: 'The CEO Project',
    slug: 'ceo-project',
    url: 'theceoproject.com',
    model: 'CEO peer advisory groups and executive coaching — private member organization',
    pricing: '$15,000–$30,000/year membership',
    deploymentTime: 'N/A — peer membership model',
    ivyLeague: false,
    usOnly: false,
    flatRate: true,
    cancellationPolicy: 'Annual membership',
    strengths: ['Highly curated peer groups', 'Private membership exclusivity', 'Senior executive peers'],
    weaknesses: ['Not executive placement — peer group only', 'Does not deploy executives', 'Membership is for the CEO, not for the company hiring'],
    bestFor: 'CEOs seeking a private peer community for senior leadership development',
    verdictVsCrimson: 'The CEO Project is a peer membership network, not a fractional executive deployment service. Companies hiring The Crimson Bench are getting an executive in the seat — not a group coaching session.',
  },
  {
    name: 'Countsy',
    slug: 'countsy',
    url: 'countsy.com',
    model: 'Outsourced CFO, controller, and HR for early-stage startups — bundled service model',
    pricing: '$3,000–$8,000/month bundled packages',
    deploymentTime: '3–5 business days',
    ivyLeague: false,
    usOnly: true,
    flatRate: true,
    cancellationPolicy: '30-day notice',
    strengths: ['Bundled CFO + HR + Controller for startups', 'US-based', 'Flat monthly pricing', 'Early-stage startup focus'],
    weaknesses: ['Not Ivy League credentialed', 'Limited to CFO and HR functions', 'Designed for early-stage — limited senior executive depth for growth-stage companies', 'No deployment SLA'],
    bestFor: 'Seed-stage startups that need basic outsourced finance and HR functions bundled together at low cost',
    verdictVsCrimson: 'Countsy serves a different market segment — very early-stage companies needing basic finance and HR infrastructure. The Crimson Bench deploys senior Ivy League executives for strategic and operational leadership. These are different needs at different stages.',
  },
]

export function getCompetitorBySlug(slug: string): Competitor | undefined {
  return COMPETITORS.find(c => c.slug === slug)
}

export function getAllCompetitorSlugs(): string[] {
  return COMPETITORS.map(c => c.slug)
}
