export interface Product {
  id: string
  num: number
  name: string
  shortName: string
  price: number | string
  priceSuffix?: string
  type: 'one-time' | 'monthly' | 'annual' | 'fixed-scope' | 'affiliate' | 'custom'
  tagline: string
  description: string
  includes: string[]
  upsellTo?: string
  stripeMode: 'payment' | 'subscription' | 'custom'
  isNew?: boolean
  isBestValue?: boolean
}

export const PRODUCTS: Product[] = [
  {
    id: 'industry-audit-report',
    num: 1,
    name: 'Industry Audit Report',
    shortName: 'Audit Report',
    price: 500,
    type: 'one-time',
    tagline: 'Written analysis. No call required.',
    description:
      'Submit your P&L, org chart, or operational overview and receive a written industry audit from an Ivy League-educated executive within 48 hours. No call required. Ideal for budget-constrained companies that need expert analysis before committing to a deeper engagement.',
    includes: [
      'Written executive analysis (4–6 pages)',
      'Identification of top 3–5 operational or financial risks',
      'Benchmark comparison to industry peers',
      'Recommended next steps with priority ranking',
    ],
    upsellTo: 'executive-diagnostic',
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'executive-diagnostic',
    num: 2,
    name: 'Executive Diagnostic',
    shortName: 'Diagnostic',
    price: 1500,
    type: 'one-time',
    tagline: '2-hour intensive audit. 3-page triage roadmap.',
    description:
      'Our flagship entry product. Submit your financial statements, org chart, or operational overview. Your dedicated Ivy League-educated executive runs a 2-hour intensive audit and delivers a 3-page triage roadmap within 48 hours. Fee is credited toward any retainer engagement started within 30 days.',
    includes: [
      '2-hour live executive working session',
      '3-page prioritized triage roadmap',
      'Identification of top 5 critical gaps',
      'Recommended engagement tier and scope',
      'Fee credited toward any retainer started within 30 days',
    ],
    upsellTo: 'advisory-retainer',
    stripeMode: 'payment',
  },
  {
    id: 'diagnostic-bundle',
    num: 3,
    name: 'Diagnostic Bundle — 3×',
    shortName: 'Bundle',
    price: 3750,
    type: 'one-time',
    tagline: 'Three diagnostics at a bundle rate.',
    description:
      'Three Executive Diagnostics at a bundle rate — saving $750 versus individual pricing. Ideal for private equity firms or family offices evaluating multiple portfolio companies, or for companies that want to audit multiple functions (finance, operations, and technology) simultaneously.',
    includes: [
      '3× Executive Diagnostic sessions (2 hours each)',
      '3× 3-page triage roadmaps',
      'Can be applied across different C-suite roles',
      'Can be applied across multiple portfolio companies',
      '$750 savings versus 3× individual pricing',
    ],
    upsellTo: 'scale-up-fractional',
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'advisory-retainer',
    num: 4,
    name: 'Advisory Retainer',
    shortName: 'Advisory',
    price: 4000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Strategic sounding board. Two calls per month.',
    description:
      'Two 90-minute advisory calls per month with your dedicated Ivy League-educated executive, plus asynchronous email and Slack access for high-level decision support between sessions. The strategic sounding board for executives who need a credentialed thought partner without a deeper operational commitment.',
    includes: [
      '2× 90-minute advisory calls per month',
      'Async email and Slack access between sessions',
      'Written summary and action items after each session',
      '14-day no-cause cancellation',
      'Dedicated Ivy League-educated executive',
    ],
    upsellTo: 'scale-up-fractional',
    stripeMode: 'subscription',
  },
  {
    id: 'scale-up-fractional',
    num: 5,
    name: 'Scale-Up Fractional — 1 Day/Week',
    shortName: 'Scale-Up',
    price: 7500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Dedicated C-suite oversight. One day per week.',
    description:
      'The most popular fractional engagement tier. Your executive is in your operations one full day per week — owning KPI tracking, running team meetings, managing key vendor relationships, and driving weekly execution. The equivalent of a $180,000/year hire at a fraction of the cost.',
    includes: [
      '1 full day per week of dedicated executive time (in-person or remote)',
      'Weekly team meeting facilitation',
      'KPI tracking and dashboard ownership',
      'Async availability throughout the week',
      '14-day no-cause cancellation',
    ],
    upsellTo: 'growth-fractional',
    stripeMode: 'subscription',
    isBestValue: true,
  },
  {
    id: 'growth-fractional',
    num: 6,
    name: 'Growth Fractional — 2 Days/Week',
    shortName: 'Growth',
    price: 12500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Intensive oversight. Two days per week.',
    description:
      'Intensive fractional engagement for companies in active growth phases. Your executive is present two full days per week — covering board reporting, team management, cross-departmental execution, and active hiring oversight. Equivalent to $300,000/year full-time at 40% of the cost.',
    includes: [
      '2 full days per week of dedicated executive time',
      'Board and investor reporting ownership',
      'Active team management and hiring oversight',
      'Cross-departmental execution and accountability',
      'Async availability throughout the week',
      '14-day no-cause cancellation',
    ],
    upsellTo: 'embedded-executive',
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'embedded-executive',
    num: 7,
    name: 'Embedded Executive — 3+ Days/Week',
    shortName: 'Embedded',
    price: 18500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Near-full-time. In the seat.',
    description:
      'Near-full-time executive presence. Your Crimson Bench executive operates as effectively your C-suite leader — owning hiring decisions, investor relations, full P&L accountability, and operational oversight. Equivalent value to a $400,000/year executive package at approximately 55% of the cost.',
    includes: [
      '3+ full days per week of dedicated executive time',
      'Full P&L and functional accountability',
      'Hiring decision authority (agreed scope)',
      'Direct investor and board-level representation',
      'All team meetings and operational reviews',
      '14-day no-cause cancellation',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'emergency-role-transition',
    num: 8,
    name: 'Emergency Role Transition Pack',
    shortName: 'Emergency Pack',
    price: 8500,
    type: 'fixed-scope',
    tagline: '30-day rapid deployment. Clear deliverable.',
    description:
      "Fixed-scope 30-day emergency engagement designed for urgent leadership gaps. A defined deliverable — stabilize a leadership void, close a board reporting cycle, navigate a critical hire window, or manage a regulatory deadline — with the Crimson Bench's 48-hour deployment SLA.",
    includes: [
      '30-day fixed engagement, deployed within 48 hours',
      'Defined deliverable agreed at engagement start',
      'Up to 3 days per week of executive time',
      'End-of-engagement transition document',
      'Option to convert to ongoing retainer at conclusion',
    ],
    upsellTo: 'scale-up-fractional',
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'board-advisory-seat',
    num: 9,
    name: 'Board Advisory Seat',
    shortName: 'Board Advisory',
    price: 2500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Independent director-level strategic counsel.',
    description:
      'An Ivy League-educated Crimson Bench executive joins your board or advisory board as an independent director or strategic advisor. Quarterly board meetings plus availability for ad hoc strategic counsel between sessions. Adds institutional credibility to your governance structure.',
    includes: [
      'Quarterly board meeting attendance',
      'Ad hoc strategic counsel between board meetings',
      'Written perspectives on major strategic decisions',
      'Introductions to relevant network contacts on request',
      'Annual board calendar and governance calendar review',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'succession-planning-assessment',
    num: 10,
    name: 'Executive Succession Planning Assessment',
    shortName: 'Succession Assessment',
    price: 2500,
    type: 'one-time',
    tagline: 'Leadership bench strength, mapped and ranked.',
    description:
      "A formal written assessment of your current leadership team's succession readiness. Identifies internal candidates for each C-suite role, gaps in bench strength, development plans for high-potential leaders, and external search criteria for roles with no internal successor. Delivered in 5–7 business days.",
    includes: [
      'Assessment of internal succession readiness for each C-suite role',
      'Scoring rubric for internal candidates',
      'Gap analysis and development plan recommendations',
      'External search criteria for roles with no viable internal successor',
      'Written report (8–12 pages) plus executive briefing call',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'leadership-team-audit',
    num: 11,
    name: 'Leadership Team Audit',
    shortName: 'Team Audit',
    price: 1200,
    type: 'one-time',
    tagline: '2-hour session. Team structure, comp, and gaps.',
    description:
      "A focused 2-hour session auditing your leadership team's structure, compensation benchmarks, and performance gaps. Distinct from the Executive Diagnostic (which audits the business) — this audits the team running it. Produces a written report with specific team design and compensation recommendations.",
    includes: [
      '2-hour leadership team audit session',
      'Compensation benchmark analysis vs. market data',
      'Org design assessment and gap identification',
      'Individual performance gap observations',
      'Written recommendations report',
    ],
    upsellTo: 'advisory-retainer',
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'investor-readiness-package',
    num: 12,
    name: 'Investor Readiness Package',
    shortName: 'Investor Readiness',
    price: 5000,
    type: 'one-time',
    tagline: 'CFO-led. Series A/B fundraise preparation.',
    description:
      'A structured package for companies preparing for a Series A or B fundraise. Led by a Crimson Bench CFO with capital markets experience, this engagement prepares your financials, data room, and investor narrative to withstand institutional due diligence. Average engagement window is 3–4 weeks.',
    includes: [
      'Financial model review and institutional-quality cleanup',
      'Data room structure and documentation checklist',
      'Investor Q&A preparation and mock diligence session',
      'Key metrics dashboard aligned to Series A/B investor expectations',
      'Cap table review and pre-money valuation analysis',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'permanent-executive-search',
    num: 13,
    name: 'Permanent Executive Search',
    shortName: 'Perm Search',
    price: '25% of first-year comp',
    type: 'custom',
    tagline: 'Full-time C-suite sourced from our bench and network.',
    description:
      "When a permanent C-suite hire is the right answer, The Crimson Bench sources and vets candidates from our extended network of Ivy League-educated operators. We charge 25% of first-year compensation — payable upon successful hire — with a 90-day replacement guarantee if the hire doesn't work out.",
    includes: [
      'Role specification and market positioning',
      'Candidate sourcing from Crimson Bench extended network',
      'Resume screening and first-round interviews',
      'Structured reference checks',
      '90-day replacement guarantee',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'strategic-planning-sprint',
    num: 14,
    name: 'Strategic Planning Sprint',
    shortName: 'Strategy Sprint',
    price: 4500,
    type: 'fixed-scope',
    tagline: '2-week facilitated planning. 12-month roadmap output.',
    description:
      'A structured 2-week facilitated strategic planning engagement. Your Crimson Bench executive leads your leadership team through a disciplined process — market analysis, competitive positioning, resource prioritization — and produces a 12-month strategic plan with quarterly milestones and financial targets.',
    includes: [
      '2-week facilitated engagement (2–3 working sessions)',
      'Market and competitive landscape analysis',
      'Resource allocation and prioritization framework',
      '12-month strategic plan document',
      'Quarterly milestone and OKR structure',
      'Financial target modeling',
    ],
    upsellTo: 'advisory-retainer',
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'crisis-intervention-retainer',
    num: 15,
    name: 'Crisis Intervention Retainer',
    shortName: 'Crisis Retainer',
    price: 15000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: '24-hour response SLA. Distress-grade support.',
    description:
      'Priority access retainer for companies in acute distress — cash flow crises, sudden leadership departures, regulatory emergencies, or activist investor situations. Includes a 24-hour executive response SLA and up to 4 days per week of dedicated executive time. Structured for the worst 90 days your company will ever face.',
    includes: [
      'Up to 4 days per week of dedicated executive time',
      '24-hour response SLA for critical escalations',
      'Board and investor crisis communication support',
      'Cash preservation and emergency capital planning',
      'Leadership stabilization and team communication',
      '14-day no-cause cancellation',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'bench-membership',
    num: 16,
    name: 'The Bench Membership',
    shortName: 'Membership',
    price: 1000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Self-serve access to the full bench directory.',
    description:
      'Monthly membership providing self-serve access to the full Crimson Bench executive directory. Book 1-hour consultation sessions with any executive on the bench at $500/session (credited against membership). Ideal for companies that need occasional expert access without committing to a full retainer.',
    includes: [
      'Full access to the Crimson Bench executive directory',
      '1 complimentary 1-hour consultation per month',
      'Additional sessions at $500 each (member pricing)',
      'Priority access to new bench additions',
      'Monthly Executive Intelligence newsletter',
    ],
    upsellTo: 'advisory-retainer',
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'nonprofit-fractional',
    num: 17,
    name: 'Nonprofit Fractional Tier',
    shortName: 'Nonprofit',
    price: 3500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Institutional leadership at a mission-aligned rate.',
    description:
      'A dedicated fractional engagement tier for 501(c)(3) nonprofit organizations. Provides the same Ivy League-educated executive talent and 48-hour deployment SLA at a mission-aligned rate — because great governance and strategic leadership should not be reserved only for for-profit organizations.',
    includes: [
      '1 day per week of dedicated executive time',
      'Board and donor reporting support',
      'Grant-aligned financial and operational reporting',
      'Org design for nonprofit-specific structures',
      '14-day no-cause cancellation',
      'Verification of 501(c)(3) status required',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'ma-due-diligence-assessment',
    num: 18,
    name: 'M&A Due Diligence Executive Assessment',
    shortName: 'M&A Assessment',
    price: 2000,
    type: 'one-time',
    tagline: '3rd-party C-suite capability assessment for acquirers.',
    description:
      "A third-party executive capability assessment for private equity investors, strategic acquirers, or lenders who need an independent view of a target company's leadership team. Crimson Bench evaluates the C-suite's capability, completeness, and succession risk — and delivers a written assessment within 5 business days.",
    includes: [
      'Executive interviews with key C-suite members',
      'Capability assessment against industry benchmarks',
      'Leadership risk and succession gap analysis',
      'Written assessment report (6–10 pages)',
      'Recommended actions for post-close talent integration',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'corporate-leadership-workshop',
    num: 19,
    name: 'Corporate Leadership Workshop',
    shortName: 'Workshop',
    price: '3,000–8,000',
    type: 'fixed-scope',
    tagline: 'Half-day C-suite development session.',
    description:
      'A facilitated half-day leadership development workshop delivered by a Crimson Bench executive. Topics include: capital allocation decision-making, strategic planning frameworks, board communication best practices, or crisis leadership. Designed for corporate leadership teams, PE portfolio company management teams, or executive onboarding programs.',
    includes: [
      '3.5-hour facilitated workshop session (in-person or virtual)',
      'Custom curriculum built for your team and context',
      'Pre-workshop participant survey and preparation guide',
      'Post-workshop action plan and resource package',
      'Follow-up 30-minute debrief call included',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'annual-prepay',
    num: 20,
    name: 'Annual Prepay — 2 Months Free',
    shortName: 'Annual',
    price: 'Tier × 10',
    type: 'annual',
    tagline: '12 months of access for the price of 10.',
    description:
      'Prepay any monthly retainer tier for 12 months and receive 2 months free — an effective 17% discount. Locking in an annual engagement also guarantees priority access to your dedicated executive and eliminates billing variability. Available for Advisory Retainer through Embedded Executive tiers.',
    includes: [
      '12 months of access for 10 months of billing',
      '17% effective discount on any monthly tier',
      'Priority scheduling and executive access',
      'Annual strategic review session (bonus session)',
      'Locked-in rate protection for 12 months',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'pe-corporate-package',
    num: 21,
    name: 'PE / Family Office Corporate Package',
    shortName: 'Corporate',
    price: '30,000+',
    priceSuffix: '/month',
    type: 'custom',
    tagline: 'Multi-executive deployment across portfolio companies.',
    description:
      'A custom multi-executive engagement for private equity firms, family offices, and holding companies that need C-suite leadership deployed across multiple portfolio companies simultaneously. Includes a dedicated partner contact, priority deployment access, and consolidated billing with volume pricing.',
    includes: [
      'Multi-executive deployment across portfolio companies',
      'Dedicated Crimson Bench partner contact',
      'Priority 48-hour deployment across all portfolio engagements',
      'Consolidated billing and reporting',
      'Quarterly portfolio-level executive review',
      'Custom volume pricing',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'referral-partner-program',
    num: 22,
    name: 'Referral Partner Program',
    shortName: 'Referral',
    price: '10% rev share',
    type: 'affiliate',
    tagline: '12-month revenue share on referred engagements.',
    description:
      'Earn 10% revenue share for the first 12 months of any client engagement you refer to The Crimson Bench. Designed for M&A advisors, investment bankers, accountants, attorneys, and other professional services firms whose clients regularly face C-suite leadership gaps. Paid monthly, tracked transparently.',
    includes: [
      '10% revenue share for first 12 months per referred client',
      'Monthly payments via ACH or wire',
      'Dedicated partner dashboard and referral tracking',
      'Crimson Bench co-marketing materials for partner use',
      'Priority introductions to our executive bench for partner events',
    ],
    stripeMode: 'custom',
    isNew: true,
  },

  // ─── PLACEMENT & SEARCH FEES ─────────────────────────────────────────────

  {
    id: 'permanent-executive-search',
    num: 23,
    name: 'Permanent Executive Search',
    shortName: 'Perm Search',
    price: '35,000–75,000',
    type: 'fixed-scope',
    tagline: 'Full-time C-suite placement from the 25K bench.',
    description:
      'When you need a permanent hire, not a fractional one. Crimson Bench draws on our 25,000-executive network to identify, vet, and present permanent C-suite candidates. Success-based pricing with a 6-month guarantee — if the hire leaves within 6 months, we re-search at no additional fee.',
    includes: [
      'Full-time CEO, CFO, CTO, COO, CRO, CMO, CHRO, or CISO placement',
      'Access to 25,000+ Ivy League-educated executive network',
      'Structured interview process and reference verification',
      'Compensation benchmarking and offer structuring',
      '6-month replacement guarantee',
      'Onboarding support and 90-day check-in',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'board-director-placement',
    num: 24,
    name: 'Board Director Placement',
    shortName: 'Board Placement',
    price: '25,000–55,000',
    type: 'fixed-scope',
    tagline: 'Independent directors from our 25K network.',
    description:
      'Find and place independent board directors who bring genuine domain expertise — not just a prestigious name. Our board director search draws on executives who have served on public and private company boards, with expertise matched to your specific stage, industry, and governance needs.',
    includes: [
      'Board skills matrix assessment and gap analysis',
      'Search across 25,000+ executive network',
      'Candidate screening for independence, expertise, and fit',
      'Background verification and reference checks',
      'Director compensation benchmarking',
      '12-month relationship support',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'advisor-placement',
    num: 25,
    name: 'Advisor Placement & Structuring',
    shortName: 'Advisor Placement',
    price: '8,000–18,000',
    type: 'fixed-scope',
    tagline: 'Formal advisory agreements with equity and cash terms.',
    description:
      'Identify and place strategic advisors — domain experts, former operators, or industry connectors — with equity compensation, cash retainers, or hybrid structures. Crimson Bench matches your company to advisors from our network based on your specific growth stage and strategic needs.',
    includes: [
      'Advisor scope definition and compensation structuring',
      'Search across 25,000+ executive and advisor network',
      'Advisory agreement templates (equity, cash, or hybrid)',
      'Onboarding framework and engagement cadence design',
      'Up to 3 advisor placements per engagement',
    ],
    stripeMode: 'payment',
    isNew: true,
  },

  // ─── ADVISORY & ASSESSMENT SERVICES ──────────────────────────────────────

  {
    id: 'management-due-diligence',
    num: 26,
    name: 'Management Due Diligence Report',
    shortName: 'Mgmt DD',
    price: '8,000–25,000',
    type: 'fixed-scope',
    tagline: 'PE/VC management team assessment pre-investment.',
    description:
      "An independent management team assessment for private equity investors, venture capital firms, and strategic acquirers evaluating a target company. Crimson Bench executives assess the leadership team's capability, completeness, compensation alignment, and succession depth — and deliver a written report within 10 business days.",
    includes: [
      'Executive interviews with all C-suite members',
      'Capability and experience benchmarking vs. industry standards',
      'Organizational completeness assessment (gaps vs. stage)',
      'Compensation alignment and retention risk analysis',
      'Written Management DD Report (10–15 pages)',
      'Q&A session with deal team',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'acquisition-readiness-assessment',
    num: 27,
    name: 'Acquisition Readiness Assessment',
    shortName: 'M&A Readiness',
    price: '15,000–35,000',
    type: 'fixed-scope',
    tagline: 'Pre-sale prep to maximize your exit valuation.',
    description:
      "A structured assessment that prepares your company for an M&A process. Crimson Bench executives identify the leadership gaps, operational weaknesses, and financial presentation issues that buyers will scrutinize in diligence — and deliver a remediation roadmap to maximize your exit valuation before going to market.",
    includes: [
      'Leadership team capability assessment and gap analysis',
      'Financial presentation and quality of earnings pre-review',
      'Operational scalability and systems assessment',
      'Buyer perspective simulation (what will PE/strategic buyers find?)',
      'Written Acquisition Readiness Report with remediation roadmap',
      '30-day follow-on support during remediation',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'portfolio-company-health-audit',
    num: 28,
    name: 'Portfolio Company Health Audit',
    shortName: 'Portfolio Audit',
    price: '10,000–30,000',
    type: 'fixed-scope',
    tagline: "Annual health check on PE portfolio company leadership and operations.",
    description:
      "An annual diagnostic for private equity operating partners who need an independent view of a portfolio company's leadership effectiveness, operational performance, and value creation plan execution. Delivered by a Crimson Bench partner-level executive with PE operating experience.",
    includes: [
      'Leadership effectiveness assessment (all C-suite)',
      'Value creation plan progress review',
      'Operational KPI benchmarking vs. peer portfolio',
      'Board meeting preparation and governance review',
      'Written Portfolio Health Report (8–12 pages)',
      'Presentation to PE firm and management team',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'technology-stack-audit',
    num: 29,
    name: 'Technology Stack Audit',
    shortName: 'Tech Audit',
    price: '5,000–12,000',
    type: 'fixed-scope',
    tagline: 'CTO-led review of your tech stack, debt, and roadmap.',
    description:
      'A 30-day CTO-led assessment of your technology architecture, engineering team structure, technical debt, and product roadmap alignment. Crimson Bench deploys a senior CTO or VP of Engineering to assess your stack against your growth stage and deliver a prioritized remediation and investment roadmap.',
    includes: [
      'Architecture review and technical debt assessment',
      'Engineering team capability and org structure review',
      'Build vs. buy vs. partner analysis for key tech decisions',
      'Security and compliance gap assessment',
      'Product-engineering alignment review',
      'Written Technology Assessment Report with investment roadmap',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'go-to-market-playbook',
    num: 30,
    name: 'Go-to-Market Playbook',
    shortName: 'GTM Playbook',
    price: '8,000–20,000',
    type: 'fixed-scope',
    tagline: 'CMO-led 60-day GTM strategy and execution plan.',
    description:
      'A CMO-led 60-day engagement to define or reset your go-to-market strategy. Includes ICP definition, channel prioritization, positioning and messaging, demand generation framework, and a 12-month execution calendar — delivered as a written playbook your team can execute without further consulting support.',
    includes: [
      'ICP and buyer persona definition',
      'Competitive positioning and messaging framework',
      'Channel prioritization and budget allocation model',
      'Demand generation and content strategy',
      '12-month GTM calendar with milestone targets',
      'Written Go-to-Market Playbook (20–30 pages)',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'revenue-operations-audit',
    num: 31,
    name: 'Revenue Operations Audit',
    shortName: 'RevOps Audit',
    price: '5,000–15,000',
    type: 'fixed-scope',
    tagline: 'CRO-led assessment of your entire revenue engine.',
    description:
      'A CRO-led assessment of your sales pipeline, revenue operations, CRM hygiene, quota structures, and revenue forecasting process. Crimson Bench identifies the highest-leverage fixes to your revenue engine and delivers a prioritized remediation plan with ROI projections.',
    includes: [
      'Sales pipeline and conversion rate analysis',
      'CRM data quality and process audit',
      'Sales compensation and quota structure review',
      'Revenue forecasting accuracy assessment',
      'Sales and marketing alignment review',
      'Written Revenue Operations Assessment with quick-win roadmap',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'people-strategy-assessment',
    num: 32,
    name: 'People Strategy Assessment',
    shortName: 'People Assessment',
    price: '6,000–16,000',
    type: 'fixed-scope',
    tagline: 'CHRO-led talent, culture, and compensation review.',
    description:
      'A CHRO-led assessment of your human capital strategy — compensation benchmarking, org design, retention risk, culture health, and recruiting capabilities. Crimson Bench delivers a People Strategy Report and implementation roadmap tailored to your growth stage and headcount trajectory.',
    includes: [
      'Compensation benchmarking vs. market data',
      'Organizational design and reporting structure review',
      'Retention risk and flight risk identification',
      'Culture health assessment (anonymous survey)',
      'Recruiting process and pipeline review',
      'Written People Strategy Report with 90-day action plan',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'capital-structure-advisory',
    num: 33,
    name: 'Capital Structure Advisory',
    shortName: 'Cap Structure',
    price: '15,000–45,000',
    type: 'fixed-scope',
    tagline: 'CFO-led analysis of your ideal debt and equity mix.',
    description:
      'A CFO-led engagement to assess and optimize your capital structure — evaluating the right mix of debt, equity, and working capital facilities given your growth trajectory, risk profile, and exit objectives. Includes lender and investor market intelligence from Crimson Bench deal experience.',
    includes: [
      'Current capital structure assessment vs. peers',
      'Debt capacity and leverage analysis',
      'Equity vs. debt trade-off modeling',
      'Working capital and liquidity management review',
      'Lender and investor market intelligence briefing',
      'Written Capital Structure Recommendation Report',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'crisis-management-retainer',
    num: 34,
    name: 'Crisis Management Retainer',
    shortName: 'Crisis Retainer',
    price: 8000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'On-call C-suite response for board-level crises.',
    description:
      'A standing retainer for access to a senior Crimson Bench executive on an on-call basis for board-level crises: leadership departures, regulatory investigations, customer or investor crises, activist shareholder situations, or executive misconduct. Response within 4 hours. Cancel at any time.',
    includes: [
      'On-call access to senior Crimson Bench executive',
      '4-hour response SLA for crisis escalations',
      'Monthly 1-hour preparedness briefing',
      'Crisis communication and board preparation support',
      'Network access to legal, PR, and regulatory specialists',
      '14-day cancellation policy',
    ],
    upsellTo: 'embedded-executive',
    stripeMode: 'subscription',
    isNew: true,
  },

  // ─── SUBSCRIPTIONS & NETWORK ACCESS ──────────────────────────────────────

  {
    id: 'executive-coaching',
    num: 35,
    name: 'Executive Coaching',
    shortName: 'Coaching',
    price: 1200,
    type: 'one-time',
    tagline: '90-minute 1:1 coaching session with a C-suite veteran.',
    description:
      'A 90-minute 1:1 coaching session with a Crimson Bench Ivy League-educated executive. Topics include: leadership presence, board communication, investor relations, managing difficult executives, personal career strategy, or any C-suite challenge you face. Purchase individually or as a package of 6 sessions.',
    includes: [
      '90-minute private coaching session',
      'Pre-session questionnaire and context review',
      'Session recording and notes delivered within 24 hours',
      'Resource recommendations and follow-up reading',
      'Option to book follow-on sessions at same executive',
    ],
    upsellTo: 'advisory-retainer',
    stripeMode: 'payment',
    isNew: true,
    isBestValue: false,
  },
  {
    id: 'talent-access-subscription',
    num: 36,
    name: 'PE/VC Talent Access Subscription',
    shortName: 'Talent Access',
    price: 3500,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Search the 25K bench. On demand.',
    description:
      'A monthly subscription for private equity firms, family offices, and venture capital firms that gives unlimited search access to The Crimson Bench executive network. Browse executive profiles, request introductions, and deploy fractional leadership across your portfolio at discounted rates.',
    includes: [
      'Unlimited executive profile search and access',
      'Priority introductions to matched executives',
      '15% discount on all fractional engagement fees',
      'Dedicated relationship manager',
      'Monthly bench briefing (new executive intakes)',
      'Portfolio company co-investment on executive costs',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'executive-network-membership',
    num: 37,
    name: 'Executive Network Membership',
    shortName: 'Network Membership',
    price: 1200,
    priceSuffix: '/year',
    type: 'annual',
    tagline: 'Join the 25K bench. Access deal flow and peers.',
    description:
      'For C-suite executives who want to join The Crimson Bench network as available fractional talent. Members gain access to exclusive deal flow, peer executive community, thought leadership content, and priority consideration for incoming fractional mandates. Annual membership with rolling renewal.',
    includes: [
      'Verified profile on the Crimson Bench bench',
      'Priority consideration for incoming mandates',
      'Access to exclusive executive peer community',
      'Monthly deal flow briefing and mandate pipeline',
      'Thought leadership publication opportunities',
      'Discounted coaching and certification programs',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'succession-planning-program',
    num: 38,
    name: 'Succession Planning Program',
    shortName: 'Succession',
    price: '15,000–40,000',
    type: 'fixed-scope',
    tagline: '6-month structured succession program for CEO/board.',
    description:
      'A structured 6-month program to design and implement a CEO or key executive succession plan. Crimson Bench works with the board and outgoing CEO to identify internal candidates, assess external options, and create a transition plan that protects business continuity and investor relationships.',
    includes: [
      'Internal succession candidate assessment',
      'External market scan for succession alternatives',
      'Succession timeline and milestone design',
      'Transition communication strategy',
      'Interim leadership coverage during transition',
      'Post-succession 90-day support',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: '100-day-onboarding-program',
    num: 39,
    name: '100-Day Executive Onboarding Program',
    shortName: '100-Day Plan',
    price: '12,000',
    type: 'fixed-scope',
    tagline: 'Structured onboarding for newly placed C-suite executives.',
    description:
      "A structured 100-day onboarding program for newly hired or newly deployed C-suite executives. Crimson Bench works with the incoming executive and board to design a 100-day listening, assessment, and early-win plan — reducing time-to-impact and minimizing the risk of a failed executive placement.",
    includes: [
      '100-day milestone plan co-designed with executive and board',
      'Weekly coaching and debrief sessions',
      'Stakeholder mapping and relationship management guide',
      'Early win identification and prioritization framework',
      'Mid-point (Day 50) board presentation preparation',
      'Day 100 assessment and 12-month plan development',
    ],
    stripeMode: 'payment',
    isNew: true,
  },

  // ─── DIGITAL PRODUCTS & EDUCATION ────────────────────────────────────────

  {
    id: 'fractional-executive-certification',
    num: 40,
    name: 'Fractional Executive Certification',
    shortName: 'Certification',
    price: 2500,
    type: 'one-time',
    tagline: 'Become Crimson Bench Certified. Stand out on the bench.',
    description:
      'A structured certification program for C-suite executives who want to build and monetize a fractional executive practice. Includes a 3-module curriculum (client acquisition, engagement structuring, and board communication), a live assessment, and a Crimson Bench certification credential upon completion.',
    includes: [
      '3-module online curriculum (10 hours total)',
      'Live assessment with Crimson Bench senior executive',
      'Crimson Bench Certified Fractional Executive credential',
      'Verified badge for LinkedIn and marketing materials',
      'Priority consideration for Crimson Bench bench placement',
      '1-year access to curriculum updates',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'executive-masterclass',
    num: 41,
    name: 'Executive Masterclass Series',
    shortName: 'Masterclass',
    price: 1500,
    type: 'one-time',
    tagline: '6-module video series on C-suite strategy and execution.',
    description:
      'A 6-module video masterclass series taught by Crimson Bench executives — Ivy League MBAs and former C-suite leaders with operating experience at companies from $5M to $5B. Modules cover: board communication, capital raising, scaling operations, managing PE relationships, building a high-performance leadership team, and navigating CEO transitions.',
    includes: [
      '6 video modules (90 minutes each)',
      'Downloadable frameworks and templates for each module',
      'Private online community with cohort peers',
      'Q&A sessions with Crimson Bench executives',
      'Lifetime access to course content',
      'Certificate of completion',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'market-compensation-report',
    num: 42,
    name: 'C-Suite Compensation & Market Data Report',
    shortName: 'Comp Report',
    price: 1000,
    type: 'one-time',
    tagline: 'Real compensation data from 25K+ executive placements.',
    description:
      'A data product built from Crimson Bench compensation data across 25,000+ executive placements. Includes cash, equity, and total compensation benchmarks by role, company stage, industry, and geography — the most comprehensive private-company C-suite compensation dataset available outside of institutional data providers.',
    includes: [
      'Compensation benchmarks for all 8 C-suite roles',
      'Segmented by company stage, revenue, and industry',
      'Geographic adjustment factors for major markets',
      'Fractional vs. full-time vs. interim comparison tables',
      'Equity benchmarking (options, RSUs, phantom equity)',
      'Annual refresh with latest market data',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'executive-playbook-bundle',
    num: 43,
    name: 'Executive Playbook Template Bundle',
    shortName: 'Playbook Bundle',
    price: 350,
    type: 'one-time',
    tagline: '20+ board-ready templates and frameworks.',
    description:
      'A library of 20+ battle-tested executive templates used by Crimson Bench executives across 24,000+ mandates. Includes 100-day plan templates, board deck frameworks, financial review templates, OKR-setting guides, org design worksheets, and M&A integration checklists. Download and use immediately.',
    includes: [
      '100-Day Executive Onboarding Plan template',
      'Board of Directors presentation framework',
      'Monthly management reporting package template',
      'OKR-setting and strategic planning workshop guide',
      'Organizational design and RACI matrix templates',
      '10 additional templates across finance, ops, HR, and tech',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'board-readiness-assessment',
    num: 44,
    name: 'Board Readiness Assessment',
    shortName: 'Board Readiness',
    price: 3500,
    type: 'one-time',
    tagline: 'Are you board-ready? Find out in 5 business days.',
    description:
      'A structured assessment for C-suite executives who want to join a public or private company board. Crimson Bench evaluates your domain expertise, governance knowledge, time availability, and positioning — and delivers a Board Readiness Report with a specific action plan to achieve your first board seat within 12–24 months.',
    includes: [
      '90-minute Board Readiness interview with Crimson Bench executive',
      'Expertise and experience gap analysis vs. board needs',
      'Positioning and personal brand assessment',
      'Network mapping for board access',
      'Written Board Readiness Report (6–8 pages)',
      '3-month follow-on support and accountability check-in',
    ],
    stripeMode: 'payment',
    isNew: true,
  },

  // ─── EVENTS & PARTNER PROGRAMS ────────────────────────────────────────────

  {
    id: 'speaker-bureau',
    num: 45,
    name: 'Speaker Bureau',
    shortName: 'Speaker',
    price: 'Commission-based',
    type: 'custom',
    tagline: 'Book a Crimson Bench executive for your event.',
    description:
      'Book a Crimson Bench executive to speak at your conference, corporate event, investor meeting, or podcast. Our bench includes former public company CEOs, PE operating partners, and C-suite executives with deep expertise across technology, finance, operations, and organizational leadership. Speaking fees vary by executive and format.',
    includes: [
      'Speaker matching based on topic and audience',
      'Pre-event briefing and content customization',
      'Speaker bio, headshot, and topic abstract package',
      'Post-event Q&A and executive availability',
      'Option to include book signing, workshop, or breakout session',
      'Flexible formats: keynote, panel, fireside chat, workshop',
    ],
    stripeMode: 'custom',
    isNew: true,
  },
  {
    id: 'annual-summit-pass',
    num: 46,
    name: 'Annual Executive Summit Pass',
    shortName: 'Summit Pass',
    price: 3000,
    type: 'one-time',
    tagline: 'One day. 200 executives. Crimson Bench New York.',
    description:
      'The Crimson Bench Annual Executive Summit brings together 200 portfolio company executives, PE operating partners, investors, and C-suite leaders for a full-day program of keynotes, workshops, and curated networking. Held annually in New York City. Passes are limited to maintain quality of dialogue.',
    includes: [
      'Full-day access to keynotes and breakout sessions',
      'Pre-matched executive networking (algorithmic pairing)',
      'Crimson Bench Bench Showcase (meet available executives)',
      'Lunch and evening cocktail reception',
      'Access to all session recordings post-event',
      'Summit attendee directory with contact opt-in',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'white-label-partner-license',
    num: 47,
    name: 'White Label Partner License',
    shortName: 'White Label',
    price: 'Custom',
    type: 'custom',
    tagline: 'Deploy the 25K bench under your brand.',
    description:
      'License The Crimson Bench talent platform and executive network to deploy under your own brand. Designed for consulting firms, accounting practices, investment banks, and law firms that want to offer fractional executive services to their clients without building their own talent infrastructure. Revenue sharing, white label technology, and co-branded delivery.',
    includes: [
      'Access to 25,000+ executive network for white-label deployment',
      'Co-branded engagement materials and delivery framework',
      'Dedicated partner success manager',
      'Partner portal with pipeline tracking and billing',
      'Training program for partner client-facing teams',
      'Revenue share structure with quarterly settlements',
    ],
    stripeMode: 'custom',
    isNew: true,
  },

  // ─── RESEARCH & INTELLIGENCE SERVICES ────────────────────────────────────

  {
    id: 'deep-research-report',
    num: 48,
    name: 'Deep Research Report',
    shortName: 'Deep Research',
    price: '3,500–15,000',
    type: 'fixed-scope',
    tagline: 'PhD-grade research on any market, technology, or topic.',
    description:
      'Commission a deep research report on any market, technology, sector, or scientific topic. Crimson Bench deploys researchers from our 150,000+ global network — including PhD scientists, former government analysts, and domain specialists — to produce a comprehensive, citation-rich report within 10–15 business days.',
    includes: [
      'Primary and secondary research synthesis',
      'Expert interviews with domain specialists',
      'Data analysis and visualization',
      'Executive summary and key findings (2–3 pages)',
      'Full report with citations (20–60 pages)',
      'Optional live presentation to leadership team',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'scientific-literature-synthesis',
    num: 49,
    name: 'Scientific Literature Synthesis',
    shortName: 'Lit Synthesis',
    price: '2,500–8,000',
    type: 'fixed-scope',
    tagline: 'Systematic review of scientific literature for business decisions.',
    description:
      'A systematic review and synthesis of the scientific literature on any topic relevant to your business — drug mechanisms, materials science, AI/ML methods, climate models, or emerging technologies. Delivered by a PhD-level scientist from our network in a business-ready format your leadership team can act on.',
    includes: [
      'Systematic search across PubMed, arXiv, Web of Science, and proprietary databases',
      'Quality assessment and study grading',
      'Plain-English synthesis for business audiences',
      'Key findings and uncertainty assessment',
      'Implications for business strategy',
      'Literature database delivered in organized format',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'commissioned-whitepaper',
    num: 50,
    name: 'Commissioned Whitepaper',
    shortName: 'Whitepaper',
    price: '5,000–20,000',
    type: 'fixed-scope',
    tagline: 'Authoritative thought leadership. Written by domain experts.',
    description:
      'A rigorously researched whitepaper authored by domain experts from The Crimson Bench and our 150,000+ global network. Published under your brand or co-branded with Crimson Bench. Includes primary research, expert interviews, and data analysis — producing content that earns citations, drives SEO, and positions your company as the category authority.',
    includes: [
      'Topic development and research brief',
      'Primary research and expert interviews',
      'Data analysis and original insights',
      'Professionally written whitepaper (2,500–8,000 words)',
      'Infographic and data visualization package',
      'Distribution strategy recommendation',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'competitive-intelligence-report',
    num: 51,
    name: 'Competitive Intelligence Report',
    shortName: 'Competitive Intel',
    price: '3,000–12,000',
    type: 'fixed-scope',
    tagline: 'Deep competitive intelligence from primary sources.',
    description:
      'A primary-source competitive intelligence report on your top 3–5 competitors. Crimson Bench researchers conduct expert interviews, analyze public filings, patent databases, job postings, and customer reviews to build the most complete competitive picture available without insider access.',
    includes: [
      'Competitor product, pricing, and positioning analysis',
      'Win/loss pattern analysis and messaging weaknesses',
      'Technology and IP landscape mapping',
      'Key personnel tracking and talent intelligence',
      'Regulatory and legal exposure assessment',
      'Competitive scorecard and strategic implications',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'technology-landscape-analysis',
    num: 52,
    name: 'Technology Landscape Analysis',
    shortName: 'Tech Landscape',
    price: '5,000–18,000',
    type: 'fixed-scope',
    tagline: 'What technologies will define your industry in 3 years.',
    description:
      'A comprehensive analysis of the technology landscape in your industry — covering emerging technologies, adoption curves, build vs. buy options, and the technology bets your competitors are making. Conducted by CTO-level executives and PhD technologists from our global network.',
    includes: [
      'Current technology stack benchmarking vs. industry',
      'Emerging technology identification and timeline mapping',
      'Vendor landscape mapping and comparison',
      'Build vs. buy vs. partner decision framework',
      'Technology investment prioritization matrix',
      'Technology Landscape Report (25–40 pages)',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'patent-ip-landscape',
    num: 53,
    name: 'Patent & IP Landscape Analysis',
    shortName: 'IP Landscape',
    price: '4,000–14,000',
    type: 'fixed-scope',
    tagline: 'Who owns the technology in your space.',
    description:
      'A patent and intellectual property landscape analysis conducted by our network of IP specialists and domain scientists. Identifies freedom-to-operate constraints, emerging patent thickets, licensing opportunities, and IP acquisition targets — critical for product development, M&A diligence, and competitive strategy.',
    includes: [
      'Patent landscape mapping by technology area',
      'Key patent holder identification and analysis',
      'Freedom-to-operate assessment',
      'Expiring patent opportunity identification',
      'IP acquisition and licensing opportunity mapping',
      'Written IP Landscape Report with strategic implications',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'market-sizing-study',
    num: 54,
    name: 'Market Sizing Study',
    shortName: 'Market Sizing',
    price: '4,000–12,000',
    type: 'fixed-scope',
    tagline: 'Bottoms-up TAM, SAM, SOM analysis from primary research.',
    description:
      'A rigorous market sizing study that goes beyond published reports to build a bottoms-up TAM/SAM/SOM analysis using primary research, expert interviews, and proprietary data triangulation. Used by PE/VC investors, strategy teams, and boards to justify investment theses and market entry decisions.',
    includes: [
      'Top-down and bottoms-up market sizing methodology',
      'Primary interviews with market participants',
      'Customer segmentation and willingness-to-pay analysis',
      'Geographic and vertical market disaggregation',
      'Market sizing model (Excel/Google Sheets) with drivers',
      'Written Market Sizing Report with methodology appendix',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'regulatory-intelligence-report',
    num: 55,
    name: 'Regulatory Intelligence Report',
    shortName: 'Regulatory Intel',
    price: '3,500–10,000',
    type: 'fixed-scope',
    tagline: 'Regulatory risk and opportunity mapping for any sector.',
    description:
      'A regulatory intelligence report covering the regulatory environment in your sector and jurisdiction — including upcoming rule changes, enforcement trends, compliance cost trajectories, and regulatory arbitrage opportunities. Delivered by former government officials, regulatory attorneys, and compliance executives from our network.',
    includes: [
      'Current regulatory environment overview',
      'Upcoming rule changes and impact timeline',
      'Enforcement trend analysis',
      'Compliance cost benchmarking vs. peers',
      'Regulatory risk and opportunity matrix',
      'Written Regulatory Intelligence Report with action recommendations',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'consumer-survey-research',
    num: 56,
    name: 'Consumer Survey & Primary Research',
    shortName: 'Consumer Research',
    price: '5,000–15,000',
    type: 'fixed-scope',
    tagline: 'Custom survey design, fielding, and analysis.',
    description:
      'A custom consumer or B2B research study — including questionnaire design, panel fielding, and analysis — delivered by Crimson Bench research specialists. Ideal for product-market fit validation, pricing research, brand health measurement, and customer satisfaction benchmarking.',
    includes: [
      'Research question definition and hypothesis development',
      'Questionnaire design and validation',
      'Panel selection and survey fielding (N=200–500+)',
      'Statistical analysis and significance testing',
      'Data visualization and executive summary',
      'Raw data delivery in preferred format',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'economic-impact-analysis',
    num: 57,
    name: 'Economic Impact Analysis',
    shortName: 'Economic Impact',
    price: '8,000–25,000',
    type: 'fixed-scope',
    tagline: 'Quantify the economic impact of your business or policy.',
    description:
      'An economic impact analysis quantifying the direct, indirect, and induced economic effects of your business, investment, or policy initiative. Used by companies for investor relations, government affairs, grant applications, public relations, and stakeholder communications. Delivered by economists and quantitative analysts from our global network.',
    includes: [
      'Direct, indirect, and induced impact modeling',
      'Jobs created and wages supported analysis',
      'Tax revenue and GDP contribution estimates',
      'Regional and sector-level economic multipliers',
      'Peer comparison and benchmarking',
      'Publication-quality Economic Impact Report',
    ],
    stripeMode: 'payment',
    isNew: true,
  },

  // ─── DATA & MODELING SERVICES ─────────────────────────────────────────────

  {
    id: 'custom-dataset',
    num: 58,
    name: 'Custom Dataset Compilation',
    shortName: 'Custom Dataset',
    price: '5,000–20,000',
    type: 'fixed-scope',
    tagline: 'Proprietary datasets built for your analysis.',
    description:
      'Commission a custom dataset compiled and cleaned by Crimson Bench data specialists. Datasets include scraped web data, public records aggregation, alternative data, satellite imagery analysis, or structured expert-sourced data — formatted and documented for immediate use in your analysis or model.',
    includes: [
      'Data source identification and sourcing strategy',
      'Data collection, cleaning, and normalization',
      'Data documentation and codebook',
      'Quality assurance and completeness verification',
      'Delivery in preferred format (CSV, JSON, SQL, API)',
      'Optional ongoing update/refresh subscription',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'financial-model-build',
    num: 59,
    name: 'Financial Model Build',
    shortName: 'Financial Model',
    price: '3,500–12,000',
    type: 'fixed-scope',
    tagline: 'Board-ready 3-statement model built by CFO-level analysts.',
    description:
      'A custom financial model built by Crimson Bench CFO-level analysts — three-statement (P&L, balance sheet, cash flow), integrated, with scenario analysis, sensitivity tables, and investor-grade presentation. Used for board presentations, fundraising, strategic planning, and M&A processes.',
    includes: [
      '3-statement integrated financial model',
      'Revenue and cost driver assumptions documentation',
      'Scenario analysis (base, bear, bull cases)',
      'Sensitivity analysis on key drivers',
      'Valuation model (DCF and comps)',
      'Investor-grade output formatting',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'business-scenario-simulation',
    num: 60,
    name: 'Business Scenario Simulation',
    shortName: 'Scenario Sim',
    price: '5,000–18,000',
    type: 'fixed-scope',
    tagline: 'What-if simulations for strategic decisions.',
    description:
      'A quantitative business scenario simulation for major strategic decisions — market entry, pricing strategy, capacity expansion, M&A integration, or competitive response. Built by quantitative analysts and operations researchers from our network using Monte Carlo and agent-based simulation methods.',
    includes: [
      'Decision framing and key variable identification',
      'Model architecture and assumption documentation',
      'Monte Carlo or agent-based simulation build',
      'Output analysis and probability distributions',
      'Sensitivity analysis and decision thresholds',
      'Simulation model and presentation deliverables',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'demand-forecasting-model',
    num: 61,
    name: 'Demand Forecasting Model',
    shortName: 'Demand Forecast',
    price: '6,000–15,000',
    type: 'fixed-scope',
    tagline: 'ML-powered demand forecasting for planning and inventory.',
    description:
      'A machine learning-powered demand forecasting model built on your historical sales and operational data. Crimson Bench data scientists from our 150,000+ global network build, validate, and deploy models that outperform traditional time-series methods — reducing inventory costs and improving planning accuracy.',
    includes: [
      'Historical data analysis and feature engineering',
      'Model selection and validation (ARIMA, XGBoost, Prophet, or custom)',
      'Accuracy benchmarking vs. current forecasting method',
      'Model documentation and retraining protocol',
      'Dashboard integration (Tableau, Power BI, or custom)',
      'Ongoing support for 90 days post-delivery',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'operations-research-optimization',
    num: 62,
    name: 'Operations Research & Optimization',
    shortName: 'Ops Research',
    price: '8,000–25,000',
    type: 'fixed-scope',
    tagline: 'Mathematical optimization of your operations.',
    description:
      'Mathematical optimization of your operational processes — supply chain routing, workforce scheduling, pricing optimization, facility location, or production planning. Crimson Bench operations researchers build and deploy optimization models that generate measurable cost savings and efficiency improvements.',
    includes: [
      'Process mapping and bottleneck identification',
      'Mathematical model formulation',
      'Optimization algorithm selection and implementation',
      'Constraint analysis and trade-off quantification',
      'Implementation roadmap and change management guide',
      'Estimated ROI and payback period analysis',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'supply-chain-intelligence',
    num: 63,
    name: 'Supply Chain Intelligence Report',
    shortName: 'Supply Chain Intel',
    price: '6,000–18,000',
    type: 'fixed-scope',
    tagline: 'End-to-end supply chain risk and opportunity assessment.',
    description:
      'A comprehensive supply chain intelligence report covering supplier risk, logistics cost benchmarking, nearshoring/reshoring opportunities, geopolitical exposure, and supply chain resilience assessment. Delivered by former supply chain executives, PhD engineers, and trade specialists from our global network.',
    includes: [
      'Supplier concentration and single-source risk mapping',
      'Logistics cost benchmarking and optimization opportunities',
      'Geopolitical and tariff risk assessment by input category',
      'Nearshoring and reshoring feasibility analysis',
      'Resilience scorecard and scenario planning',
      'Supply Chain Intelligence Report with strategic recommendations',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'monte-carlo-risk-simulation',
    num: 64,
    name: 'Monte Carlo Risk Simulation',
    shortName: 'Risk Simulation',
    price: '5,000–15,000',
    type: 'fixed-scope',
    tagline: 'Quantify your strategic uncertainty with probability distributions.',
    description:
      'A Monte Carlo risk simulation that replaces point estimates with probability distributions across your key business variables — revenue, costs, time-to-market, regulatory approval, or any other uncertain input. Used by CFOs, boards, and investors to make better decisions under uncertainty.',
    includes: [
      'Uncertainty identification and variable mapping',
      'Probability distribution fitting to historical or expert data',
      'Monte Carlo simulation build (10,000+ iterations)',
      'Output distribution analysis and P10/P50/P90 reporting',
      'Sensitivity analysis and key risk driver identification',
      'Simulation model and board-ready presentation',
    ],
    stripeMode: 'payment',
    isNew: true,
  },

  // ─── SCIENTIFIC & TECHNICAL ADVISORY ─────────────────────────────────────

  {
    id: 'deep-tech-due-diligence',
    num: 65,
    name: 'Deep Tech Due Diligence',
    shortName: 'Deep Tech DD',
    price: '10,000–35,000',
    type: 'fixed-scope',
    tagline: 'PhD-level technical diligence on deep tech companies.',
    description:
      'A PhD-level technical due diligence assessment for investors evaluating deep technology companies — AI/ML, biotech, cleantech, advanced materials, robotics, semiconductors, or quantum computing. Crimson Bench deploys domain scientists and engineers who can assess technical feasibility, IP defensibility, and development risk at a level that generalist advisors cannot.',
    includes: [
      'Technical feasibility assessment by domain scientists',
      'IP and trade secret depth assessment',
      'Technology development risk and timeline analysis',
      'Competitive technology benchmarking',
      'Team technical capability assessment',
      'Written Deep Tech DD Report (15–25 pages)',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'scientific-advisory-panel',
    num: 66,
    name: 'Scientific Advisory Panel',
    shortName: 'SAB / Advisory Panel',
    price: '8,000–25,000',
    priceSuffix: '/year',
    type: 'annual',
    tagline: 'Assemble a world-class SAB from our 150K network.',
    description:
      'Crimson Bench assembles and manages a custom Scientific Advisory Board (SAB) from our global network of 150,000+ scientists, engineers, and technical experts — matched precisely to your technology domain, research stage, and regulatory pathway. Includes advisory agreement structuring, compensation design, and meeting facilitation.',
    includes: [
      'SAB needs assessment and profile design',
      'Expert search and matching across 150,000+ network',
      'Advisory agreement and equity/cash compensation structuring',
      'Meeting facilitation and agenda design',
      'IP protection protocols and conflict management',
      'Annual renewal and SAB composition review',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'rd-strategy-advisory',
    num: 67,
    name: 'R&D Strategy & Lab Design',
    shortName: 'R&D Strategy',
    price: '10,000–30,000',
    type: 'fixed-scope',
    tagline: 'Build the R&D function your technology requires.',
    description:
      'A comprehensive R&D strategy and laboratory design engagement for companies building deep technology products. Crimson Bench deploys CTO-level executives and PhD researchers to design your R&D organization, prioritize research programs, define build/partner/acquire decisions, and establish the operational cadence for a world-class research function.',
    includes: [
      'R&D program prioritization and resource allocation',
      'Lab infrastructure and equipment planning',
      'Research team structure and hiring plan',
      'IP capture and publication strategy',
      'External collaboration and university partnership strategy',
      'R&D roadmap (3-year) and milestone framework',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'ai-ml-strategy',
    num: 68,
    name: 'AI & Machine Learning Strategy',
    shortName: 'AI/ML Strategy',
    price: '10,000–30,000',
    type: 'fixed-scope',
    tagline: 'Build your AI roadmap with AI practitioners, not consultants.',
    description:
      'An AI and machine learning strategy engagement delivered by actual AI/ML practitioners — PhD researchers, former AI lab leads, and production ML engineers — from our 150,000-person global network. Defines your AI use cases, data strategy, model deployment approach, and build/buy/partner decisions.',
    includes: [
      'AI use case identification and ROI prioritization',
      'Data strategy and data readiness assessment',
      'Build vs. buy vs. fine-tune decision framework',
      'ML infrastructure and MLOps architecture recommendation',
      'AI talent strategy and team structure',
      'AI Strategy Roadmap (18-month) with investment requirements',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'climate-sustainability-assessment',
    num: 69,
    name: 'Climate & Sustainability Assessment',
    shortName: 'ESG Assessment',
    price: '8,000–25,000',
    type: 'fixed-scope',
    tagline: 'GHG inventory, ESG gap analysis, and net-zero roadmap.',
    description:
      'A comprehensive climate and sustainability assessment conducted by environmental scientists, ESG specialists, and former sustainability officers from our network. Includes GHG inventory (Scope 1, 2, 3), regulatory compliance gap analysis, ESG reporting framework selection, and a practical net-zero transition roadmap.',
    includes: [
      'Greenhouse gas inventory (Scope 1, 2, and 3)',
      'ESG materiality assessment',
      'Regulatory compliance gap analysis (SEC, EU CSRD, etc.)',
      'ESG reporting framework selection (GRI, SASB, TCFD)',
      'Net-zero transition roadmap and carbon offset strategy',
      'Board ESG governance framework',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'biotech-pharma-advisory',
    num: 70,
    name: 'Biotech & Pharma Development Advisory',
    shortName: 'Biotech Advisory',
    price: 'Custom',
    type: 'custom',
    tagline: 'Drug development and regulatory strategy from the bench.',
    description:
      'Strategic advisory for biotech and pharmaceutical companies navigating IND filing, clinical trial design, regulatory strategy, CMC development, and partnering/licensing decisions. Crimson Bench deploys former FDA officials, clinical development VPs, and biostatisticians from our 150,000+ global network.',
    includes: [
      'Regulatory strategy and IND/NDA/BLA pathway planning',
      'Clinical development plan review and optimization',
      'CMC (Chemistry, Manufacturing, and Controls) advisory',
      'Biostatistics and study design review',
      'Partnering, licensing, and co-development strategy',
      'KOL identification and medical affairs strategy',
    ],
    stripeMode: 'custom',
    isNew: true,
  },

  // ─── SOCIAL MEDIA & DIGITAL CONTENT ──────────────────────────────────────

  {
    id: 'social-media-strategy',
    num: 71,
    name: 'Social Media Strategy & Audit',
    shortName: 'Social Strategy',
    price: '3,500–10,000',
    type: 'fixed-scope',
    tagline: 'Your social presence audited. A 12-month strategy built.',
    description:
      'A comprehensive social media strategy engagement covering platform audit, audience analysis, content strategy, posting cadence, and influencer/partnership opportunities. Delivered by former social media directors and digital marketing executives with proven track records at B2B and B2C brands.',
    includes: [
      'Current platform audit and competitive benchmarking',
      'Audience persona and platform prioritization',
      'Content pillar development and brand voice guide',
      '12-month editorial calendar template',
      'Paid social strategy and budget recommendation',
      'KPI framework and measurement dashboard setup',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'executive-linkedin-ghostwriting',
    num: 72,
    name: 'Executive LinkedIn Ghostwriting',
    shortName: 'LinkedIn Ghostwriting',
    price: 2000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Your voice. Our writers. LinkedIn credibility that compounds.',
    description:
      'Monthly LinkedIn ghostwriting for C-suite executives who want a dominant thought leadership presence but cannot write consistently themselves. A dedicated Crimson Bench writer — a former executive or journalist with domain expertise — interviews you monthly and publishes 8–12 posts in your voice.',
    includes: [
      '8–12 LinkedIn posts per month in your voice',
      'Monthly 60-minute interview to capture your perspectives',
      'Profile optimization (headline, about section, featured)',
      'Engagement monitoring and response recommendations',
      'Monthly analytics report and growth tracking',
      '14-day cancellation policy',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'thought-leadership-program',
    num: 73,
    name: 'Thought Leadership Program',
    shortName: 'Thought Leadership',
    price: 3000,
    priceSuffix: '/month',
    type: 'monthly',
    tagline: 'Category authority. Monthly. Multi-channel.',
    description:
      'A comprehensive thought leadership program that builds your or your organization\'s authority across LinkedIn, industry publications, podcasts, and speaking engagements. A Crimson Bench editorial and PR team manages the full content calendar, pitch pipeline, and publication relationships on your behalf.',
    includes: [
      'Monthly content strategy and editorial calendar',
      'LinkedIn ghostwriting (8–12 posts/month)',
      'Bylined article pitching and placement (2–3/month)',
      'Podcast booking and preparation (1–2/month)',
      'Speaking opportunity identification and application',
      'Monthly impact report with media coverage tracking',
    ],
    stripeMode: 'subscription',
    isNew: true,
  },
  {
    id: 'corporate-podcast-strategy',
    num: 74,
    name: 'Corporate Podcast Strategy & Launch',
    shortName: 'Podcast Launch',
    price: '5,000–15,000',
    type: 'fixed-scope',
    tagline: 'Concept to launch in 60 days. Expert guests included.',
    description:
      'End-to-end podcast strategy and launch for companies, executives, or PE firms that want a podcast as a channel for thought leadership, deal sourcing, or community building. Crimson Bench handles concept development, format design, guest sourcing (from our 25K+ exec network), production setup, and distribution strategy.',
    includes: [
      'Podcast concept and positioning development',
      'Format design (interview, panel, narrative, or hybrid)',
      'Technical setup (recording, editing, hosting)',
      'First 8-episode guest sourcing and booking',
      'Distribution and promotion strategy',
      'Launch PR and cross-promotion plan',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'brand-positioning',
    num: 75,
    name: 'Brand Positioning & Messaging',
    shortName: 'Brand Positioning',
    price: '6,000–18,000',
    type: 'fixed-scope',
    tagline: 'Positioning strategy and a complete messaging framework.',
    description:
      'A strategic brand positioning engagement that defines your category position, core value proposition, messaging hierarchy, and proof points — for companies that need to reposition, relaunch, or sharpen their story for fundraising, sales, or market entry. Delivered by former CMOs and brand strategists.',
    includes: [
      'Competitive positioning audit',
      'Customer and prospect voice-of-customer research',
      'Core value proposition development',
      'Messaging hierarchy and proof point framework',
      'Persona-specific messaging variants',
      'Brand messaging guide (30–50 page deliverable)',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'crisis-communications-strategy',
    num: 76,
    name: 'Crisis Communications Strategy',
    shortName: 'Crisis Comms',
    price: '5,000–20,000',
    type: 'fixed-scope',
    tagline: 'Build your crisis playbook before you need it.',
    description:
      'A crisis communications strategy and preparedness engagement for companies, boards, and executives who want a pre-built crisis response capability before a crisis occurs. Includes scenario planning, communications protocols, spokesperson training, and media relationship guidance. Also available as a rapid-response retainer.',
    includes: [
      'Crisis scenario identification and prioritization',
      'Crisis communications protocol and decision tree',
      'Spokesperson identification and media training',
      'Pre-approved holding statements by scenario',
      'Stakeholder communication mapping',
      'Crisis simulation exercise with debrief',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'influencer-creator-strategy',
    num: 77,
    name: 'Influencer & Creator Strategy',
    shortName: 'Influencer Strategy',
    price: '3,500–10,000',
    type: 'fixed-scope',
    tagline: 'B2B and B2C influencer strategy for modern brands.',
    description:
      'A comprehensive influencer and creator strategy defining your approach to working with LinkedIn thought leaders, industry podcasters, YouTube creators, or traditional social media influencers. Includes creator identification, compensation structuring, brief development, and performance measurement framework.',
    includes: [
      'Influencer landscape mapping by platform and niche',
      'Creator persona development and audience alignment scoring',
      'Compensation benchmarking (flat fee, CPA, equity)',
      'Brief template and content approval workflow',
      'FTC compliance guidance',
      'Influencer Strategy Playbook and measurement dashboard',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
  {
    id: 'content-strategy',
    num: 78,
    name: 'Content Strategy & Editorial Calendar',
    shortName: 'Content Strategy',
    price: '4,000–12,000',
    type: 'fixed-scope',
    tagline: 'A year of content strategy. Executed with SEO precision.',
    description:
      'A comprehensive content strategy that defines your content pillars, SEO keyword targets, editorial calendar, distribution channels, and repurposing workflow. Delivered by former editorial directors, CMOs, and SEO specialists from our network — producing a content plan your team can execute without further consulting support.',
    includes: [
      'Content audit and competitive content benchmarking',
      'SEO keyword research and cluster mapping',
      'Content pillar and topic framework',
      'Full 12-month editorial calendar',
      'Distribution and repurposing workflow',
      'Content performance measurement framework',
    ],
    stripeMode: 'payment',
    isNew: true,
  },
]

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id)
}

export function getMonthlyProducts(): Product[] {
  return PRODUCTS.filter(p => p.type === 'monthly')
}

export function getOneTimeProducts(): Product[] {
  return PRODUCTS.filter(p => p.type === 'one-time' || p.type === 'fixed-scope')
}

export function formatPrice(product: Product): string {
  if (typeof product.price === 'number') {
    return `$${product.price.toLocaleString()}${product.priceSuffix ?? ''}`
  }
  return `$${product.price}${product.priceSuffix ?? ''}`
}
